/** Labelled fixtures for the decision bench. Hand-written; extend freely. */

export type Tier = 'cheap' | 'standard' | 'frontier';

export const ROUTING_FIXTURES: { prompt: string; label: Tier }[] = [
  // cheap
  { prompt: 'What tasks are due today?', label: 'cheap' },
  { prompt: 'Mark the bulletin proofread task as done.', label: 'cheap' },
  { prompt: 'Is the Fellowship Hall free Friday at 6pm?', label: 'cheap' },
  { prompt: 'Rename the "Easter setup" rhythm to "Easter weekend setup".', label: 'cheap' },
  { prompt: 'How many unread messages do I have?', label: 'cheap' },
  { prompt: 'What time does the Sunday service start?', label: 'cheap' },
  { prompt: 'Fix the typo in the first line of this announcement: "Welcom to church".', label: 'cheap' },
  { prompt: 'Add a task: call the sound vendor tomorrow.', label: 'cheap' },
  { prompt: 'List my open pull requests.', label: 'cheap' },
  { prompt: 'Who is scheduled for nursery this Sunday?', label: 'cheap' },
  { prompt: 'Convert this date to MM/DD/YYYY: March 4th, 2027.', label: 'cheap' },
  { prompt: 'Archive the email from the printer about the invoice.', label: 'cheap' },
  { prompt: 'What does the acronym PCO stand for here?', label: 'cheap' },
  { prompt: 'Change the due date of the volunteer thank-you task to Friday.', label: 'cheap' },
  { prompt: 'Show me the last commit message on this branch.', label: 'cheap' },
  // standard
  { prompt: 'Draft a friendly email to the volunteer team thanking them for Easter weekend and asking for feedback.', label: 'standard' },
  { prompt: 'Summarize this week\'s message threads and list any follow-ups I owe people.', label: 'standard' },
  { prompt: 'Plan next week\'s staff schedule around the two facility reservations and the Wednesday youth night.', label: 'standard' },
  { prompt: 'Create a weekly rhythm for Sunday setup with six steps and assign owners based on last month\'s roster.', label: 'standard' },
  { prompt: 'Pull the service plan from Planning Center and write a run-of-show for the tech team.', label: 'standard' },
  { prompt: 'Write a unit test for the recurring-rule parser that covers weekly and monthly cases.', label: 'standard' },
  { prompt: 'Add a "notes" field to the reservation dialog and wire it to the API in the Flutter view.', label: 'standard' },
  { prompt: 'Turn these meeting notes into action items with owners and due dates.', label: 'standard' },
  { prompt: 'Find my emails from this week about the building repair and draft a status update for the elders.', label: 'standard' },
  { prompt: 'Write a project template for hosting a community outreach event, with milestones.', label: 'standard' },
  { prompt: 'Reply to the caterer\'s quote and negotiate for a smaller minimum order.', label: 'standard' },
  { prompt: 'Refactor this Express controller to use the repository helper and update its tests.', label: 'standard' },
  { prompt: 'Compare last three months of facility reservations and tell me which rooms are underused.', label: 'standard' },
  { prompt: 'Create a Canva-ready outline for the fall sermon series announcement with a headline and three bullets.', label: 'standard' },
  { prompt: 'Fix the failing vitest for the tasks controller and explain what was wrong.', label: 'standard' },
  // frontier
  { prompt: 'Design a sync architecture so the desktop app can work offline and reconcile task edits with the production Postgres without losing changes, including conflict resolution rules.', label: 'frontier' },
  { prompt: 'The API server intermittently returns stale reservations after a create; trace through the repository, cache and migration layers and find the root cause.', label: 'frontier' },
  { prompt: 'Review our OAuth token storage and agent local-auth bypass for security weaknesses and propose a prioritized remediation plan.', label: 'frontier' },
  { prompt: 'Plan and execute a migration of the SQLite schema to support multi-campus organizations, including data backfill, rollback strategy and API compatibility.', label: 'frontier' },
  { prompt: 'Think through whether we should replace polling with a websocket push for triggers, weighing failure modes, battery, ordering guarantees and rollout risk.', label: 'frontier' },
  { prompt: 'Refactor the agent runner across all providers to share one tool-dispatch abstraction, keeping streaming behavior identical, and make a step-by-step plan first.', label: 'frontier' },
  { prompt: 'Analyze two years of giving, attendance and volunteer data and propose a strategy for the next three years, with the assumptions and risks explicit.', label: 'frontier' },
  { prompt: 'Our notarized macOS build crashes on launch only on Apple silicon after signing; diagnose the entitlements and native module interplay.', label: 'frontier' },
  { prompt: 'Design the permission model for letting ministry leaders delegate rhythms and facilities to sub-teams while auditors can see everything, and prove it has no privilege escalation paths.', label: 'frontier' },
  { prompt: 'There is a race between the recurring-rule generator and manual task edits that duplicates tasks around DST changes; reproduce it, fix it, and write regression tests.', label: 'frontier' },
  { prompt: 'Evaluate three approaches for ranking which memories to inject into prompts and recommend one, including how we would measure success offline and in production.', label: 'frontier' },
  { prompt: 'Restructure the Flutter navigation and state management so screens can be lazily loaded without breaking deep links or provider lifetimes; outline the migration in stages.', label: 'frontier' },
  { prompt: 'Investigate why memory retrieval latency doubled after the last release across FTS and Engraph, and design a fix that does not regress recall.', label: 'frontier' },
  { prompt: 'Draft a disaster-recovery plan for the church\'s data across Planning Center, Google Workspace and our own servers, with tested restore procedures.', label: 'frontier' },
  { prompt: 'Audit the whole Planning Center integration for rate-limit, pagination and data-consistency bugs and fix the most serious ones.', label: 'frontier' },
];

/** Server pool: id -> representative tool ids. Document text = "id: tool, tool". */
export const TOOL_SERVERS: Record<string, string[]> = {
  gmail: ['search_threads', 'get_thread', 'send_message', 'create_draft', 'reply', 'label_thread'],
  google_calendar: ['list_events', 'create_event', 'update_event', 'suggest_time', 'respond_to_event'],
  google_drive: ['search_files', 'read_file_content', 'create_file', 'share_file', 'list_recent_files'],
  planning_center: ['list_service_plans', 'get_plan_items', 'list_people', 'list_songs', 'schedule_volunteer', 'list_check_ins'],
  github: ['list_pull_requests', 'create_pull_request', 'get_file_contents', 'search_code', 'issue_read', 'list_commits'],
  rhythm: ['list_tasks', 'create_task', 'list_rhythms', 'list_projects', 'reserve_facility', 'send_message_thread'],
  vercel: ['list_deployments', 'get_deployment', 'get_runtime_logs', 'list_projects', 'add_project_domain'],
  canva: ['generate_design', 'create_design', 'export_design', 'search_designs', 'resize_design'],
  buffer: ['create_post', 'list_posts', 'list_channels', 'get_aggregated_post_metrics'],
  playwright: ['browser_navigate', 'browser_click', 'browser_snapshot', 'browser_take_screenshot', 'browser_fill_form'],
};

export const TOOL_FIXTURES: { prompt: string; expected: string[] }[] = [
  { prompt: 'Find the email from the printer about the bulletin invoice', expected: ['gmail'] },
  { prompt: 'Send a thank-you note to the volunteer team', expected: ['gmail'] },
  { prompt: 'What is on my calendar tomorrow afternoon?', expected: ['google_calendar'] },
  { prompt: 'Find a time next week when the pastor and I are both free for an hour', expected: ['google_calendar'] },
  { prompt: 'Open the budget spreadsheet in Drive and tell me the total for facilities', expected: ['google_drive'] },
  { prompt: 'Share the volunteer handbook with the new nursery coordinator', expected: ['google_drive'] },
  { prompt: 'Who is serving on the worship team this Sunday?', expected: ['planning_center'] },
  { prompt: 'Pull the order of service and song list for the 10am service', expected: ['planning_center'] },
  { prompt: 'Check how many kids checked in last Sunday', expected: ['planning_center'] },
  { prompt: 'Open a pull request for the reservation dialog changes', expected: ['github'] },
  { prompt: 'Search the repo for where recurring rules get expanded', expected: ['github'] },
  { prompt: 'Which issues are still open on the Rhythm repository?', expected: ['github'] },
  { prompt: 'Add a task to order communion supplies', expected: ['rhythm'] },
  { prompt: 'Reserve the Main Hall for Saturday at 2pm for a wedding rehearsal', expected: ['rhythm'] },
  { prompt: 'Show my recurring rhythms for staff meetings', expected: ['rhythm'] },
  { prompt: 'Why did the last production deploy fail?', expected: ['vercel'] },
  { prompt: 'Point the new domain at the church website project', expected: ['vercel'] },
  { prompt: 'Make a flyer for the fall potluck', expected: ['canva'] },
  { prompt: 'Resize our Easter graphic for Instagram stories', expected: ['canva'] },
  { prompt: 'Schedule a post about Sunday\'s sermon for tomorrow morning', expected: ['buffer'] },
  { prompt: 'How did our Facebook posts perform last month?', expected: ['buffer'] },
  { prompt: 'Go to the giving portal and take a screenshot of the dashboard', expected: ['playwright'] },
  { prompt: 'Fill in the online form on the county permit website', expected: ['playwright'] },
  { prompt: 'Email the caterer and put the delivery on my calendar', expected: ['gmail', 'google_calendar'] },
  { prompt: 'Look up the service plan and create a task for each tech cue', expected: ['planning_center', 'rhythm'] },
];

export const MEMORY_BANK: Record<string, string> = {
  bullets: 'AJ prefers meeting notes as bullet lists',
  sunday: 'Sunday service setup starts 7am in the Main Hall',
  pco: 'Planning Center service plans are published every Wednesday',
  email: "AJ likes email replies short, friendly, and signed 'AJ'",
  tz: 'The church office is in Visalia, California (Pacific time)',
  youth: 'Youth group meets Wednesday evenings in the Fellowship Hall',
  budget: 'Facilities budget requests are due to the finance committee by the 15th of each month',
  pastor: 'Pastor Dan does not take meetings on Mondays',
  vendor: 'The sound system vendor is Central Valley AV; their contact is Maria',
  comm: 'Weekly announcements go out to the congregation on Thursdays',
  nursery: 'Nursery volunteers need a completed background check before serving',
  key: 'The building keys are kept in the lockbox by the east door',
  dietary: 'AJ is allergic to shellfish',
  coffee: 'AJ drinks oat-milk lattes',
  dog: "AJ's dog is named Biscuit",
  car: 'AJ drives a blue Honda Civic',
  projector: 'The Main Hall projector needs 10 minutes to warm up before service',
  tasks: 'Recurring tasks should default to weekly unless stated otherwise',
  code: 'AJ prefers TypeScript with strict mode and vitest for tests',
  git: "Branches in the Rhythm repo are named feat/<slug>, and PRs are never merged without AJ's review",
  easter: 'Easter sunrise service is held at the Mooney Grove Park amphitheater',
  volunteers: 'Volunteer schedules are managed in Planning Center Services with a 2-week lead time',
  giving: 'Online giving reports are reviewed by the treasurer on the first Monday of the month',
  wifi: 'The guest wifi password is posted in the lobby and rotates quarterly',
  newsletter: 'The monthly newsletter is drafted in Canva using the brand kit',
  social: 'Social posts are scheduled through Buffer, usually at 9am',
  calendar: 'Room reservation conflicts should be resolved in favor of worship events',
  name: "AJ's full name is AJ Hochhalter and he is the operations director",
  lunch: 'Staff lunch on Fridays is at noon; AJ usually orders tacos',
  summary: 'AJ wants summaries limited to three sentences',
};

/** `pool` ids are drawn from MEMORY_BANK; `relevant` is a subset of pool. */
export const MEMORY_FIXTURES: { query: string; pool: string[]; relevant: string[]; note?: string }[] = [
  { query: "How should I format the notes from today's staff meeting?", pool: ['bullets', 'pastor', 'sunday', 'coffee', 'dog', 'key', 'code', 'summary'], relevant: ['bullets'], note: 'lexical distractor: pastor' },
  { query: "What time do we need to be at the sanctuary to get ready on the Lord's day?", pool: ['sunday', 'youth', 'giving', 'dietary', 'car', 'tasks', 'wifi', 'name'], relevant: ['sunday'], note: 'semantic only' },
  { query: 'Draft a reply to the vendor about the speakers', pool: ['vendor', 'email', 'budget', 'pastor', 'dog', 'nursery', 'git', 'comm'], relevant: ['vendor', 'email'] },
  { query: 'Anything I should know before ordering food for the volunteer thank-you dinner?', pool: ['dietary', 'volunteers', 'coffee', 'budget', 'newsletter', 'key', 'car', 'code'], relevant: ['dietary'], note: 'semantic only; lexical distractor: volunteers' },
  { query: 'Where should I put the branch for the new feature?', pool: ['git', 'code', 'social', 'easter', 'comm', 'calendar', 'coffee', 'key'], relevant: ['git'] },
  { query: 'When does the congregation get the weekly update?', pool: ['comm', 'newsletter', 'pco', 'tz', 'dog', 'giving', 'nursery', 'youth'], relevant: ['comm'] },
  { query: "Someone new wants to help in the kids' room, what's required?", pool: ['nursery', 'volunteers', 'youth', 'key', 'wifi', 'car', 'budget', 'name'], relevant: ['nursery'], note: 'semantic only; lexical distractor: volunteers' },
  { query: 'Set up the recurring reminder for staff prayer', pool: ['tasks', 'comm', 'pastor', 'sunday', 'dog', 'coffee', 'social', 'wifi'], relevant: ['tasks'] },
  { query: 'How do I let a visitor get online?', pool: ['wifi', 'key', 'projector', 'pco', 'code', 'email', 'lunch', 'dog'], relevant: ['wifi'], note: 'semantic only' },
  { query: 'Which park is the dawn gathering for the spring holiday at?', pool: ['easter', 'sunday', 'youth', 'calendar', 'budget', 'car', 'dog', 'giving'], relevant: ['easter'], note: 'semantic only' },
  { query: 'Schedule the Facebook and Instagram posts for next week', pool: ['social', 'newsletter', 'comm', 'email', 'tz', 'code', 'key', 'coffee'], relevant: ['social'] },
  { query: 'Who reviews the donation numbers and when?', pool: ['giving', 'budget', 'volunteers', 'pco', 'name', 'lunch', 'pastor', 'wifi'], relevant: ['giving'], note: 'semantic only' },
  { query: 'Can I book the pastor for a 1:1 Monday morning?', pool: ['pastor', 'calendar', 'sunday', 'youth', 'tz', 'name', 'dog', 'car'], relevant: ['pastor'] },
  { query: 'Two events want the Fellowship Hall at the same time, who wins?', pool: ['calendar', 'youth', 'sunday', 'key', 'budget', 'projector', 'pco', 'lunch'], relevant: ['calendar'], note: 'lexical distractor: youth' },
  { query: "What's the deadline to submit money requests for the repair?", pool: ['budget', 'giving', 'vendor', 'key', 'tz', 'code', 'dog', 'summary'], relevant: ['budget'], note: 'semantic; lexical distractor: giving' },
];
