import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:provider/provider.dart';
import 'package:rhythm_desktop/features/agent_memory/controllers/agent_memory_controller.dart';
import 'package:rhythm_desktop/features/agent_memory/data/agent_memory_data_source.dart';
import 'package:rhythm_desktop/features/agent_memory/models/agent_memory_entry.dart';
import 'package:rhythm_desktop/features/agent_memory/repositories/agent_memory_repository.dart';
import 'package:rhythm_desktop/features/agent_memory/views/agent_memory_view.dart';

class _MemorySource extends AgentMemoryDataSource {
  _MemorySource(this.entries);

  final List<AgentMemoryEntry> entries;

  @override
  Future<List<AgentMemoryEntry>> list() async => entries;
}

AgentMemoryEntry _entry(
  String id,
  String state, {
  bool unverifiable = false,
}) =>
        AgentMemoryEntry(
      id: id,
      kind: 'fact',
      content: '$state memory $id',
      tags: const [],
      lifecycleState: state,
      staleAfter: state == 'stale' ? '2026-07-01' : null,
      generatedBy: 'agent:rhythm/1',
      generatedAt: '2026-07-28T12:00:00.000Z',
      trustTier: 'human',
      sources: const [
        {'id': 'runbook', 'type': 'document', 'ref': 'rhythm://runbook/1'},
      ],
      verificationCount: 2,
      unverifiable: unverifiable,
      createdAt: '2026-07-28T12:00:00.000Z',
      updatedAt: '2026-07-28T12:00:00.000Z',
    );

void main() {
  testWidgets(
      'issue-1219-c6: memory list shows lifecycle and read-only provenance',
      (tester) async {
    final controller = AgentMemoryController(
      AgentMemoryRepository(
        _MemorySource([
          _entry('active', 'active'),
          _entry('stale', 'stale'),
          _entry('deprecated', 'deprecated'),
          AgentMemoryEntry(
            id: 'unknown',
            kind: 'fact',
            content: 'unknown provenance',
            tags: const [],
            lifecycleState: 'active',
            unverifiable: true,
            createdAt: '2026-07-28T12:00:00.000Z',
            updatedAt: '2026-07-28T12:00:00.000Z',
          ),
        ]),
      ),
    );

    await tester.pumpWidget(
      ChangeNotifierProvider<AgentMemoryController>.value(
        value: controller,
        child: const MaterialApp(home: AgentMemoryView()),
      ),
    );
    await tester.pumpAndSettle();

    expect(find.text('Active'), findsNWidgets(2));
    expect(find.text('Stale'), findsOneWidget);
    expect(find.text('Deprecated'), findsOneWidget);
    expect(find.text('Unverifiable'), findsOneWidget);

    await tester.tap(find.text('stale memory stale'));
    await tester.pumpAndSettle();

    expect(find.text('Provenance'), findsOneWidget);
    expect(find.text('Generated by: agent:rhythm/1'), findsOneWidget);
    expect(
      find.text('Trust: human · 1 source · 2 verifications'),
      findsOneWidget,
    );
    expect(find.text('Stale after: 2026-07-01'), findsOneWidget);
    expect(find.byType(TextField), findsOneWidget);
  });
}
