export type ReadinessState = 'unconfigured' | 'missing' | 'unsupported' | 'unverified' | 'changed' | 'ready';
export type DayflowRecovery = 'configure' | 'check_source' | 'retry' | 'refresh_preview' | 'reload_list' | 'none';
export type DayflowErrorCode = 'INVALID_REQUEST' | 'CURSOR_INVALID' | 'SOURCE_MISSING' | 'SOURCE_UNSUPPORTED' | 'SOURCE_UNVERIFIED' | 'SOURCE_CHANGED' | 'DISABLED' | 'TIMEZONE_REQUIRED' | 'PREVIEW_EXPIRED' | 'PREVIEW_INVALIDATED' | 'SELECTION_CONFLICT' | 'PENDING_OPERATION' | 'CURSOR_STALE' | 'READER_TIMEOUT' | 'READER_CANCELLED' | 'READER_FAILED' | 'EXPORT_INVALID' | 'EXPORT_LIMIT' | 'TIMEZONE_MISMATCH' | 'IMPORT_UNCERTAIN' | 'LEDGER_UNAVAILABLE' | 'INTERNAL_ERROR' | 'OWNED_NOTE_NOT_FOUND' | 'LOCAL_ONLY' | 'FORBIDDEN_ORIGIN';
export interface SourceLabel { label: string; version: '2.6.0'; build: '133'; }
export interface SourceReadiness { state: ReadinessState; source: SourceLabel | null; code: DayflowErrorCode | null; }
export interface SourceCheckResponse extends SourceReadiness { selectionToken?: string; expiresAt?: string; }
export interface DayflowConfig { enabled: boolean; automaticImport: false; timezone: string | null; rolloverHour: 4; exclusions: string[]; maxRecordsPerRun: number; source: SourceLabel | null; }
export interface DayflowStatus { enabled: boolean; automaticImport: false; readiness: SourceReadiness; canPreview: boolean; importedCount: number; pendingCreateCount: number; pendingDeleteCount: number; }
export interface DayflowPreview { token: string; expiresAt: string; date: string; timeZone: string; coverage: 'existing_cards'; analysisCompleteness: 'unknown'; candidates: Array<{ candidateId: string; summary: string; observedStart: string; observedEnd?: string; category?: string; trust: 'unverified' }>; withheld: Array<{ recordIndex: number; code: 'SENSITIVE_CONTENT' | 'EMPTY_CONTENT' | 'SUMMARY_LIMIT' }>; }
export interface DayflowCommit { items: Array<{ candidateId: string; state: 'imported' | 'skipped' | 'conflict' | 'pending'; memoryId?: string; code?: DayflowErrorCode }>; }
export interface OwnedNote { memoryId: string; importedAt: string; state: 'imported' | 'pending_create' | 'pending_delete'; }
export interface OwnedNotesPage { items: OwnedNote[]; nextCursor: string | null; total: number; }
export interface DayflowGateway { getStatus(): Promise<DayflowStatus>; getReadiness(): Promise<SourceReadiness>; checkReadiness(bundlePath: string): Promise<SourceCheckResponse>; getConfig(): Promise<DayflowConfig>; updateConfig(patch: { enabled?: boolean; timezone?: string; exclusions?: string[]; maxRecordsPerRun?: number; sourceSelectionToken?: string }): Promise<DayflowConfig>; preview(date: string): Promise<DayflowPreview>; commit(token: string, candidateIds: string[]): Promise<DayflowCommit>; listOwned(limit?: number, cursor?: string): Promise<OwnedNotesPage>; forget(memoryId: string): Promise<{ memoryId: string; state: 'forgotten' }>; disable(): Promise<DayflowStatus>; }
export class DayflowGatewayError extends Error { constructor(public readonly code: DayflowErrorCode, public readonly retryable: boolean, public readonly recovery: DayflowRecovery, message: string) { super(message); } }
export const dayflowErrorMessages: Readonly<Record<DayflowErrorCode, string>> = { INVALID_REQUEST: 'Dayflow needs valid settings.', CURSOR_INVALID: 'The notes list cursor is invalid.', SOURCE_MISSING: 'Select an available Dayflow source.', SOURCE_UNSUPPORTED: 'This Dayflow source is unsupported.', SOURCE_UNVERIFIED: 'Verify the selected Dayflow source.', SOURCE_CHANGED: 'The selected Dayflow source changed.', DISABLED: 'Enable manual Dayflow integration first.', TIMEZONE_REQUIRED: 'Set a timezone before previewing.', PREVIEW_EXPIRED: 'This preview expired. Create a new preview.', PREVIEW_INVALIDATED: 'This preview is no longer valid. Create a new preview.', SELECTION_CONFLICT: 'Selected observations changed. Create a new preview.', PENDING_OPERATION: 'Dayflow is finishing an earlier operation.', CURSOR_STALE: 'The owned-notes list changed. Reloading it.', READER_TIMEOUT: 'Dayflow took too long. You can retry manually.', READER_CANCELLED: 'Dayflow reading was cancelled.', READER_FAILED: 'Dayflow could not read the selected source.', EXPORT_INVALID: 'The Dayflow export is invalid.', EXPORT_LIMIT: 'The Dayflow export exceeds the safe limit.', TIMEZONE_MISMATCH: 'The selected date does not match the configured timezone.', IMPORT_UNCERTAIN: 'The import outcome is uncertain. Check owned observations.', LEDGER_UNAVAILABLE: 'Owned observations are temporarily unavailable.', INTERNAL_ERROR: 'Dayflow is unavailable.', OWNED_NOTE_NOT_FOUND: 'That owned observation is no longer available.', LOCAL_ONLY: 'Dayflow management is available only locally.', FORBIDDEN_ORIGIN: 'Dayflow management is unavailable from this origin.' };
export function createLiveDayflowGateway(apiBase: string, localFetcher: typeof fetch): DayflowGateway {
  const request = async <T>(path: string, method = 'GET', body?: unknown): Promise<T> => { const response = await localFetcher(`${apiBase}/dayflow-integration${path}`, { method, headers: { accept: 'application/json', ...(body === undefined ? {} : { 'content-type': 'application/json' }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }), signal: AbortSignal.timeout(12_000) }); if (!response.ok) { const payload = await response.json().catch(() => null) as { error?: { code?: DayflowErrorCode; retryable?: boolean; recovery?: DayflowRecovery } } | null; const error = payload?.error; const code = error?.code && Object.hasOwn(dayflowErrorMessages, error.code) ? error.code : 'INTERNAL_ERROR'; const recovery: DayflowRecovery = error?.recovery && ['configure', 'check_source', 'retry', 'refresh_preview', 'reload_list', 'none'].includes(error.recovery) ? error.recovery : 'none'; throw new DayflowGatewayError(code, error?.retryable === true, recovery, dayflowErrorMessages[code]); } return response.json() as Promise<T>; };
  return { getStatus: () => request('/status'), getReadiness: () => request('/readiness'), checkReadiness: (bundlePath) => request('/readiness/check', 'POST', { bundlePath }), getConfig: () => request('/config'), updateConfig: (patch) => request('/config', 'PUT', patch), preview: (date) => request('/preview', 'POST', { date }), commit: (token, candidateIds) => request('/commit', 'POST', { token, candidateIds }), listOwned: (limit, cursor) => request(`/owned-notes?${new URLSearchParams({ ...(limit ? { limit: String(limit) } : {}), ...(cursor ? { cursor } : {}) })}`), forget: (memoryId) => request('/forget', 'POST', { memoryId }), disable: () => request('/disable', 'POST', {}) };
}
