// GENERATED FILE — DO NOT EDIT.
// Regenerate with: node scripts/generate-mobile-opencode-operations.mjs
// Source: apps/opencode_fork/packages/sdk/openapi.json

import type { MobileOpenCodeOperation } from './mobile_opencode_proxy_types';

export const MOBILE_OPENCODE_OPERATION_MANIFEST = [
  {"operationId":"app.agents","method":"GET","path":"/agent","allowed":true},
  {"operationId":"app.config.reload","method":"POST","path":"/config/reload","allowed":true},
  {"operationId":"app.log","method":"POST","path":"/log","allowed":false,"reason":"Mobile requests may not write arbitrary engine log payloads"},
  {"operationId":"app.skills","method":"GET","path":"/skill","allowed":true},
  {"operationId":"app.skills.reload","method":"POST","path":"/skill/reload","allowed":true},
  {"operationId":"auth.remove","method":"DELETE","path":"/auth/{providerID}","allowed":true},
  {"operationId":"auth.set","method":"PUT","path":"/auth/{providerID}","allowed":true},
  {"operationId":"command.list","method":"GET","path":"/command","allowed":true},
  {"operationId":"config.get","method":"GET","path":"/config","allowed":true},
  {"operationId":"config.providers","method":"GET","path":"/config/providers","allowed":true},
  {"operationId":"config.update","method":"PATCH","path":"/config","allowed":true},
  {"operationId":"event.subscribe","method":"GET","path":"/event","allowed":false,"reason":"SSE is exposed only through the bounded realtime gateway"},
  {"operationId":"experimental.console.get","method":"GET","path":"/experimental/console","allowed":false,"reason":"Experimental Console APIs are not supported"},
  {"operationId":"experimental.console.listOrgs","method":"GET","path":"/experimental/console/orgs","allowed":false,"reason":"Experimental Console APIs are not supported"},
  {"operationId":"experimental.console.switchOrg","method":"POST","path":"/experimental/console/switch","allowed":false,"reason":"Experimental Console APIs are not supported"},
  {"operationId":"experimental.resource.list","method":"GET","path":"/experimental/resource","allowed":true},
  {"operationId":"experimental.session.list","method":"GET","path":"/experimental/session","allowed":true},
  {"operationId":"experimental.workspace.adapter.list","method":"GET","path":"/experimental/workspace/adapter","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"experimental.workspace.create","method":"POST","path":"/experimental/workspace","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"experimental.workspace.list","method":"GET","path":"/experimental/workspace","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"experimental.workspace.remove","method":"DELETE","path":"/experimental/workspace/{id}","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"experimental.workspace.status","method":"GET","path":"/experimental/workspace/status","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"experimental.workspace.syncList","method":"POST","path":"/experimental/workspace/sync-list","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"experimental.workspace.warp","method":"POST","path":"/experimental/workspace/warp","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"file.list","method":"GET","path":"/file","allowed":true},
  {"operationId":"file.read","method":"GET","path":"/file/content","allowed":true},
  {"operationId":"file.status","method":"GET","path":"/file/status","allowed":true},
  {"operationId":"find.files","method":"GET","path":"/find/file","allowed":true},
  {"operationId":"find.symbols","method":"GET","path":"/find/symbol","allowed":true},
  {"operationId":"find.text","method":"GET","path":"/find","allowed":true},
  {"operationId":"formatter.status","method":"GET","path":"/formatter","allowed":true},
  {"operationId":"global.config.get","method":"GET","path":"/global/config","allowed":true},
  {"operationId":"global.config.update","method":"PATCH","path":"/global/config","allowed":false,"reason":"Unscoped global configuration mutation is not mobile-safe"},
  {"operationId":"global.dispose","method":"POST","path":"/global/dispose","allowed":false,"reason":"Rhythm desktop owns the engine lifecycle"},
  {"operationId":"global.event","method":"GET","path":"/global/event","allowed":false,"reason":"SSE is exposed only through the bounded realtime gateway"},
  {"operationId":"global.health","method":"GET","path":"/global/health","allowed":true},
  {"operationId":"global.upgrade","method":"POST","path":"/global/upgrade","allowed":false,"reason":"Rhythm desktop owns fork upgrades"},
  {"operationId":"instance.dispose","method":"POST","path":"/instance/dispose","allowed":false,"reason":"Rhythm desktop owns engine instance disposal"},
  {"operationId":"lsp.status","method":"GET","path":"/lsp","allowed":true},
  {"operationId":"mcp.add","method":"POST","path":"/mcp","allowed":true},
  {"operationId":"mcp.auth.authenticate","method":"POST","path":"/mcp/{name}/auth/authenticate","allowed":true},
  {"operationId":"mcp.auth.callback","method":"POST","path":"/mcp/{name}/auth/callback","allowed":true},
  {"operationId":"mcp.auth.remove","method":"DELETE","path":"/mcp/{name}/auth","allowed":true},
  {"operationId":"mcp.auth.start","method":"POST","path":"/mcp/{name}/auth","allowed":true},
  {"operationId":"mcp.connect","method":"POST","path":"/mcp/{name}/connect","allowed":true},
  {"operationId":"mcp.disconnect","method":"POST","path":"/mcp/{name}/disconnect","allowed":true},
  {"operationId":"mcp.status","method":"GET","path":"/mcp","allowed":true},
  {"operationId":"part.delete","method":"DELETE","path":"/session/{sessionID}/message/{messageID}/part/{partID}","allowed":true},
  {"operationId":"part.update","method":"PATCH","path":"/session/{sessionID}/message/{messageID}/part/{partID}","allowed":true},
  {"operationId":"path.get","method":"GET","path":"/path","allowed":true},
  {"operationId":"permission.list","method":"GET","path":"/permission","allowed":true},
  {"operationId":"permission.reply","method":"POST","path":"/permission/{requestID}/reply","allowed":true},
  {"operationId":"permission.respond","method":"POST","path":"/session/{sessionID}/permissions/{permissionID}","allowed":true},
  {"operationId":"project.current","method":"GET","path":"/project/current","allowed":true},
  {"operationId":"project.initGit","method":"POST","path":"/project/git/init","allowed":true},
  {"operationId":"project.list","method":"GET","path":"/project","allowed":true},
  {"operationId":"project.update","method":"PATCH","path":"/project/{projectID}","allowed":true},
  {"operationId":"provider.auth","method":"GET","path":"/provider/auth","allowed":true},
  {"operationId":"provider.list","method":"GET","path":"/provider","allowed":true},
  {"operationId":"provider.oauth.authorize","method":"POST","path":"/provider/{providerID}/oauth/authorize","allowed":true},
  {"operationId":"provider.oauth.callback","method":"POST","path":"/provider/{providerID}/oauth/callback","allowed":true},
  {"operationId":"pty.connect","method":"GET","path":"/pty/{ptyID}/connect","allowed":false,"reason":"PTY WebSocket traffic uses the authenticated realtime gateway"},
  {"operationId":"pty.connectToken","method":"POST","path":"/pty/{ptyID}/connect-token","allowed":true},
  {"operationId":"pty.create","method":"POST","path":"/pty","allowed":true},
  {"operationId":"pty.get","method":"GET","path":"/pty/{ptyID}","allowed":true},
  {"operationId":"pty.list","method":"GET","path":"/pty","allowed":true},
  {"operationId":"pty.remove","method":"DELETE","path":"/pty/{ptyID}","allowed":true},
  {"operationId":"pty.shells","method":"GET","path":"/pty/shells","allowed":true},
  {"operationId":"pty.update","method":"PUT","path":"/pty/{ptyID}","allowed":true},
  {"operationId":"question.list","method":"GET","path":"/question","allowed":true},
  {"operationId":"question.reject","method":"POST","path":"/question/{requestID}/reject","allowed":true},
  {"operationId":"question.reply","method":"POST","path":"/question/{requestID}/reply","allowed":true},
  {"operationId":"session.abort","method":"POST","path":"/session/{sessionID}/abort","allowed":true},
  {"operationId":"session.children","method":"GET","path":"/session/{sessionID}/children","allowed":true},
  {"operationId":"session.command","method":"POST","path":"/session/{sessionID}/command","allowed":true},
  {"operationId":"session.create","method":"POST","path":"/session","allowed":true},
  {"operationId":"session.delete","method":"DELETE","path":"/session/{sessionID}","allowed":true},
  {"operationId":"session.deleteMessage","method":"DELETE","path":"/session/{sessionID}/message/{messageID}","allowed":true},
  {"operationId":"session.diff","method":"GET","path":"/session/{sessionID}/diff","allowed":true},
  {"operationId":"session.fork","method":"POST","path":"/session/{sessionID}/fork","allowed":true},
  {"operationId":"session.get","method":"GET","path":"/session/{sessionID}","allowed":true},
  {"operationId":"session.init","method":"POST","path":"/session/{sessionID}/init","allowed":true},
  {"operationId":"session.list","method":"GET","path":"/session","allowed":true},
  {"operationId":"session.message","method":"GET","path":"/session/{sessionID}/message/{messageID}","allowed":true},
  {"operationId":"session.messages","method":"GET","path":"/session/{sessionID}/message","allowed":true},
  {"operationId":"session.prompt","method":"POST","path":"/session/{sessionID}/message","allowed":true},
  {"operationId":"session.prompt_async","method":"POST","path":"/session/{sessionID}/prompt_async","allowed":true},
  {"operationId":"session.revert","method":"POST","path":"/session/{sessionID}/revert","allowed":true},
  {"operationId":"session.share","method":"POST","path":"/session/{sessionID}/share","allowed":true},
  {"operationId":"session.shell","method":"POST","path":"/session/{sessionID}/shell","allowed":true},
  {"operationId":"session.status","method":"GET","path":"/session/status","allowed":true},
  {"operationId":"session.summarize","method":"POST","path":"/session/{sessionID}/summarize","allowed":true},
  {"operationId":"session.todo","method":"GET","path":"/session/{sessionID}/todo","allowed":true},
  {"operationId":"session.unrevert","method":"POST","path":"/session/{sessionID}/unrevert","allowed":true},
  {"operationId":"session.unshare","method":"DELETE","path":"/session/{sessionID}/share","allowed":true},
  {"operationId":"session.update","method":"PATCH","path":"/session/{sessionID}","allowed":true},
  {"operationId":"sync.history.list","method":"POST","path":"/sync/history","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"sync.replay","method":"POST","path":"/sync/replay","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"sync.start","method":"POST","path":"/sync/start","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"sync.steal","method":"POST","path":"/sync/steal","allowed":false,"reason":"Experimental workspace/sync APIs are not supported"},
  {"operationId":"tool.ids","method":"GET","path":"/experimental/tool/ids","allowed":true},
  {"operationId":"tool.list","method":"GET","path":"/experimental/tool","allowed":true},
  {"operationId":"tui.appendPrompt","method":"POST","path":"/tui/append-prompt","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.clearPrompt","method":"POST","path":"/tui/clear-prompt","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.control.next","method":"GET","path":"/tui/control/next","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.control.response","method":"POST","path":"/tui/control/response","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.executeCommand","method":"POST","path":"/tui/execute-command","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.openHelp","method":"POST","path":"/tui/open-help","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.openModels","method":"POST","path":"/tui/open-models","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.openSessions","method":"POST","path":"/tui/open-sessions","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.openThemes","method":"POST","path":"/tui/open-themes","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.publish","method":"POST","path":"/tui/publish","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.selectSession","method":"POST","path":"/tui/select-session","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.showToast","method":"POST","path":"/tui/show-toast","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"tui.submitPrompt","method":"POST","path":"/tui/submit-prompt","allowed":false,"reason":"The mobile client controls the headless server, not the TUI"},
  {"operationId":"v2.model.list","method":"GET","path":"/api/model","allowed":false,"reason":"The mobile contract is pinned to the supported v1 API"},
  {"operationId":"v2.provider.get","method":"GET","path":"/api/provider/{providerID}","allowed":false,"reason":"The mobile contract is pinned to the supported v1 API"},
  {"operationId":"v2.provider.list","method":"GET","path":"/api/provider","allowed":false,"reason":"The mobile contract is pinned to the supported v1 API"},
  {"operationId":"v2.session.compact","method":"POST","path":"/api/session/{sessionID}/compact","allowed":false,"reason":"The mobile contract is pinned to the supported v1 API"},
  {"operationId":"v2.session.context","method":"GET","path":"/api/session/{sessionID}/context","allowed":false,"reason":"The mobile contract is pinned to the supported v1 API"},
  {"operationId":"v2.session.list","method":"GET","path":"/api/session","allowed":false,"reason":"The mobile contract is pinned to the supported v1 API"},
  {"operationId":"v2.session.messages","method":"GET","path":"/api/session/{sessionID}/message","allowed":false,"reason":"The mobile contract is pinned to the supported v1 API"},
  {"operationId":"v2.session.prompt","method":"POST","path":"/api/session/{sessionID}/prompt","allowed":false,"reason":"The mobile contract is pinned to the supported v1 API"},
  {"operationId":"v2.session.wait","method":"POST","path":"/api/session/{sessionID}/wait","allowed":false,"reason":"The mobile contract is pinned to the supported v1 API"},
  {"operationId":"vcs.apply","method":"POST","path":"/vcs/apply","allowed":true},
  {"operationId":"vcs.diff","method":"GET","path":"/vcs/diff","allowed":true},
  {"operationId":"vcs.diff.raw","method":"GET","path":"/vcs/diff/raw","allowed":true},
  {"operationId":"vcs.get","method":"GET","path":"/vcs","allowed":true},
  {"operationId":"vcs.status","method":"GET","path":"/vcs/status","allowed":true},
  {"operationId":"worktree.create","method":"POST","path":"/experimental/worktree","allowed":true},
  {"operationId":"worktree.list","method":"GET","path":"/experimental/worktree","allowed":true},
  {"operationId":"worktree.remove","method":"DELETE","path":"/experimental/worktree","allowed":true},
  {"operationId":"worktree.reset","method":"POST","path":"/experimental/worktree/reset","allowed":true},
] as const satisfies readonly MobileOpenCodeOperation[];
