/** Synthetic only: ephemeral loopback listener, temporary vault, in-memory SQLite. */
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import Database from 'better-sqlite3';import express from 'express';
import {mkdtempSync,rmSync,readFileSync,writeFileSync,existsSync,readdirSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {request as httpRequest,type Server} from 'node:http';
import {runMigrations} from '../database/migrations';import {setDb} from '../database/db';
import {AgentMemoryRepository} from '../repositories/agent_memory_repository';import {MemoryIndexService} from '../services/memory_index_service';
import {createObservationIfAbsentInVault,MemoryCanonicalDeleteError} from '../services/memoryVaultWriteService';import {agentMemoryService} from '../services/agentMemoryService';
import {createAgentMemoryImportRouter} from '../routes/agent_memory_import_routes';import {receiptMatchesRequest,validateObservationImport} from '../controllers/agent_memory_import_controller';
import {DayflowIntegrationService} from '../integrations/dayflow/service';import {LocalDayflowMemoryClient} from '../integrations/dayflow/memory_client';import {MemoryLedger} from '../integrations/dayflow/ledger';
import {env} from '../config/env';import {localAgentSurfaceGuard} from '../middleware/local_agent_surface_guard';
import {EngraphHttpClient} from '../services/engraph_client';import {searchMemoryReferences} from '../services/memory_retrieval';
const runFile=promisify(execFile);let root:string,memoryDir:string,index:MemoryIndexService,repo:AgentMemoryRepository,db:Database.Database,previous:Database.Database|null;
const servers:Server[]=[],services:DayflowIntegrationService[]=[];
const request={schemaVersion:1,operationId:'operation_0123456789',id:'01ARZ3NDEKTSV4RRFFQ69G5FAV',content:'Synthetic HTTP observation',source:{id:'dayflow_fixture',resource:'dayflow://card/synthetic',revision:'a'.repeat(64),exportVersion:'fixture-v1',observedAt:'2026-10-01T08:00:00Z'},usageWindow:{from:'2026-10-01',to:'2026-10-01'}};
function canonicalPath(id:string){return join(memoryDir,'context',`import-${id.toLowerCase()}.md`);}
function files(){const folder=join(memoryDir,'context');return existsSync(folder)?readdirSync(folder).filter(name=>name.startsWith('import-')&&name.endsWith('.md')):[];}
async function mount(options:{guard?:boolean;remote?:boolean;executionLocal?:boolean;originGuardEnabled?:boolean;broadParserFirst?:boolean;indexTransport?:boolean}={}){
 const app=express();if(options.broadParserFirst)app.use(express.json());if(options.remote)app.use((req,_res,next)=>{Object.defineProperty(req.socket,'remoteAddress',{value:'192.0.2.123',configurable:true});next();});if(options.guard)app.use(localAgentSurfaceGuard);
 app.use('/agent-memory',createAgentMemoryImportRouter({executionLocal:options.executionLocal??true,originGuardEnabled:options.originGuardEnabled??true,importObservation:input=>createObservationIfAbsentInVault(input,{memoryDir,index})}));
 app.use(express.json());
 app.delete('/agent-memory/:id',async(req,res,next)=>{try{res.status(await agentMemoryService.forget(req.params.id,{memoryDir,index})?204:404).end();}catch(error){next(error);}});
 if(options.indexTransport)app.post('/_synthetic_index/remove',async(req,res,next)=>{try{res.json({removed:await index.removeNote(req.body.sourceId)});}catch(error){next(error);}});
 const server=await new Promise<Server>((resolve,reject)=>{const listener=app.listen(0,'127.0.0.1',()=>resolve(listener));listener.once('error',reject);});servers.push(server);return `http://127.0.0.1:${(server.address() as {port:number}).port}`;
}
function post(base:string,body:unknown=request,headers:Record<string,string>={}){return new Promise<Response>((resolve,reject)=>{const outgoing=httpRequest(`${base}/agent-memory/import-observation`,{method:'POST',headers:{'content-type':'application/json',...headers}},incoming=>{let raw='';incoming.setEncoding('utf8');incoming.on('data',chunk=>raw+=chunk);incoming.on('end',()=>resolve(new Response(raw,{status:incoming.statusCode})));});outgoing.on('error',reject);outgoing.end(JSON.stringify(body));});}
function service(base:string,records=[{id:'one',start:'2026-10-01T08:00:00Z',summary:'Synthetic HTTP marker'}]){const result=new DayflowIntegrationService({source:{read:async()=>({contractVersion:'fixture-v1',sourceInstanceId:'synthetic',records})},memoryClient:new LocalDayflowMemoryClient(base),ledger:new MemoryLedger(join(root,'ledger.json'))});services.push(result);return result;}
async function child(base:string,mode='normal'){const {stdout}=await runFile('/Users/ajhochhalter/.local/bin/node',['--require',resolve('node_modules/tsx/dist/cjs/index.cjs'),resolve('recovery-child.cjs'),root,base,mode],{cwd:process.cwd(),timeout:14000,maxBuffer:16384});return JSON.parse(stdout.trim());}
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),'dayflow-sol-http-'));memoryDir=join(root,'memory');db=new Database(':memory:');db.pragma('foreign_keys = ON');runMigrations(db);previous=setDb(db);repo=new AgentMemoryRepository();index=new MemoryIndexService(repo);});
afterEach(async()=>{vi.restoreAllMocks();vi.unstubAllGlobals();services.splice(0).forEach(s=>s.dispose());await Promise.all(servers.splice(0).map(server=>new Promise<void>(resolve=>server.close(()=>resolve()))));setDb(previous);db.close();rmSync(root,{recursive:true,force:true});});
describe('native observation factory over synthetic HTTP',()=>{
 it('creates two same-heading observations with distinct IDs through adapter/client/route/core',async()=>{const base=await mount(),adapter=service(base,[{id:'one',start:'2026-10-01T08:00:00Z',summary:'Same synthetic heading'},{id:'two',start:'2026-10-01T09:00:00Z',summary:'Same synthetic heading'}]);await adapter.updateConfig({enabled:true,timezone:'UTC'});const preview=await adapter.preview(),result=await adapter.commit(preview.token,preview.candidates.map(c=>c.candidateId));expect(result.failed).toEqual([]);expect(result.imported).toHaveLength(2);expect(files()).toHaveLength(2);expect(await repo.searchAsync('synthetic heading',undefined,10)).toHaveLength(2);});
 it('replays canonical bytes and repairs a missing index through HTTP',async()=>{const base=await mount(),first=await post(base);expect(first.status).toBe(201);const receipt=await first.json() as {path:string;canonicalContentHash:string},before=readFileSync(canonicalPath(request.id),'utf8');await index.removeNote(receipt.path);expect(await repo.listAsync(undefined,undefined,20)).toHaveLength(0);const replay=await post(base);expect(replay.status).toBe(200);expect(await replay.json()).toMatchObject({disposition:'already_present',canonicalContentHash:receipt.canonicalContentHash});expect(readFileSync(canonicalPath(request.id),'utf8')).toBe(before);expect(await repo.listAsync(undefined,undefined,20)).toHaveLength(1);});
 it('replays a receipt with explicit observedEnd',async()=>{const base=await mount(),body={...request,source:{...request.source,observedEnd:'2026-10-01T09:00:00Z'}};expect((await post(base,body)).status).toBe(201);expect((await post(base,body)).status).toBe(200);});
 it('accepts observation body within the declared 8000-character route bound',async()=>{expect((await post(await mount(),{...request,content:'Synthetic activity summary '.repeat(24)})).status).toBe(201);});
 it('rejects replay after a human edit without changing bytes',async()=>{const base=await mount();expect((await post(base)).status).toBe(201);const filename=canonicalPath(request.id),edited=readFileSync(filename,'utf8').replace(request.content,'Human synthetic correction');writeFileSync(filename,edited);const replay=await post(base);expect(replay.status).toBe(409);expect((await replay.json() as {code:string}).code).toBe('OBSERVATION_IMPORT_CONFLICT');expect(readFileSync(filename,'utf8')).toBe(edited);});
 it('reconciles a lost response in a fresh process and clears the pending journal',async()=>{const base=await mount(),first=await child(base,'lost');expect(first.result.failed).toHaveLength(1);expect(files()).toHaveLength(1);const filename=join(memoryDir,'context',files()[0]),before=readFileSync(filename,'utf8'),second=await child(base);expect(second.pid).not.toBe(first.pid);expect(second.result.conflicts).toEqual([]);expect(second.result.failed).toEqual([]);expect(second.result.imported.length+second.result.skipped.length).toBe(1);const ledger=JSON.parse(readFileSync(join(root,'ledger.json'),'utf8'));expect(Object.values(ledger.entries).every((e:any)=>!e.pendingCreateAt)).toBe(true);expect(readFileSync(filename,'utf8')).toBe(before);});
 it('preserves human edits when recovering an uncertain commit in a fresh process',async()=>{const base=await mount();await child(base,'lost');const filename=join(memoryDir,'context',files()[0]),edited=readFileSync(filename,'utf8').replace('Synthetic process recovery marker','Human recovery correction');writeFileSync(filename,edited);const next=await child(base);expect(readFileSync(filename,'utf8')).toBe(edited);expect(next.result.imported).toEqual([]);expect(next.result.conflicts).toHaveLength(1);});
 it('reports unfinished creates separately from successfully imported observations',async()=>{const result=await child(await mount(),'lost');expect(result.status).toMatchObject({importedCount:0,pendingCreateCount:1,pendingDeleteCount:0});});
 it('reports unfinished deletes separately from imported observations',async()=>{const base=await mount(),adapter=service(base);await adapter.updateConfig({enabled:true,timezone:'UTC'});const preview=await adapter.preview(),result=await adapter.commit(preview.token,[preview.candidates[0].candidateId]);vi.stubGlobal('fetch',vi.fn(async()=>new Response('',{status:503})));await expect(adapter.forget(result.imported[0])).rejects.toThrow();expect(adapter.status()).toMatchObject({importedCount:0,pendingCreateCount:0,pendingDeleteCount:1});});
 it('deletes canonical truth despite a missing index and excludes it after index rebuild',async()=>{const base=await mount(),adapter=service(base);await adapter.updateConfig({enabled:true,timezone:'UTC'});const preview=await adapter.preview(),committed=await adapter.commit(preview.token,[preview.candidates[0].candidateId]);expect(committed.imported).toHaveLength(1);const id=committed.imported[0],row=await agentMemoryService.get(id,{memoryDir,index});expect(row).toBeTruthy();await index.removeNote(row!.sourceId!);await adapter.forget(id);await index.rebuildIndexFromVault(root);expect({canonicalExists:existsSync(canonicalPath(id)),recalled:(await repo.searchAsync('Synthetic HTTP marker',undefined,10)).length}).toEqual({canonicalExists:false,recalled:0});});
 it('keeps nested-vault Dayflow imports joinable to native references, then rejects a stale native hit after forget',async()=>{
  const previous={vault:process.env.MEMORY_VAULT_PATH,subdir:process.env.MEMORY_VAULT_SUBDIR,engraph:process.env.ENGRAPH_MEMORY_VAULT_ROOT};
  Object.assign(process.env,{MEMORY_VAULT_PATH:root,MEMORY_VAULT_SUBDIR:'memory',ENGRAPH_MEMORY_VAULT_ROOT:memoryDir});
  try {
   const base=await mount(),adapter=service(base,[
    {id:'target',start:'2026-10-01T08:00:00Z',summary:'Nested Dayflow target evidence'},
    {id:'control',start:'2026-10-01T09:00:00Z',summary:'Nested Dayflow unaffected control'},
   ]);
   await adapter.updateConfig({enabled:true,timezone:'UTC'});
   const preview=await adapter.preview();
   const committed=await adapter.commit(preview.token,preview.candidates.map(candidate=>candidate.candidateId));
   expect(committed.failed).toEqual([]);
   const targetMemoryId=committed.imported[0];
   const rows=await repo.listAsync(undefined,undefined,20);
   const target=rows.find(row=>row.content.includes('target evidence'));
   const control=rows.find(row=>row.content.includes('unaffected control'));
   expect(target?.sourceId).toMatch(/^memory\/context\/import-/);
   expect(control?.sourceId).toMatch(/^memory\/context\/import-/);
   const stale=[
    {file_path:target!.sourceId!.slice('memory/'.length),snippet:'Nested Dayflow target evidence',score:99},
    {file_path:control!.sourceId!.slice('memory/'.length),snippet:'Nested Dayflow unaffected control',score:98},
   ];
   const peer=express();
   peer.post('/api/search',(_req,res)=>res.json({results:stale}));
   const nativeBase=await new Promise<string>((resolve,reject)=>{
    const listener=peer.listen(0,'127.0.0.1',()=>{servers.push(listener);resolve(`http://127.0.0.1:${(listener.address() as {port:number}).port}`);});
    listener.once('error',reject);
   });
   const native=new EngraphHttpClient(nativeBase);
   const positive=await searchMemoryReferences('nested Dayflow',undefined,{repo,engraph:native});
   expect(positive.references.map(reference=>reference.id)).toEqual([target!.id,control!.id]);
   await adapter.forget(targetMemoryId);
   expect(existsSync(join(root,target!.sourceId!))).toBe(false);
   const negative=await searchMemoryReferences('nested Dayflow',undefined,{repo,engraph:native});
   expect(negative.references.map(reference=>reference.id)).toEqual([control!.id]);
  } finally {
   if(previous.vault===undefined)delete process.env.MEMORY_VAULT_PATH;else process.env.MEMORY_VAULT_PATH=previous.vault;
   if(previous.subdir===undefined)delete process.env.MEMORY_VAULT_SUBDIR;else process.env.MEMORY_VAULT_SUBDIR=previous.subdir;
   if(previous.engraph===undefined)delete process.env.ENGRAPH_MEMORY_VAULT_ROOT;else process.env.ENGRAPH_MEMORY_VAULT_ROOT=previous.engraph;
  }
 });
});
describe('factory request boundaries',()=>{
 it('rejects foreign Origin and cross-site requests',async()=>{const base=await mount();expect((await post(base,request,{Origin:'https://attacker.invalid'})).status).toBe(403);expect((await post(base,request,{'sec-fetch-site':'cross-site'})).status).toBe(403);expect(files()).toHaveLength(0);});
 it('rejects synthetic non-loopback sockets',async()=>{expect((await post(await mount({remote:true}))).status).toBe(403);expect(files()).toHaveLength(0);});
 it('rejects disabled local execution or origin guard',async()=>{expect((await post(await mount({executionLocal:false}))).status).toBe(403);expect((await post(await mount({originGuardEnabled:false}))).status).toBe(403);});
 it('rejects untrusted Host without an unspecified outer mount',async()=>{expect((await post(await mount(),request,{Host:'attacker.invalid'})).status).toBe(403);expect(files()).toHaveLength(0);});
 it('rejects localhost Origin absent from renderer allowlist',async()=>{expect((await post(await mount(),request,{Origin:'http://localhost:61234'})).status).toBe(403);expect(files()).toHaveLength(0);});
 it('existing outer local guard supplies Host and exact Origin defenses',async()=>{const local=env.agentLocal,guard=env.agentOriginGuardEnabled;env.agentLocal=true;env.agentOriginGuardEnabled=true;try{const base=await mount({guard:true});expect((await post(base,request,{Host:'attacker.invalid'})).status).toBe(403);expect((await post(base,request,{Origin:'http://localhost:61234'})).status).toBe(403);expect((await post(base)).status).toBe(201);}finally{env.agentLocal=local;env.agentOriginGuardEnabled=guard;}});
 it('accepts the explicitly configured Electron renderer Origin',async()=>{const local=env.agentLocal,guard=env.agentOriginGuardEnabled,origins=env.localRendererOrigins;env.agentLocal=true;env.agentOriginGuardEnabled=true;env.localRendererOrigins=['rhythm://app'];try{expect((await post(await mount({guard:true}),request,{Origin:'rhythm://app'})).status).toBe(201);}finally{env.agentLocal=local;env.agentOriginGuardEnabled=guard;env.localRendererOrigins=origins;}});
 it('rejects a resource making the DTO larger than 16 KiB without mutation',async()=>{const oversized={...request,source:{...request.source,resource:'dayflow://card/'+ 'x'.repeat(20000)}};expect((await post(await mount(),oversized)).status).toBeGreaterThanOrEqual(400);expect(files()).toHaveLength(0);});
 it('rejects impossible observation timestamp before native writer',()=>{expect(()=>validateObservationImport({...request,source:{...request.source,observedAt:'2026-02-30T08:00:00Z'}})).toThrow();});
});
describe('strict correlated receipt',()=>{
 const input={operationId:request.operationId,id:request.id,content:request.content,sourceId:'synthetic',observation:{sourceInstanceId:'synthetic',recordId:'one',summary:request.content,observedStart:request.source.observedAt,revisionHash:request.source.revision,dayKey:request.usageWindow.from,exportVersion:'fixture-v1' as const}};
 const receipt={schemaVersion:1,operationId:request.operationId,id:request.id,path:`memory/context/import-${request.id.toLowerCase()}.md`,disposition:'created',canonicalContentHash:'b'.repeat(64),sourceRevision:request.source.revision,exportVersion:'fixture-v1'};
 it.each(['operationId','id','sourceRevision','exportVersion','disposition','canonicalContentHash'])('rejects malformed %s',async field=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({...receipt,[field]:'invalid'}),{status:201})));await expect(new LocalDayflowMemoryClient().createOnly(input)).rejects.toThrow();});
 it.each(['../outside.md','/absolute.md',undefined])('rejects unsafe/missing receipt path %s',async path=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({...receipt,path}),{status:201})));await expect(new LocalDayflowMemoryClient().createOnly(input)).rejects.toThrow();});
 it('receiptMatchesRequest rejects an otherwise valid absolute path',()=>{expect(receiptMatchesRequest({...receipt,path:'/absolute.md'} as any,request as any)).toBe(false);});
 it('receiptMatchesRequest rejects arbitrary disposition and path traversal',()=>{expect(receiptMatchesRequest({...receipt,disposition:'anything',path:'../outside.md'} as any,request as any)).toBe(false);});
});

describe('supplemental supported-layout and raw request boundaries',()=>{
 it('accepts real canonical receipts in the supported empty-subdirectory vault layout',async()=>{const subdirectory=process.env.MEMORY_VAULT_SUBDIR;process.env.MEMORY_VAULT_SUBDIR='';memoryDir=root;try{const adapter=service(await mount());await adapter.updateConfig({enabled:true,timezone:'UTC'});const preview=await adapter.preview(),result=await adapter.commit(preview.token,[preview.candidates[0].candidateId]);expect(result.failed).toEqual([]);expect(result.imported).toHaveLength(1);expect(files()).toHaveLength(1);}finally{if(subdirectory===undefined)delete process.env.MEMORY_VAULT_SUBDIR;else process.env.MEMORY_VAULT_SUBDIR=subdirectory;}});
 it('enforces 16 KiB raw JSON limit before parsing even with valid bounded fields',async()=>{const base=await mount();const status=await new Promise<number>((resolve,reject)=>{const outgoing=httpRequest(`${base}/agent-memory/import-observation`,{method:'POST',headers:{'content-type':'application/json'}},incoming=>{incoming.resume();incoming.on('end',()=>resolve(incoming.statusCode!));});outgoing.on('error',reject);outgoing.end(' '.repeat(20000)+JSON.stringify(request));});expect(status).toBeGreaterThanOrEqual(400);expect(files()).toHaveLength(0);});
 it('rejects no-Origin same-site fetch consistently with the shared local guard',async()=>{expect((await post(await mount(),request,{'sec-fetch-site':'same-site'})).status).toBe(403);expect(files()).toHaveLength(0);});
});


describe('streamed body byte-bound qualification',()=>{
 async function rawPost(base:string,raw:string,chunked:boolean){return new Promise<{status:number;body:any}>((resolve,reject)=>{const headers:Record<string,string>={'content-type':'application/json'};if(chunked)headers['transfer-encoding']='chunked';else headers['content-length']=String(Buffer.byteLength(raw));const outgoing=httpRequest(`${base}/agent-memory/import-observation`,{method:'POST',headers},incoming=>{let text='';incoming.setEncoding('utf8');incoming.on('data',chunk=>text+=chunk);incoming.on('end',()=>{let body:any;try{body=JSON.parse(text);}catch{body=text;}resolve({status:incoming.statusCode!,body});});});outgoing.on('error',reject);if(chunked){outgoing.flushHeaders();for(let offset=0;offset<raw.length;offset+=1000)outgoing.write(raw.slice(offset,offset+1000));outgoing.end();}else outgoing.end(raw);});}
 it.each([false,true])('rejects actual oversized body with chunked=%s, before canonical mutation',async chunked=>{const raw=' '.repeat(20000)+JSON.stringify(request),result=await rawPost(await mount(),raw,chunked);expect(result).toEqual({status:413,body:{code:'INVALID_OBSERVATION_IMPORT'}});expect(files()).toHaveLength(0);expect(await repo.listAsync(undefined,undefined,20)).toHaveLength(0);});
 it('accepts valid chunked JSON without Content-Length',async()=>{expect((await rawPost(await mount(),JSON.stringify(request),true)).status).toBe(201);expect(files()).toHaveLength(1);});
 it('rejects UTF-8 byte overflow despite fewer than 8000 content characters',async()=>{const content='😀'.repeat(3990),raw=JSON.stringify({...request,content,source:{...request.source,resource:'dayflow://card/'+'x'.repeat(256)}});expect(content.length).toBeLessThan(8000);expect(Buffer.byteLength(raw)).toBeGreaterThan(16384);expect((await rawPost(await mount(),raw,true)).status).toBe(413);expect(files()).toHaveLength(0);});
 it('returns a bounded safe 400 JSON response for malformed streamed JSON',async()=>{const result=await rawPost(await mount(),'{\"schemaVersion\":1,\"content\":\"synthetic-must-not-echo\",',true);expect(result).toEqual({status:400,body:{code:'INVALID_OBSERVATION_IMPORT'}});expect(files()).toHaveLength(0);});
 it('demonstrates why a broader upstream parser cannot precede the import factory',async()=>{const raw=' '.repeat(20000)+JSON.stringify(request),result=await rawPost(await mount({broadParserFirst:true}),raw,true);expect(result.status).toBe(201);expect(files()).toHaveLength(1);});
});


describe('fresh-process deletion cleanup recovery',()=>{
 it('cannot finalize a deletion retry while an orphaned derived row remains recallable',async()=>{const base=await mount(),created=await child(base);expect(created.result.imported).toHaveLength(1);const id=created.result.imported[0];vi.spyOn(MemoryIndexService.prototype,'removeNote').mockRejectedValueOnce(new Error('Synthetic derived cleanup interruption'));const first=await child(base,'forget');expect(first.result.deleteError).toBe(true);expect(first.status.pendingDeleteCount).toBe(1);expect(existsSync(canonicalPath(id))).toBe(false);expect(await repo.searchAsync('Synthetic process recovery marker',undefined,10)).toHaveLength(1);const second=await child(base,'forget');expect(second.pid).not.toBe(first.pid);const recalled=(await repo.searchAsync('Synthetic process recovery marker',undefined,10)).length;expect({terminalForget:Boolean(second.result.forgotten),recallRemains:recalled>0}).not.toEqual({terminalForget:true,recallRemains:true});if(second.result.forgotten){expect(recalled).toBe(0);expect(second.status.pendingDeleteCount).toBe(0);}else expect(second.status.pendingDeleteCount).toBe(1);});
});


describe('durable deletion record validation and pre-unlink safeguards',()=>{
 const recoveryName='.rhythm-canonical-delete-recovery.json';
 async function seeded(){const first=await post(await mount());expect(first.status).toBe(201);return first.json() as Promise<{path:string}>;}
 it.each([['version',{version:2,entries:{}}],['array',{version:1,entries:[]}],['blank ID',{version:1,entries:{'':'memory/context/valid.md'}}],['long ID',{version:1,entries:{['x'.repeat(257)]:'memory/context/valid.md'}}],['absolute path',{version:1,entries:{[request.id]:'/tmp/escaped.md'}}],['traversal',{version:1,entries:{[request.id]:'memory/../../escaped.md'}}]])('fails closed on invalid recovery %s without canonical/index mutation',async(_name,record)=>{await seeded();const raw=JSON.stringify(record),filename=join(memoryDir,recoveryName);writeFileSync(filename,raw);await expect(agentMemoryService.forget(request.id,{memoryDir,index})).rejects.toMatchObject({code:'MEMORY_DELETE_UNAVAILABLE'});expect(existsSync(canonicalPath(request.id))).toBe(true);expect(await repo.searchAsync('Synthetic HTTP observation',undefined,10)).toHaveLength(1);expect(readFileSync(filename,'utf8')).toBe(raw);});
 it('rejects malformed recovery JSON before canonical deletion',async()=>{await seeded();const filename=join(memoryDir,recoveryName);writeFileSync(filename,'{invalid synthetic JSON');await expect(agentMemoryService.forget(request.id,{memoryDir,index})).rejects.toMatchObject({code:'MEMORY_DELETE_UNAVAILABLE'});expect(existsSync(canonicalPath(request.id))).toBe(true);expect(await repo.searchAsync('Synthetic HTTP observation',undefined,10)).toHaveLength(1);});
 it('rejects a symlinked recovery record without touching its target',async()=>{await seeded();const target=join(root,'synthetic-recovery-target.json'),raw=JSON.stringify({version:1,entries:{}});writeFileSync(target,raw);symlinkSync(target,join(memoryDir,recoveryName));await expect(agentMemoryService.forget(request.id,{memoryDir,index})).rejects.toMatchObject({code:'MEMORY_DELETE_UNAVAILABLE'});expect(existsSync(canonicalPath(request.id))).toBe(true);expect(readFileSync(target,'utf8')).toBe(raw);});
 it('never finalizes recovery after a human-edit race prevented the original unlink',async()=>{const receipt=await seeded(),filename=canonicalPath(request.id),before=readFileSync(filename,'utf8'),edited=before.replace(request.content,'Human synthetic deletion-race correction');await index.removeNote(receipt.path);await expect(agentMemoryService.forget(request.id,{memoryDir,index,beforeNoteDeletion:async()=>writeFileSync(filename,edited)})).rejects.toBeInstanceOf(MemoryCanonicalDeleteError);expect(readFileSync(filename,'utf8')).toBe(edited);const evidencePath=join(memoryDir,recoveryName),evidence=readFileSync(evidencePath,'utf8');await expect(agentMemoryService.forget(request.id,{memoryDir,index})).rejects.toMatchObject({code:'MEMORY_DELETE_CONFLICT'});expect(readFileSync(filename,'utf8')).toBe(edited);expect(readFileSync(evidencePath,'utf8')).toBe(evidence);await index.rebuildIndexFromVault(root);expect(await repo.searchAsync('Human synthetic deletion-race correction',undefined,10)).toHaveLength(1);});
 it('cannot finalize a fresh-process pre-unlink recovery record while canonical truth survives',async()=>{const base=await mount(),created=await child(base),id=created.result.imported[0],row=await agentMemoryService.get(id,{memoryDir,index});expect(row).toBeTruthy();writeFileSync(join(memoryDir,recoveryName),JSON.stringify({version:1,entries:{[id]:row!.sourceId}}));await index.removeNote(row!.sourceId!);const evidencePath=join(memoryDir,recoveryName),evidence=readFileSync(evidencePath,'utf8'),canonical=readFileSync(canonicalPath(id),'utf8');const retried=await child(base,'forget');expect(retried.result).toEqual({deleteError:true});expect(retried.status.pendingDeleteCount).toBe(1);expect(readFileSync(evidencePath,'utf8')).toBe(evidence);expect(readFileSync(canonicalPath(id),'utf8')).toBe(canonical);const ledger=JSON.parse(readFileSync(join(root,'ledger.json'),'utf8'));expect(Object.values(ledger.entries).every((entry:any)=>Boolean(entry.pendingDeleteAt)&&!entry.tombstonedAt)).toBe(true);await index.rebuildIndexFromVault(root);expect(await repo.searchAsync('Synthetic process recovery marker',undefined,10)).toHaveLength(1);});
});


describe('actual native worker process restart after canonical unlink',()=>{
 it('recovers from durable evidence in a newly imported native writer process before confirming recall absence',async()=>{const base=await mount({indexTransport:true});expect((await post(base)).status).toBe(201);async function nativeWorker(mode:string){const {stdout}=await runFile('/Users/ajhochhalter/.local/bin/node',['--require',resolve('node_modules/tsx/dist/cjs/index.cjs'),resolve('native-delete-child.cjs'),root,base,request.id,mode],{cwd:process.cwd(),timeout:14000,maxBuffer:32768});return JSON.parse(stdout.trim().split('\n').at(-1)!);}const failed=await nativeWorker('fail');expect(failed).toMatchObject({success:false,code:'MEMORY_DELETE_UNAVAILABLE'});expect(existsSync(canonicalPath(request.id))).toBe(false);expect(await repo.searchAsync('Synthetic HTTP observation',undefined,10)).toHaveLength(1);const record=join(memoryDir,'.rhythm-canonical-delete-recovery.json');expect(JSON.parse(readFileSync(record,'utf8')).entries[request.id]).toBeTruthy();const resumed=await nativeWorker('resume');expect(resumed.pid).not.toBe(failed.pid);expect(resumed.success).toBe(true);expect(await repo.searchAsync('Synthetic HTTP observation',undefined,10)).toHaveLength(0);expect(existsSync(canonicalPath(request.id))).toBe(false);expect(JSON.parse(readFileSync(record,'utf8')).entries[request.id]).toBeUndefined();});
});

describe('indexed pre-unlink recovery must share fail-closed canonical-ID semantics',()=>{
 it('does not erase a surviving human edit on fresh-process retry merely because its derived row still exists',async()=>{const base=await mount(),created=await child(base),id=created.result.imported[0],filename=canonicalPath(id),edited=readFileSync(filename,'utf8').replace('Synthetic process recovery marker','Human indexed deletion-race correction');await expect(agentMemoryService.forget(id,{memoryDir,index,beforeNoteDeletion:async()=>writeFileSync(filename,edited)})).rejects.toBeInstanceOf(MemoryCanonicalDeleteError);expect(readFileSync(filename,'utf8')).toBe(edited);expect(await repo.searchAsync('Synthetic process recovery marker',undefined,10)).toHaveLength(1);const evidencePath=join(memoryDir,'.rhythm-canonical-delete-recovery.json'),evidence=readFileSync(evidencePath,'utf8');const retry=await child(base,'forget'),outcome={reply:retry.result,canonicalExists:existsSync(filename),pendingDeleteCount:retry.status.pendingDeleteCount,recoveryEntry:JSON.parse(readFileSync(evidencePath,'utf8')).entries[id]??null};expect(outcome).toEqual({reply:{deleteError:true},canonicalExists:true,pendingDeleteCount:1,recoveryEntry:JSON.parse(evidence).entries[id]});expect(readFileSync(filename,'utf8')).toBe(edited);expect(readFileSync(evidencePath,'utf8')).toBe(evidence);});
});
