import { inflateSync } from 'node:zlib';
/** Original Free addendum positive cases #3/#4/#7/#8 via the authenticated product API and fake loopback provider. */
import { createHash } from 'node:crypto';
import { spawn, type ChildProcess } from 'node:child_process';
import { existsSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import defaults from '../services/decision/router_grid.default.json';
const LIVE=process.env.RHYTHM_LIVE_E2E==='1'&&process.env.RHYTHM_LIVE_FREE_ORIGINAL_CASES==='1';
const ROOT=['/private/tmp/sdmr-grid-sandbox','/private/tmp/sdmr-grid-sandbox-r6u','/private/tmp/sdmr-grid-sandbox-r14c'].find(r=>r===process.env.RHYTHM_SANDBOX_DIR)??'/private/tmp/sdmr-grid-sandbox';
const APP=`${ROOT}/home/Library/Application Support/Rhythm`,OVERRIDE=`${APP}/router-grid.json`,OPERATOR=`${APP}/router-free-extraction.json`;
const BASE='http://127.0.0.1:4398',GRID='http://127.0.0.1:7482',PROVIDER='http://127.0.0.1:7481';
const auth={authorization:'Bearer e02-synthetic-session-not-a-secret','content-type':'application/json'};
const SMALL='openrouter/thinkingmachines/inkling-small:free',INKLING='openrouter/thinkingmachines/inkling:free',ULTRA='openrouter/nvidia/nemotron-3-ultra-550b-a55b:free',NANO='openrouter/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free';
const OLD_INVALID_PNG_BASE64='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl9sAAAAASUVORK5CYII=';
// Truthful 2x2, 8-bit truecolor RGB PNG: every decoded pixel is #0000ff. Generated and archived in
// /private/tmp/sdmr-grid-sandbox/tmp/r19-image-fixture/fixture-custody.json.
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAD0lEQVR42mNgYPgPRmAKABf2A/3HkIu0AAAAAElFTkSuQmCC','base64');
const CRC_TABLE=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0});
function crc32(data:Buffer){let c=0xffffffff;for(const b of data)c=CRC_TABLE[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function inspectPng(data:Buffer):{valid:boolean;errors:string[];width?:number;height?:number;colorType?:number;raw?:Buffer}{
 const errors:string[]=[];if(!data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return{valid:false,errors:['signature']};
 let p=8,ihdr:Buffer|undefined;const idat:Buffer[]=[];while(p<data.length){if(p+12>data.length){errors.push('truncated_chunk');break}const n=data.readUInt32BE(p),type=data.subarray(p+4,p+8),body=data.subarray(p+8,p+8+n);if(p+12+n>data.length){errors.push('truncated_body');break}const expected=data.readUInt32BE(p+8+n),actual=crc32(Buffer.concat([type,body]));if(expected!==actual)errors.push(`crc:${type.toString()}`);if(type.toString()==='IHDR')ihdr=body;if(type.toString()==='IDAT')idat.push(body);p+=12+n}
 if(!ihdr||ihdr.length!==13)return{valid:false,errors:[...errors,'ihdr']};let raw:Buffer|undefined;try{raw=inflateSync(Buffer.concat(idat))}catch{errors.push('inflate')}
 return{valid:errors.length===0,errors,width:ihdr.readUInt32BE(0),height:ihdr.readUInt32BE(4),colorType:ihdr[9],raw};}

const coding={id:'coding_t2',kind:'coding',label:'Synthetic public coding task',prompt:'Implement sumNumbers(values), returning the sum of a public array of finite numbers.',classification:{tier:2,category:'coding',canQueue:false},exportName:'sumNumbers',tests:[{args:[[1,2,3]],expected:6},{args:[[-4,4,10]],expected:10},{args:[[]],expected:0}]};
const image={id:'blue_card',label:'Synthetic public blue card',mime:'image/png',base64:png.toString('base64'),sha256:createHash('sha256').update(png).digest('hex')};
const design={id:'design_image',kind:'image_design',label:'Synthetic public image design task',prompt:'Return the independently specified layout fields for this public image.',imageId:image.id,classification:{tier:3,category:'design',canQueue:false},helperRequiredTerms:['blue','square'],expected:{layout:'single square',primaryColor:'blue',headline:'none'}};
const knowledge='SDMRX:knowledge_t1 Public fixture item costs $42.';
const fields=[{name:'item',type:'string',required:true},{name:'price',type:'number',required:true}];
const span=(src:string,s:string)=>({start:src.indexOf(s),end:src.indexOf(s)+s.length});
let provider:ChildProcess|undefined; const router=JSON.parse(readFileSync(`${APP}/decision-router.json`,'utf8'));
const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const api=async(path:string,body:unknown)=>{const r=await fetch(BASE+path,{method:'POST',headers:auth,body:JSON.stringify(body),signal:AbortSignal.timeout(60_000)});expect(r.status).toBe(200);return r.json() as Promise<Record<string,unknown>>};
const register=(tag:string,spec:unknown)=>fetch(`${PROVIDER}/_sdmr/reply/${tag}`,{method:'POST',body:JSON.stringify(spec)});
const requests=async(tag:string)=>((await(await fetch(`${PROVIDER}/_sdmr/requests`)).json()) as Array<{lastUserText:string;body:{model:string;reasoning?:{effort?:string};messages:unknown[]}}>).filter(r=>r.lastUserText.includes(`SDMRX:${tag}`));
const usage=(used:number)=>fetch(`${GRID}/_grid/control`,{method:'POST',headers:{authorization:''},body:JSON.stringify({unknown:false,fail429:[],malformed:false,usage:Object.fromEntries(['openai-a','openai-b','anthropic-a','anthropic-b'].map(a=>[a,{five:used,week:used}]))})});
(LIVE?describe:describe.skip)('original Free positive cases #3/#4/#7/#8',()=>{
 it('image fixture integrity: old bytes fail CRC/inflate; replacement is decoded 2x2 RGB solid blue',()=>{const old=inspectPng(Buffer.from(OLD_INVALID_PNG_BASE64,'base64')),good=inspectPng(png);expect(old.valid).toBe(false);expect(old.errors).toEqual(expect.arrayContaining(['crc:IDAT','inflate']));expect(good).toMatchObject({valid:true,errors:[],width:2,height:2,colorType:2});expect(good.raw).toEqual(Buffer.from([0,0,0,255,0,0,255,0,0,0,255,0,0,255]));expect(image.sha256).toBe('2d8cfdb8c8da042145179a5c216b5ca859291e03166b6384b716bb0648635abf')});
 beforeAll(async()=>{expect(existsSync(OVERRIDE)||existsSync(OPERATOR)).toBe(false);provider=spawn(process.execPath,[join(__dirname,'fixtures/scripted_openai_provider_sdmr.mjs')],{env:{...process.env,RHYTHM_SDMR_PROVIDER_PORT:'7481'},stdio:'ignore'});for(let i=0;i<50;i++){if(await fetch(`${PROVIDER}/health`).then(r=>r.ok,()=>false))break;await pause(200)}
  writeFileSync(OVERRIDE,JSON.stringify({free_mode:{...defaults.free_mode,enabled:true}}),{flag:'wx',mode:0o600});
  writeFileSync(OPERATOR,JSON.stringify({version:1,endpoint:{baseUrl:`${PROVIDER}/v1`,authProvider:'sdmr'},qualifiedFreeModels:[SMALL,INKLING,ULTRA,NANO],publicSources:[{id:'knowledge_t1',label:'Synthetic public price list',text:knowledge,classification:{tier:1,category:'knowledge',canQueue:false}}],publicTasks:[coding,design],publicImages:[image]}),{flag:'wx',mode:0o600});
  await fetch(`${BASE}/agent-free/extraction/opt-in`,{method:'PUT',headers:auth,body:'{"enabled":true}'});await usage(100);await fetch(`${BASE}/agents/usage-budget?force=true`,{headers:auth});
 },60000);
 afterAll(async()=>{await fetch(`${BASE}/agent-free/extraction/opt-in`,{method:'PUT',headers:auth,body:'{"enabled":false}'}).catch(()=>{});await usage(40).catch(()=>{});const keys=['backend','remoteDataConsent','features','routing','tierOverrides','systemone','openaiDecisions','timeoutMs','excludedModels'];await fetch(`${BASE}/agent-decisions/config`,{method:'PUT',headers:auth,body:JSON.stringify(Object.fromEntries(keys.filter(k=>k in router).map(k=>[k,router[k]])))}).catch(()=>{});for(const f of[OVERRIDE,OPERATOR])if(existsSync(f))renameSync(f,`${f}.original-cases-retained-${Date.now()}`);provider?.kill('SIGTERM')},60000);
 it('case 3/4 coding is fail-closed until a supported OS-isolated executor exists',async()=>{const before=(await requests('coding_t2')).length;const r=await api('/agent-free/tasks',{publicTaskId:'coding_t2'});expect(r).toEqual({kind:'held',reason:'untrusted_code_execution_unsupported'});expect((await requests('coding_t2')).slice(before)).toHaveLength(0)},60000);
 it('case 9 coding remains fail-closed without calling a provider',async()=>{const before=(await requests('coding_t2')).length;expect(await api('/agent-free/tasks',{publicTaskId:'coding_t2'})).toEqual({kind:'held',reason:'untrusted_code_execution_unsupported'});expect((await requests('coding_t2')).slice(before)).toHaveLength(0)},60000);
 it('case 7: T1 knowledge can_queue false uses Inkling/max degraded and verifier releases values',async()=>{await register('knowledge_t1',{content:JSON.stringify({item:{value:'Public fixture item',...span(knowledge,'Public fixture item')},price:{value:42,...span(knowledge,'$42')}})});const r=await api('/agent-free/extractions',{publicSourceId:'knowledge_t1',fields});expect(r).toMatchObject({kind:'released',model:INKLING,degraded:true,values:{item:'Public fixture item',price:42}});expect((await requests('knowledge_t1')).at(-1)?.body).toMatchObject({model:'thinkingmachines/inkling:free',reasoning:{effort:'max'}})},60000);
 it('case 8: public image bytes go to Nano helper then Ultra/medium and exact oracle releases',async()=>{await register('design_image',{byModel:{'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free':{content:'A blue square with no text.'},'nvidia/nemotron-3-ultra-550b-a55b:free':{content:JSON.stringify(design.expected)}}});const r=await api('/agent-free/tasks',{publicTaskId:'design_image'});expect(r).toMatchObject({kind:'released',model:ULTRA,effort:'medium',helper:{model:NANO,verified:true},values:design.expected});const q=await requests('design_image');expect(q).toHaveLength(2);expect(q[0].body.model).toBe('nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free');expect(JSON.stringify(q[0].body.messages)).toContain(`data:image/png;base64,${image.base64}`);expect(q[1].body).toMatchObject({model:'nvidia/nemotron-3-ultra-550b-a55b:free',reasoning:{effort:'medium'}});expect(JSON.stringify(q[1].body.messages)).toContain('A blue square with no text.');expect(JSON.stringify(q[1].body.messages)).not.toContain(image.base64)},60000);
 it('negative image: helper oracle mismatch rejects before the text model',async()=>{const before=(await requests('design_image')).length;await register('design_image',{byModel:{'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free':{content:'An unrelated red circle.'},'nvidia/nemotron-3-ultra-550b-a55b:free':{content:JSON.stringify(design.expected)}}});const r=await api('/agent-free/tasks',{publicTaskId:'design_image'});expect(r).toMatchObject({kind:'rejected',model:NANO,checks:['helper_oracle_mismatch']});expect((await requests('design_image')).slice(before)).toHaveLength(1)},60000);
});
