import 'package:flutter/foundation.dart';

import '../models/agent_skill.dart';
import '../models/agent_skill_version.dart';
import '../repositories/agent_skills_repository.dart';

enum AgentSkillsStatus { idle, loading, error }

/// Curates the shared skill library generated by the self-improvement loop.
///
/// Mirrors [AgentConfigsController]: a [ChangeNotifier] exposing a list, a
/// status enum, an error string, and CRUD methods that re-fetch/patch the
/// local agent server (`:4001`).
class AgentSkillsController extends ChangeNotifier {
  AgentSkillsController(this._repository);

  final AgentSkillsRepository _repository;

  List<AgentSkill> _skills = [];
  AgentSkillsStatus _status = AgentSkillsStatus.idle;
  String? _error;

  List<AgentSkill> get skills => List.unmodifiable(_skills);

  AgentSkillsStatus get status => _status;

  String? get error => _error;

  Future<void> loadSkills() async {
    _status = AgentSkillsStatus.loading;
    _error = null;
    notifyListeners();
    try {
      _skills = await _repository.getAll();
      _status = AgentSkillsStatus.idle;
    } catch (e) {
      _error = e.toString();
      _status = AgentSkillsStatus.error;
    }
    notifyListeners();
  }

  /// Promote a draft skill to published (`status='published'`).
  Future<bool> publishSkill(String id) async {
    try {
      final updated = await _repository.update(id, status: 'published');
      _skills = _skills.map((s) => s.id == id ? updated : s).toList();
      _error = null;
      notifyListeners();
      return true;
    } catch (e) {
      _error = e.toString();
      notifyListeners();
      return false;
    }
  }

  Future<bool> deleteSkill(String id) async {
    try {
      await _repository.delete(id);
      _skills = _skills.where((s) => s.id != id).toList();
      _error = null;
      notifyListeners();
      return true;
    } catch (e) {
      _error = e.toString();
      notifyListeners();
      return false;
    }
  }

  /// P5-3: fetch the version history for a skill. Returns null on error (and
  /// records [error]); callers surface the failure to the user.
  Future<List<AgentSkillVersion>?> loadVersions(String id) async {
    try {
      final versions = await _repository.getVersions(id);
      _error = null;
      return versions;
    } catch (e) {
      _error = e.toString();
      notifyListeners();
      return null;
    }
  }

  /// P5-3: roll back a skill to [versionNo]. On success the restored live skill
  /// replaces the in-memory row (so the version number updates immediately).
  Future<bool> rollbackSkill(String id, int versionNo) async {
    try {
      final restored = await _repository.rollback(id, versionNo);
      _skills = _skills.map((s) => s.id == id ? restored : s).toList();
      _error = null;
      notifyListeners();
      return true;
    } catch (e) {
      _error = e.toString();
      notifyListeners();
      return false;
    }
  }
}
