import React from 'react'; import { createRoot } from 'react-dom/client';
import { SettingsPage } from '../src/pages/settings'; import { GatewayProvider } from '../src/gateway/context'; import { AuthUserProvider } from '../src/gateway/auth'; import { FixtureProvider } from '../src/store';
const calls: any[] = []; Object.assign(window, { __e40: calls, rhythmShell: { appVersion: '9.9.9-test', updates: { openDownloadPage: async () => calls.push(['update']) } } });
const query = new URLSearchParams(location.search); const role = query.get('role') === 'staff' ? 'staff' as const : 'admin' as const; const userId = Number(query.get('user') ?? 1);
let workspace = { id: 8, name: 'VCRC', role, joinCode: 'OLD' };
const members = [{ userId: 1, name: 'Admin', email: 'admin@example.invalid', photoUrl: null, role: 'admin' as const }, { userId: 2, name: 'Casey', email: 'casey@example.invalid', photoUrl: null, role: 'staff' as const, isFacilitiesManager: false }];
const settings = { workspace: async () => workspace, members: async () => members, regenerateJoinCode: async () => (workspace = { ...workspace, joinCode: 'NEW' }, { joinCode: 'NEW' }), updateRole: async (...args: any[]) => calls.push(['role', ...args]), removeMember: async (...args: any[]) => calls.push(['remove', ...args]), updateUser: async (...args: any[]) => calls.push(['user', ...args]), updatePreferences: async (...args: any[]) => calls.push(['preferences', ...args]) };
const gateway: any = { mode: 'fixture', environment: null, domains: { settings }, health: { api: async () => ({ service: 'api', state: 'healthy' }), engine: async () => ({ service: 'engine', state: 'healthy' }) }, unsupported: async () => { throw new Error('unsupported'); } };
createRoot(document.getElementById('root')!).render(<GatewayProvider gateway={gateway}><AuthUserProvider user={{ id: userId, name: role === 'admin' ? 'Admin' : 'Staff', email: `${role}@example.invalid`, role }}><FixtureProvider><SettingsPage /></FixtureProvider></AuthUserProvider></GatewayProvider>);
