import React from 'react'; import { createRoot } from 'react-dom/client';
import { SettingsPage } from '../src/pages/settings'; import { GatewayProvider } from '../src/gateway/context'; import { AuthUserProvider } from '../src/gateway/auth'; import { FixtureProvider } from '../src/store';
const calls: any[] = []; Object.assign(window, { __e40: calls, rhythmShell: { appVersion: '9.9.9-test', updates: { openDownloadPage: async () => calls.push(['update']) } } });
const query = new URLSearchParams(location.search); const role = query.get('role') === 'staff' ? 'staff' as const : 'admin' as const; const userId = Number(query.get('user') ?? 1); const state = query.get('state') ?? 'ready'; const consumedTokenRace = query.get('race') === 'consumed-token';
let workspace: { id: number; name: string; role: 'admin' | 'staff'; joinCode?: string } | null = state === 'empty' ? null : { id: 8, name: 'VCRC', role, joinCode: 'OLD' };
const members = [{ userId: 1, name: 'Admin', email: 'admin@example.invalid', photoUrl: null, role: 'admin' as const }, { userId: 2, name: 'Casey', email: 'casey@example.invalid', photoUrl: null, role: 'staff' as const, isFacilitiesManager: false }];
const load = async <T,>(value: T): Promise<T> => {
  if (state === 'loading') return new Promise<T>(() => undefined);
  if (state === 'error') throw new Error('Settings could not be loaded for this workspace.');
  return value;
};
const settings = { workspace: async () => load(workspace), members: async () => load(state === 'empty' ? [] : members), regenerateJoinCode: async () => (workspace = workspace ? { ...workspace, joinCode: 'NEW' } : workspace, { joinCode: 'NEW' }), updateRole: async (...args: any[]) => calls.push(['role', ...args]), removeMember: async (...args: any[]) => calls.push(['remove', ...args]), updateUser: async (id: number, input: { isFacilitiesManager?: boolean }) => { calls.push(['user', id, input]); Object.assign(members.find(member => member.userId === id) ?? {}, input); }, updatePreferences: async (...args: any[]) => calls.push(['preferences', ...args]) };
let dayflowEnabled = false; let sourceSaved = false; let timezone = 'America/Los_Angeles'; let exclusions: string[] = []; let notes = [{ memoryId: '0123456789ABCDEFGHJKMNPQRS', importedAt: '2026-10-02T00:00:00Z', state: 'imported' as const }]; const source = { label: 'Dayflow fixture', version: '2.6.0' as const, build: '133' as const };
const readiness = () => sourceSaved ? { state: 'ready' as const, source, code: null } : { state: 'unconfigured' as const, source: null, code: 'SOURCE_MISSING' as const };
const updateDayflowConfig = async (patch: any) => {
  calls.push(['dayflow-config-save', patch]);
  if (consumedTokenRace && patch.sourceSelectionToken && !sourceSaved) await new Promise<void>((resolve) => { Object.assign(window, { __e40ReleaseFirstSave: resolve }); });
  if (patch.sourceSelectionToken && sourceSaved) throw new Error('SOURCE_CHANGED');
  sourceSaved = sourceSaved || Boolean(patch.sourceSelectionToken); dayflowEnabled = patch.enabled ?? dayflowEnabled; timezone = patch.timezone ?? timezone; exclusions = patch.exclusions ?? exclusions;
  return { enabled: dayflowEnabled, automaticImport: false, timezone, rolloverHour: 4 as const, exclusions, maxRecordsPerRun: 25, source: sourceSaved ? source : null };
};
const dayflow = { getStatus: async () => (calls.push(['dayflow-status']), { enabled: dayflowEnabled, automaticImport: false, readiness: readiness(), canPreview: dayflowEnabled && sourceSaved, importedCount: notes.length, pendingCreateCount: 0, pendingDeleteCount: 0 }), getReadiness: async () => readiness(), getConfig: async () => (calls.push(['dayflow-config']), { enabled: dayflowEnabled, automaticImport: false, timezone, rolloverHour: 4 as const, exclusions, maxRecordsPerRun: 25, source: sourceSaved ? source : null }), checkReadiness: async (path: string) => (calls.push(['dayflow-check', path]), { state: 'ready' as const, source, code: null, selectionToken: 'opaque-selection', expiresAt: '2026-10-02T00:05:00Z' }), updateConfig: updateDayflowConfig, preview: async (date: string) => (calls.push(['dayflow-preview', date]), { token: 'opaque-preview', expiresAt: '2026-10-02T00:10:00Z', date, timeZone: timezone, coverage: 'existing_cards' as const, analysisCompleteness: 'unknown' as const, candidates: [{ candidateId: 'a'.repeat(64), summary: 'Observed volunteer check-in', observedStart: '2026-10-02T08:00:00-07:00', trust: 'unverified' as const }], withheld: [] }), commit: async (token: string, candidateIds: string[]) => (calls.push(['dayflow-commit', token, candidateIds]), { items: candidateIds.map(candidateId => ({ candidateId, state: 'imported' as const, memoryId: notes[0].memoryId })) }), listOwned: async () => (calls.push(['dayflow-owned']), { items: notes, nextCursor: null, total: notes.length }), forget: async (memoryId: string) => (calls.push(['dayflow-forget', memoryId]), notes = notes.filter(note => note.memoryId !== memoryId), { memoryId, state: 'forgotten' as const }), disable: async () => (calls.push(['dayflow-disable']), dayflowEnabled = false, { enabled: false, automaticImport: false, readiness: readiness(), canPreview: false, importedCount: notes.length, pendingCreateCount: 0, pendingDeleteCount: 0 }) };
const gateway: any = { mode: 'fixture', environment: null, domains: { settings, dayflow }, health: { api: async () => ({ service: 'api', state: 'healthy' }), engine: async () => ({ service: 'engine', state: 'healthy' }) }, unsupported: async () => { throw new Error('unsupported'); } };
const auth = { signInWithGoogle: async () => { throw new Error('not used'); }, logout: async () => { calls.push(['logout']); } };
createRoot(document.getElementById('root')!).render(<GatewayProvider gateway={gateway}><AuthUserProvider auth={auth} user={{ id: userId, name: role === 'admin' ? 'Admin' : 'Staff', email: `${role}@example.invalid`, role }}><FixtureProvider><SettingsPage /></FixtureProvider></AuthUserProvider></GatewayProvider>);
