import { useMemo, useState } from 'react';
import { endpointContracts } from '../endpointMap';
import { Icon } from '../icons';
import { useFixtures } from '../store';
import { navigate } from './Shell';

export function EndpointMap() {
  const [query, setQuery] = useState(''); const [method, setMethod] = useState('ALL'); const { notify } = useFixtures();
  const visible = useMemo(() => endpointContracts.filter((item) => (method === 'ALL' || item.method === method) && `${item.control} ${item.method} ${item.route} ${item.handler} ${item.flutterSource} ${item.test} ${item.payload || ''}`.toLowerCase().includes(query.toLowerCase())), [query, method]);
  return <section className="endpoint-map-page" aria-labelledby="endpoint-title" data-od-id="endpoint-map">
    <header className="map-header"><div><button className="text-button" type="button" onClick={() => navigate('/agents')} data-testid="endpoint-back"><Icon name="chevronRight" className="rotate-180" size={14} />Back to Agents</button><h1 id="endpoint-title">Endpoint Map</h1><p>Every represented control is traceable to a shipping contract, deterministic fixture handler, and Playwright test.</p></div><div className="map-count"><strong>{visible.length}</strong><span>of {endpointContracts.length} contracts</span></div></header>
    <div className="map-toolbar"><label className="search-field"><Icon name="search" /><span className="sr-only">Search Endpoint Map</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search control, route, handler, or test" data-testid="endpoint-search" /></label><label className="method-filter">Method<select value={method} onChange={(event) => setMethod(event.target.value)} data-testid="endpoint-method"><option>ALL</option><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option><option>WS</option></select></label></div>
    <div className="endpoint-table-wrap"><table data-testid="endpoint-table"><caption className="sr-only">Endpoint-to-control traceability matrix</caption><thead><tr><th>Control</th><th>Method / channel</th><th>Exact route / event</th><th>Flutter source</th><th>Fixture handler</th><th>Playwright test</th><th>Payload shape</th><th><span className="sr-only">Copy</span></th></tr></thead><tbody>{visible.map((item) => <tr key={item.id} data-testid={`endpoint-row-${item.id}`}><td><strong>{item.control}</strong></td><td><span className={`method ${item.method.toLowerCase()}`}>{item.method}</span></td><td><code>{item.route}</code></td><td><code>{item.flutterSource}</code></td><td><code>{item.handler}</code></td><td><code>{item.test}</code></td><td><code className="payload">{item.payload || '-'}</code></td><td><button className="icon-button small" type="button" aria-label={`Copy ${item.route}`} onClick={() => notify(`${item.method} ${item.route} copied`)}><Icon name="copy" size={14} /></button></td></tr>)}</tbody></table>{visible.length === 0 && <div className="table-empty"><Icon name="search" /><h2>No contracts match</h2><p>Clear the search or choose another method.</p><button className="secondary-button" type="button" onClick={() => { setQuery(''); setMethod('ALL'); }}>Clear filters</button></div>}</div>
  </section>;
}
