import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../../app/core/ui/tokens/rhythm_theme.dart';
import '../controllers/agent_skills_controller.dart';
import '../models/agent_skill.dart';
import '../models/agent_skill_version.dart';

/// Lists the skills generated by the self-improvement loop and lets the user
/// curate them: publish a draft (draft→published) or delete one.
///
/// MVP: one skill at a time, no sorting/filtering. Backed by the local agent
/// server's `/agent-skills` routes via [AgentSkillsController].
class AgentSkillsView extends StatefulWidget {
  const AgentSkillsView({super.key});

  @override
  State<AgentSkillsView> createState() => _AgentSkillsViewState();
}

class _AgentSkillsViewState extends State<AgentSkillsView> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<AgentSkillsController>().loadSkills();
    });
  }

  Future<void> _confirmDelete(BuildContext context, AgentSkill skill) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: ctx.rhythm.surface,
        title: Text(
          'Delete Skill',
          style: TextStyle(color: ctx.rhythm.textPrimary),
        ),
        content: Text(
          'Delete "${skill.title}"? This cannot be undone.',
          style: TextStyle(color: ctx.rhythm.textSecondary),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child:
                Text('Cancel', style: TextStyle(color: ctx.rhythm.textMuted)),
          ),
          TextButton(
            onPressed: () => Navigator.pop(ctx, true),
            child: Text('Delete', style: TextStyle(color: ctx.rhythm.danger)),
          ),
        ],
      ),
    );
    if (confirmed == true && context.mounted) {
      await context.read<AgentSkillsController>().deleteSkill(skill.id);
    }
  }

  Future<void> _publish(BuildContext context, AgentSkill skill) async {
    final ok =
        await context.read<AgentSkillsController>().publishSkill(skill.id);
    if (!context.mounted) return;
    if (!ok) {
      final err =
          context.read<AgentSkillsController>().error ?? 'Unknown error';
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error: $err'),
          backgroundColor: context.rhythm.danger,
        ),
      );
    }
  }

  Future<void> _showHistory(BuildContext context, AgentSkill skill) async {
    final controller = context.read<AgentSkillsController>();
    final versions = await controller.loadVersions(skill.id);
    if (!context.mounted) return;
    if (versions == null) {
      final err = controller.error ?? 'Unknown error';
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error loading history: $err'),
          backgroundColor: context.rhythm.danger,
        ),
      );
      return;
    }
    await showDialog<void>(
      context: context,
      builder: (ctx) => _HistoryDialog(
        skill: skill,
        versions: versions,
        onRollback: (versionNo) async {
          Navigator.pop(ctx);
          final ok = await controller.rollbackSkill(skill.id, versionNo);
          if (!context.mounted) return;
          if (!ok) {
            final err = controller.error ?? 'Unknown error';
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text('Rollback failed: $err'),
                backgroundColor: context.rhythm.danger,
              ),
            );
          } else {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text('Rolled back "${skill.title}"'),
                backgroundColor: context.rhythm.accent,
              ),
            );
          }
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Consumer<AgentSkillsController>(
      builder: (context, controller, _) {
        return Scaffold(
          backgroundColor: context.rhythm.canvas,
          appBar: AppBar(
            backgroundColor: context.rhythm.surface,
            elevation: 0,
            title: Text(
              'Skills',
              style: TextStyle(
                color: context.rhythm.textPrimary,
                fontWeight: FontWeight.w600,
                fontSize: 18,
              ),
            ),
            actions: [
              if (controller.status == AgentSkillsStatus.idle)
                IconButton(
                  icon: Icon(
                    Icons.refresh_rounded,
                    color: context.rhythm.textSecondary,
                  ),
                  tooltip: 'Refresh',
                  onPressed: () => controller.loadSkills(),
                ),
            ],
          ),
          body: _buildBody(context, controller),
        );
      },
    );
  }

  Widget _buildBody(BuildContext context, AgentSkillsController controller) {
    if (controller.status == AgentSkillsStatus.loading &&
        controller.skills.isEmpty) {
      return Center(
        child: CircularProgressIndicator(color: context.rhythm.accent),
      );
    }

    if (controller.status == AgentSkillsStatus.error &&
        controller.skills.isEmpty) {
      return Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              Icons.error_outline_rounded,
              color: context.rhythm.danger,
              size: 48,
            ),
            const SizedBox(height: RhythmSpacing.md),
            Text(
              controller.error ?? 'An error occurred',
              style: TextStyle(color: context.rhythm.textSecondary),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: RhythmSpacing.md),
            FilledButton(
              onPressed: () => controller.loadSkills(),
              style: FilledButton.styleFrom(
                backgroundColor: context.rhythm.accent,
              ),
              child: const Text('Retry'),
            ),
          ],
        ),
      );
    }

    if (controller.skills.isEmpty) {
      return Center(
        key: const ValueKey('skills-empty-state'),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              Icons.auto_awesome_outlined,
              color: context.rhythm.textMuted,
              size: 56,
            ),
            const SizedBox(height: RhythmSpacing.md),
            Text(
              'No skills yet',
              style: TextStyle(
                color: context.rhythm.textSecondary,
                fontSize: 16,
                fontWeight: FontWeight.w500,
              ),
            ),
            const SizedBox(height: RhythmSpacing.xs),
            Text(
              'Skills appear here as the self-improvement loop learns',
              style: TextStyle(color: context.rhythm.textMuted, fontSize: 13),
            ),
          ],
        ),
      );
    }

    return ListView.separated(
      padding: const EdgeInsets.all(RhythmSpacing.md),
      itemCount: controller.skills.length,
      separatorBuilder: (_, __) => const SizedBox(height: RhythmSpacing.xs),
      itemBuilder: (context, index) {
        final skill = controller.skills[index];
        return _SkillTile(
          skill: skill,
          onPublish: () => _publish(context, skill),
          onDelete: () => _confirmDelete(context, skill),
          onHistory: () => _showHistory(context, skill),
        );
      },
    );
  }
}

// ---------------------------------------------------------------------------
// Skill tile
// ---------------------------------------------------------------------------

class _SkillTile extends StatelessWidget {
  const _SkillTile({
    required this.skill,
    required this.onPublish,
    required this.onDelete,
    required this.onHistory,
  });

  final AgentSkill skill;
  final VoidCallback onPublish;
  final VoidCallback onDelete;
  final VoidCallback onHistory;

  @override
  Widget build(BuildContext context) {
    final rhythm = context.rhythm;
    final snippet = skill.description ?? skill.whenToUse;

    return Container(
      decoration: BoxDecoration(
        color: rhythm.surfaceRaised,
        borderRadius: BorderRadius.circular(RhythmRadius.md),
        border: Border.all(color: rhythm.borderSubtle),
        boxShadow: RhythmElevation.panel,
      ),
      padding: const EdgeInsets.all(RhythmSpacing.md),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(Icons.auto_awesome_outlined, color: rhythm.accent, size: 20),
          const SizedBox(width: RhythmSpacing.sm),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Title + DRAFT badge.
                Row(
                  children: [
                    Flexible(
                      child: Text(
                        skill.title,
                        style: TextStyle(
                          color: rhythm.textPrimary,
                          fontWeight: FontWeight.w600,
                          fontSize: 14,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                    if (skill.isDraft) ...[
                      const SizedBox(width: 6),
                      const _DraftBadge(),
                    ],
                  ],
                ),
                if (snippet != null && snippet.isNotEmpty) ...[
                  const SizedBox(height: RhythmSpacing.xxs),
                  Text(
                    snippet,
                    style: TextStyle(color: rhythm.textSecondary, fontSize: 12),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                  ),
                ],
                const SizedBox(height: RhythmSpacing.xxs),
                // Source + confidence meta line.
                Row(
                  children: [
                    Text(
                      '${skill.source ?? 'unknown'} · '
                      'confidence ${skill.confidence.toStringAsFixed(2)} · '
                      'v${skill.version}',
                      style: TextStyle(color: rhythm.textMuted, fontSize: 11),
                    ),
                  ],
                ),
                if (skill.isTeacherEscalation) ...[
                  const SizedBox(height: RhythmSpacing.xxs),
                  Text(
                    '⭐ learned from failure',
                    style: TextStyle(
                      color: rhythm.warning,
                      fontSize: 11,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ],
              ],
            ),
          ),
          // Version history + rollback.
          IconButton(
            key: ValueKey('history-skill-${skill.id}'),
            icon: Icon(Icons.history_rounded,
                color: rhythm.textSecondary, size: 19),
            tooltip: 'History',
            onPressed: onHistory,
            padding: EdgeInsets.zero,
            constraints: const BoxConstraints(minWidth: 32, minHeight: 32),
          ),
          // Publish (only meaningful for drafts).
          if (skill.isDraft)
            IconButton(
              key: ValueKey('publish-skill-${skill.id}'),
              icon: Icon(Icons.publish_rounded, color: rhythm.accent, size: 20),
              tooltip: 'Publish',
              onPressed: onPublish,
              padding: EdgeInsets.zero,
              constraints: const BoxConstraints(minWidth: 32, minHeight: 32),
            ),
          IconButton(
            key: ValueKey('delete-skill-${skill.id}'),
            icon: Icon(
              Icons.delete_outline_rounded,
              color: rhythm.textMuted,
              size: 18,
            ),
            tooltip: 'Delete',
            onPressed: onDelete,
            padding: EdgeInsets.zero,
            constraints: const BoxConstraints(minWidth: 32, minHeight: 32),
          ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Version history dialog (P5-3)
// ---------------------------------------------------------------------------

/// Lists a skill's prior versions (newest first) with a one-click
/// "Rollback to this version" action per row.
class _HistoryDialog extends StatelessWidget {
  const _HistoryDialog({
    required this.skill,
    required this.versions,
    required this.onRollback,
  });

  final AgentSkill skill;
  final List<AgentSkillVersion> versions;

  /// Called with the chosen `versionNo` when the user taps Rollback.
  final void Function(int versionNo) onRollback;

  @override
  Widget build(BuildContext context) {
    final rhythm = context.rhythm;
    return AlertDialog(
      backgroundColor: rhythm.surface,
      title: Text(
        'Version history — ${skill.title}',
        style: TextStyle(color: rhythm.textPrimary, fontSize: 16),
      ),
      content: SizedBox(
        width: 420,
        child: versions.isEmpty
            ? Padding(
                key: const ValueKey('history-empty'),
                padding: const EdgeInsets.symmetric(vertical: RhythmSpacing.md),
                child: Text(
                  'No prior versions yet — this skill is at v${skill.version}.',
                  style: TextStyle(color: rhythm.textSecondary, fontSize: 13),
                ),
              )
            : ListView.separated(
                shrinkWrap: true,
                itemCount: versions.length,
                separatorBuilder: (_, __) => Divider(
                    color: rhythm.borderSubtle, height: RhythmSpacing.md),
                itemBuilder: (context, index) {
                  final v = versions[index];
                  return Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'v${v.versionNo} · ${v.source ?? 'unknown'}',
                              style: TextStyle(
                                color: rhythm.textPrimary,
                                fontWeight: FontWeight.w600,
                                fontSize: 13,
                              ),
                            ),
                            const SizedBox(height: RhythmSpacing.xxs),
                            Text(
                              v.createdAt,
                              style: TextStyle(
                                color: rhythm.textMuted,
                                fontSize: 11,
                              ),
                            ),
                            if (v.description != null &&
                                v.description!.isNotEmpty) ...[
                              const SizedBox(height: RhythmSpacing.xxs),
                              Text(
                                v.description!,
                                style: TextStyle(
                                  color: rhythm.textSecondary,
                                  fontSize: 12,
                                ),
                                maxLines: 2,
                                overflow: TextOverflow.ellipsis,
                              ),
                            ],
                          ],
                        ),
                      ),
                      TextButton(
                        key: ValueKey('rollback-version-${v.versionNo}'),
                        onPressed: () => onRollback(v.versionNo),
                        child: Text(
                          'Rollback',
                          style: TextStyle(color: rhythm.accent),
                        ),
                      ),
                    ],
                  );
                },
              ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: Text('Close', style: TextStyle(color: rhythm.textMuted)),
        ),
      ],
    );
  }
}

/// Amber pill rendered next to a draft skill's title.
class _DraftBadge extends StatelessWidget {
  const _DraftBadge();

  @override
  Widget build(BuildContext context) {
    final rhythm = context.rhythm;
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 1),
      decoration: BoxDecoration(
        color: rhythm.warning.withValues(alpha: 0.18),
        borderRadius: BorderRadius.circular(RhythmRadius.xs),
        border: Border.all(color: rhythm.warning.withValues(alpha: 0.5)),
      ),
      child: Text(
        'DRAFT',
        style: TextStyle(
          fontSize: 10,
          fontWeight: FontWeight.w700,
          letterSpacing: 0.6,
          color: rhythm.warning,
        ),
      ),
    );
  }
}
