// Generated by package-mac.mjs. The OAuth client ID is public; no client secret is embedded.
export const GOOGLE_DESKTOP_CLIENT_ID = "";
export const RHYTHM_AUTH_API_BASE = 'https://api.vcrcapps.com';
