import type { Pool } from 'pg';

const UTC_TEXT_NOW =
  `to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')`;

export async function runPostgresBootstrap(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      google_sub TEXT UNIQUE,
      photo_url TEXT,
      role TEXT NOT NULL DEFAULT 'member',
      is_facilities_manager BOOLEAN NOT NULL DEFAULT FALSE,
      password_hash TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS tasks (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      due_date TEXT,
      status TEXT NOT NULL DEFAULT 'open',
      source_type TEXT,
      source_id TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      scheduled_date TEXT,
      locked BOOLEAN NOT NULL DEFAULT FALSE,
      notes TEXT,
      owner_id INTEGER REFERENCES users(id),
      scheduled_order INTEGER
    );

    CREATE TABLE IF NOT EXISTS recurring_task_rules (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      frequency TEXT NOT NULL,
      day_of_week INTEGER,
      day_of_month INTEGER,
      month INTEGER,
      steps_json TEXT NOT NULL DEFAULT '[]',
      enabled BOOLEAN NOT NULL DEFAULT TRUE,
      owner_id INTEGER REFERENCES users(id),
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS project_templates (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      anchor_type TEXT NOT NULL DEFAULT 'date',
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS project_template_steps (
      id TEXT PRIMARY KEY,
      template_id TEXT NOT NULL REFERENCES project_templates(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      offset_days INTEGER NOT NULL DEFAULT 0,
      offset_description TEXT,
      sort_order INTEGER NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS project_instances (
      id TEXT PRIMARY KEY,
      template_id TEXT NOT NULL REFERENCES project_templates(id),
      name TEXT,
      anchor_date TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'active',
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS project_instance_steps (
      id TEXT PRIMARY KEY,
      instance_id TEXT NOT NULL REFERENCES project_instances(id) ON DELETE CASCADE,
      step_id TEXT NOT NULL REFERENCES project_template_steps(id),
      title TEXT NOT NULL,
      due_date TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'open',
      notes TEXT
    );

    CREATE TABLE IF NOT EXISTS weekly_plans (
      id TEXT PRIMARY KEY,
      week_label TEXT NOT NULL UNIQUE,
      week_start_date TEXT NOT NULL,
      locked BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS integration_accounts (
      id TEXT PRIMARY KEY,
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      provider TEXT NOT NULL,
      external_account_id TEXT NOT NULL,
      email TEXT,
      display_name TEXT,
      status TEXT NOT NULL DEFAULT 'connected',
      access_token TEXT,
      refresh_token TEXT,
      scope TEXT,
      token_type TEXT,
      expires_at TEXT,
      last_synced_at TEXT,
      error_message TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      UNIQUE(owner_id, provider)
    );

    CREATE TABLE IF NOT EXISTS calendar_shadow_events (
      id TEXT PRIMARY KEY,
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      provider TEXT NOT NULL,
      external_id TEXT NOT NULL,
      calendar_id TEXT NOT NULL,
      source_name TEXT,
      title TEXT NOT NULL,
      description TEXT,
      location TEXT,
      start_at TEXT NOT NULL,
      end_at TEXT,
      is_all_day BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      UNIQUE(owner_id, external_id)
    );

    CREATE TABLE IF NOT EXISTS gmail_signals (
      id TEXT PRIMARY KEY,
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      external_id TEXT NOT NULL,
      thread_id TEXT NOT NULL,
      from_name TEXT,
      from_email TEXT,
      subject TEXT,
      snippet TEXT,
      received_at TEXT,
      is_unread BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      UNIQUE(owner_id, external_id)
    );

    CREATE TABLE IF NOT EXISTS integration_preferences (
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      provider TEXT NOT NULL,
      key TEXT NOT NULL,
      json_value TEXT NOT NULL,
      PRIMARY KEY (owner_id, provider, key)
    );

    CREATE TABLE IF NOT EXISTS automation_rules (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      trigger_type TEXT NOT NULL,
      trigger_config TEXT,
      action_type TEXT NOT NULL,
      action_config TEXT,
      enabled BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      owner_id INTEGER REFERENCES users(id),
      source TEXT,
      trigger_key TEXT,
      source_account_id TEXT REFERENCES integration_accounts(id),
      last_evaluated_at TEXT,
      last_matched_at TEXT,
      match_count_last_run INTEGER NOT NULL DEFAULT 0,
      preview_sample TEXT,
      conditions TEXT
    );

    CREATE TABLE IF NOT EXISTS automation_signals (
      id TEXT PRIMARY KEY,
      provider TEXT NOT NULL,
      signal_type TEXT NOT NULL,
      external_id TEXT NOT NULL,
      dedupe_key TEXT NOT NULL UNIQUE,
      occurred_at TEXT,
      synced_at TEXT NOT NULL,
      source_account_id TEXT,
      source_label TEXT,
      payload_json TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS sessions (
      token TEXT PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      expires_at TEXT
    );

    CREATE TABLE IF NOT EXISTS message_threads (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      created_by INTEGER REFERENCES users(id),
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS messages (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      thread_id INTEGER NOT NULL REFERENCES message_threads(id) ON DELETE CASCADE,
      sender_id INTEGER REFERENCES users(id),
      sender_name TEXT NOT NULL,
      body TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS facilities (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      capacity INTEGER,
      location TEXT,
      building TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS reservation_series (
      id TEXT PRIMARY KEY,
      facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      requester_name TEXT NOT NULL,
      requester_user_id INTEGER REFERENCES users(id),
      created_by_user_id INTEGER REFERENCES users(id),
      notes TEXT,
      recurrence_type TEXT NOT NULL,
      recurrence_interval INTEGER,
      weekday_pattern_json TEXT,
      custom_dates_json TEXT NOT NULL DEFAULT '[]',
      start_date TEXT NOT NULL,
      end_date TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS reservation_groups (
      id TEXT PRIMARY KEY,
      series_id TEXT REFERENCES reservation_series(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      requester_name TEXT NOT NULL,
      requester_user_id INTEGER REFERENCES users(id),
      created_by_user_id INTEGER REFERENCES users(id),
      notes TEXT,
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      occurrence_date TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS reservations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
      group_id TEXT REFERENCES reservation_groups(id) ON DELETE CASCADE,
      series_id TEXT REFERENCES reservation_series(id) ON DELETE SET NULL,
      title TEXT NOT NULL,
      reserved_by TEXT NOT NULL,
      reserved_by_user_id INTEGER REFERENCES users(id),
      created_by_user_id INTEGER REFERENCES users(id),
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      notes TEXT,
      external_event_id TEXT,
      external_source TEXT,
      created_by_rhythm BOOLEAN NOT NULL DEFAULT TRUE,
      is_conflicted BOOLEAN NOT NULL DEFAULT FALSE,
      conflict_reason TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS thread_participants (
      thread_id INTEGER NOT NULL REFERENCES message_threads(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      PRIMARY KEY (thread_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS thread_reads (
      thread_id INTEGER NOT NULL REFERENCES message_threads(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      last_read_at TEXT,
      PRIMARY KEY (thread_id, user_id)
    );
  `);

  await pool.query(`
    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS scheduled_date TEXT;
    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS locked BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS notes TEXT;
    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id);
    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS scheduled_order INTEGER;

    ALTER TABLE recurring_task_rules ADD COLUMN IF NOT EXISTS steps_json TEXT NOT NULL DEFAULT '[]';
    ALTER TABLE recurring_task_rules ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE recurring_task_rules ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id);

    ALTER TABLE project_templates ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE;
    ALTER TABLE project_instances ADD COLUMN IF NOT EXISTS name TEXT;
    ALTER TABLE project_instances ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE;
    ALTER TABLE project_instance_steps ADD COLUMN IF NOT EXISTS notes TEXT;

    ALTER TABLE users ADD COLUMN IF NOT EXISTS google_sub TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_url TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'member';
    ALTER TABLE users ADD COLUMN IF NOT EXISTS is_facilities_manager BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT;

    ALTER TABLE facilities ADD COLUMN IF NOT EXISTS building TEXT;

    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS group_id TEXT REFERENCES reservation_groups(id) ON DELETE CASCADE;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS series_id TEXT REFERENCES reservation_series(id) ON DELETE SET NULL;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS reserved_by_user_id INTEGER REFERENCES users(id);
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS created_by_user_id INTEGER REFERENCES users(id);
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS external_event_id TEXT;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS external_source TEXT;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS created_by_rhythm BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS is_conflicted BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS conflict_reason TEXT;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW});

    ALTER TABLE reservation_series ADD COLUMN IF NOT EXISTS recurrence_interval INTEGER;
    ALTER TABLE reservation_series ADD COLUMN IF NOT EXISTS weekday_pattern_json TEXT;
    ALTER TABLE reservation_series ADD COLUMN IF NOT EXISTS custom_dates_json TEXT NOT NULL DEFAULT '[]';
    ALTER TABLE reservation_series ADD COLUMN IF NOT EXISTS end_date TEXT;
    ALTER TABLE reservation_series ADD COLUMN IF NOT EXISTS updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW});

    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id);
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS source TEXT;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS trigger_key TEXT;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS source_account_id TEXT REFERENCES integration_accounts(id);
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS last_evaluated_at TEXT;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS last_matched_at TEXT;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS match_count_last_run INTEGER NOT NULL DEFAULT 0;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS preview_sample TEXT;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS conditions TEXT;
  `);

  await pool.query(`
    UPDATE automation_rules
    SET source = CASE trigger_type
      WHEN 'project_step_due' THEN 'rhythm'
      WHEN 'task_due' THEN 'rhythm'
      WHEN 'plan_assembly' THEN 'rhythm'
      ELSE COALESCE(source, 'rhythm')
    END
    WHERE source IS NULL
  `);

  await pool.query(`
    UPDATE automation_rules
    SET trigger_key = CASE trigger_type
      WHEN 'project_step_due' THEN 'rhythm.project_step_due'
      WHEN 'task_due' THEN 'rhythm.task_due'
      WHEN 'plan_assembly' THEN 'rhythm.plan_assembly'
      ELSE COALESCE(trigger_key, trigger_type)
    END
    WHERE trigger_key IS NULL
  `);

  // Phase 7: workspaces, collaborators, messaging identity
  await pool.query(`
    CREATE TABLE IF NOT EXISTS workspaces (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      join_code TEXT NOT NULL UNIQUE,
      created_by INTEGER REFERENCES users(id),
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS workspace_members (
      workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      role TEXT NOT NULL DEFAULT 'staff',
      joined_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      PRIMARY KEY (workspace_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS task_collaborators (
      task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      added_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      PRIMARY KEY (task_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS project_collaborators (
      project_instance_id TEXT NOT NULL REFERENCES project_instances(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      added_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      PRIMARY KEY (project_instance_id, user_id)
    );
  `);

  await pool.query(`ALTER TABLE tasks ADD COLUMN IF NOT EXISTS workspace_id INTEGER REFERENCES workspaces(id)`);
  await pool.query(`ALTER TABLE messages ADD COLUMN IF NOT EXISTS sender_photo_url TEXT`);
  await pool.query(`ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS thread_type TEXT NOT NULL DEFAULT 'direct'`);

  // Phase 8: step assignees + rhythm collaborators
  await pool.query(`ALTER TABLE project_template_steps ADD COLUMN IF NOT EXISTS assignee_id INTEGER REFERENCES users(id) ON DELETE SET NULL`);
  await pool.query(`ALTER TABLE project_instance_steps ADD COLUMN IF NOT EXISTS assignee_id INTEGER REFERENCES users(id) ON DELETE SET NULL`);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS rhythm_collaborators (
      rhythm_id TEXT NOT NULL REFERENCES recurring_task_rules(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      added_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      PRIMARY KEY (rhythm_id, user_id)
    )
  `);

  // Notifications
  await pool.query(`
    CREATE TABLE IF NOT EXISTS notifications (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      recipient_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      type TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      message TEXT NOT NULL,
      read_at TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_notifications_recipient
      ON notifications(recipient_user_id, read_at)
  `);
}
