import type { Pool } from 'pg';

import { env } from '../config/env';
import { convertLegacyNumberedCorePermissions } from './core_permissions_repair';

const UTC_TEXT_NOW =
  `to_char(timezone('utc', now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')`;

export async function runPostgresBootstrap(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      google_sub TEXT UNIQUE,
      photo_url TEXT,
      role TEXT NOT NULL DEFAULT 'member',
      is_facilities_manager BOOLEAN NOT NULL DEFAULT FALSE,
      email_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
      password_hash TEXT,
      timezone TEXT NOT NULL DEFAULT 'America/Los_Angeles',
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS tasks (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      due_date TEXT,
      status TEXT NOT NULL DEFAULT 'open',
      source_type TEXT,
      source_id TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      scheduled_date TEXT,
      locked BOOLEAN NOT NULL DEFAULT FALSE,
      notes TEXT,
      owner_id INTEGER REFERENCES users(id),
      scheduled_order INTEGER
    );

    CREATE TABLE IF NOT EXISTS recurring_task_rules (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      frequency TEXT NOT NULL,
      day_of_week INTEGER,
      day_of_month INTEGER,
      month INTEGER,
      steps_json TEXT NOT NULL DEFAULT '[]',
      enabled BOOLEAN NOT NULL DEFAULT TRUE,
      sequential BOOLEAN NOT NULL DEFAULT FALSE,
      owner_id INTEGER REFERENCES users(id),
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS project_templates (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      anchor_type TEXT NOT NULL DEFAULT 'date',
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS project_template_steps (
      id TEXT PRIMARY KEY,
      template_id TEXT NOT NULL REFERENCES project_templates(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      offset_days INTEGER NOT NULL DEFAULT 0,
      offset_description TEXT,
      sort_order INTEGER NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS project_instances (
      id TEXT PRIMARY KEY,
      template_id TEXT NOT NULL REFERENCES project_templates(id),
      name TEXT,
      anchor_date TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'active',
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS project_instance_steps (
      id TEXT PRIMARY KEY,
      instance_id TEXT NOT NULL REFERENCES project_instances(id) ON DELETE CASCADE,
      step_id TEXT NOT NULL REFERENCES project_template_steps(id),
      title TEXT NOT NULL,
      due_date TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'open',
      notes TEXT
    );

    CREATE TABLE IF NOT EXISTS weekly_plans (
      id TEXT PRIMARY KEY,
      week_label TEXT NOT NULL UNIQUE,
      week_start_date TEXT NOT NULL,
      locked BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS integration_accounts (
      id TEXT PRIMARY KEY,
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      provider TEXT NOT NULL,
      external_account_id TEXT NOT NULL,
      email TEXT,
      display_name TEXT,
      status TEXT NOT NULL DEFAULT 'connected',
      access_token TEXT,
      refresh_token TEXT,
      scope TEXT,
      token_type TEXT,
      expires_at TEXT,
      last_synced_at TEXT,
      error_message TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      UNIQUE(owner_id, provider)
    );

    CREATE TABLE IF NOT EXISTS calendar_shadow_events (
      id TEXT PRIMARY KEY,
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      provider TEXT NOT NULL,
      external_id TEXT NOT NULL,
      calendar_id TEXT NOT NULL,
      source_name TEXT,
      title TEXT NOT NULL,
      description TEXT,
      location TEXT,
      start_at TEXT NOT NULL,
      end_at TEXT,
      is_all_day BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      UNIQUE(owner_id, external_id)
    );

    CREATE TABLE IF NOT EXISTS gmail_signals (
      id TEXT PRIMARY KEY,
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      external_id TEXT NOT NULL,
      thread_id TEXT NOT NULL,
      from_name TEXT,
      from_email TEXT,
      subject TEXT,
      snippet TEXT,
      received_at TEXT,
      is_unread BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      UNIQUE(owner_id, external_id)
    );

    CREATE TABLE IF NOT EXISTS integration_preferences (
      owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      provider TEXT NOT NULL,
      key TEXT NOT NULL,
      json_value TEXT NOT NULL,
      PRIMARY KEY (owner_id, provider, key)
    );

    CREATE TABLE IF NOT EXISTS automation_rules (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      trigger_type TEXT NOT NULL,
      trigger_config TEXT,
      action_type TEXT NOT NULL,
      action_config TEXT,
      enabled BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      owner_id INTEGER REFERENCES users(id),
      source TEXT,
      trigger_key TEXT,
      source_account_id TEXT REFERENCES integration_accounts(id),
      last_evaluated_at TEXT,
      last_matched_at TEXT,
      match_count_last_run INTEGER NOT NULL DEFAULT 0,
      preview_sample TEXT,
      conditions TEXT
    );

    CREATE TABLE IF NOT EXISTS automation_signals (
      id TEXT PRIMARY KEY,
      provider TEXT NOT NULL,
      signal_type TEXT NOT NULL,
      external_id TEXT NOT NULL,
      dedupe_key TEXT NOT NULL UNIQUE,
      occurred_at TEXT,
      synced_at TEXT NOT NULL,
      source_account_id TEXT,
      source_label TEXT,
      payload_json TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS sessions (
      token TEXT PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      expires_at TEXT
    );

    CREATE TABLE IF NOT EXISTS message_threads (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      created_by INTEGER REFERENCES users(id),
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS messages (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      thread_id INTEGER NOT NULL REFERENCES message_threads(id) ON DELETE CASCADE,
      sender_id INTEGER REFERENCES users(id),
      sender_name TEXT NOT NULL,
      body TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS facilities (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      capacity INTEGER,
      location TEXT,
      building TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS reservation_series (
      id TEXT PRIMARY KEY,
      facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      requester_name TEXT NOT NULL,
      requester_user_id INTEGER REFERENCES users(id),
      created_by_user_id INTEGER REFERENCES users(id),
      notes TEXT,
      recurrence_type TEXT NOT NULL,
      recurrence_interval INTEGER,
      weekday_pattern_json TEXT,
      custom_dates_json TEXT NOT NULL DEFAULT '[]',
      start_date TEXT NOT NULL,
      end_date TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS reservation_groups (
      id TEXT PRIMARY KEY,
      series_id TEXT REFERENCES reservation_series(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      requester_name TEXT NOT NULL,
      requester_user_id INTEGER REFERENCES users(id),
      created_by_user_id INTEGER REFERENCES users(id),
      notes TEXT,
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      occurrence_date TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS reservations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
      group_id TEXT REFERENCES reservation_groups(id) ON DELETE CASCADE,
      series_id TEXT REFERENCES reservation_series(id) ON DELETE SET NULL,
      title TEXT NOT NULL,
      reserved_by TEXT NOT NULL,
      reserved_by_user_id INTEGER REFERENCES users(id),
      created_by_user_id INTEGER REFERENCES users(id),
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      notes TEXT,
      external_event_id TEXT,
      external_source TEXT,
      created_by_rhythm BOOLEAN NOT NULL DEFAULT TRUE,
      is_conflicted BOOLEAN NOT NULL DEFAULT FALSE,
      conflict_reason TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS thread_participants (
      thread_id INTEGER NOT NULL REFERENCES message_threads(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      PRIMARY KEY (thread_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS thread_reads (
      thread_id INTEGER NOT NULL REFERENCES message_threads(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      last_read_at TEXT,
      PRIMARY KEY (thread_id, user_id)
    );
  `);

  await pool.query(`
    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS scheduled_date TEXT;
    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS locked BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS notes TEXT;
    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id);
    ALTER TABLE tasks ADD COLUMN IF NOT EXISTS scheduled_order INTEGER;

    ALTER TABLE recurring_task_rules ADD COLUMN IF NOT EXISTS steps_json TEXT NOT NULL DEFAULT '[]';
    ALTER TABLE recurring_task_rules ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE recurring_task_rules ADD COLUMN IF NOT EXISTS sequential BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE recurring_task_rules ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id);

    ALTER TABLE project_templates ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE;
    ALTER TABLE project_instances ADD COLUMN IF NOT EXISTS name TEXT;
    ALTER TABLE project_instances ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE;
    ALTER TABLE project_instance_steps ADD COLUMN IF NOT EXISTS notes TEXT;

    ALTER TABLE users ADD COLUMN IF NOT EXISTS google_sub TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_url TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'member';
    ALTER TABLE users ADD COLUMN IF NOT EXISTS is_facilities_manager BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS email_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'America/Los_Angeles';

    ALTER TABLE facilities ADD COLUMN IF NOT EXISTS building TEXT;

    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS group_id TEXT REFERENCES reservation_groups(id) ON DELETE CASCADE;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS series_id TEXT REFERENCES reservation_series(id) ON DELETE SET NULL;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS reserved_by_user_id INTEGER REFERENCES users(id);
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS created_by_user_id INTEGER REFERENCES users(id);
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS external_event_id TEXT;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS external_source TEXT;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS created_by_rhythm BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS is_conflicted BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS conflict_reason TEXT;
    ALTER TABLE reservations ADD COLUMN IF NOT EXISTS updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW});

    ALTER TABLE reservation_series ADD COLUMN IF NOT EXISTS recurrence_interval INTEGER;
    ALTER TABLE reservation_series ADD COLUMN IF NOT EXISTS weekday_pattern_json TEXT;
    ALTER TABLE reservation_series ADD COLUMN IF NOT EXISTS custom_dates_json TEXT NOT NULL DEFAULT '[]';
    ALTER TABLE reservation_series ADD COLUMN IF NOT EXISTS end_date TEXT;
    ALTER TABLE reservation_series ADD COLUMN IF NOT EXISTS updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW});

    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES users(id);
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS source TEXT;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS trigger_key TEXT;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS source_account_id TEXT REFERENCES integration_accounts(id);
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS last_evaluated_at TEXT;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS last_matched_at TEXT;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS match_count_last_run INTEGER NOT NULL DEFAULT 0;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS preview_sample TEXT;
    ALTER TABLE automation_rules ADD COLUMN IF NOT EXISTS conditions TEXT;

    -- integration_accounts: backfill columns added after the table's original
    -- release. These live in the CREATE TABLE block above, but CREATE TABLE IF
    -- NOT EXISTS does NOT alter a pre-existing table — so production DBs created
    -- before these columns existed were missing them, and the Google sign-in
    -- upsert (which writes status/error_message/etc.) failed with a 500
    -- ("column does not exist"). Idempotent ADD COLUMN IF NOT EXISTS backfills.
    ALTER TABLE integration_accounts ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'connected';
    ALTER TABLE integration_accounts ADD COLUMN IF NOT EXISTS error_message TEXT;
    ALTER TABLE integration_accounts ADD COLUMN IF NOT EXISTS email TEXT;
    ALTER TABLE integration_accounts ADD COLUMN IF NOT EXISTS display_name TEXT;
    ALTER TABLE integration_accounts ADD COLUMN IF NOT EXISTS refresh_token TEXT;
    ALTER TABLE integration_accounts ADD COLUMN IF NOT EXISTS scope TEXT;
    ALTER TABLE integration_accounts ADD COLUMN IF NOT EXISTS token_type TEXT;
    ALTER TABLE integration_accounts ADD COLUMN IF NOT EXISTS expires_at TEXT;
    ALTER TABLE integration_accounts ADD COLUMN IF NOT EXISTS last_synced_at TEXT;
  `);

  await pool.query(`
    UPDATE automation_rules
    SET source = CASE trigger_type
      WHEN 'project_step_due' THEN 'rhythm'
      WHEN 'task_due' THEN 'rhythm'
      WHEN 'plan_assembly' THEN 'rhythm'
      ELSE COALESCE(source, 'rhythm')
    END
    WHERE source IS NULL
  `);

  await pool.query(`
    UPDATE automation_rules
    SET trigger_key = CASE trigger_type
      WHEN 'project_step_due' THEN 'rhythm.project_step_due'
      WHEN 'task_due' THEN 'rhythm.task_due'
      WHEN 'plan_assembly' THEN 'rhythm.plan_assembly'
      ELSE COALESCE(trigger_key, trigger_type)
    END
    WHERE trigger_key IS NULL
  `);

  // Phase 7: workspaces, collaborators, messaging identity
  await pool.query(`
    CREATE TABLE IF NOT EXISTS workspaces (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      join_code TEXT NOT NULL UNIQUE,
      created_by INTEGER REFERENCES users(id),
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );

    CREATE TABLE IF NOT EXISTS workspace_members (
      workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      role TEXT NOT NULL DEFAULT 'staff',
      joined_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      PRIMARY KEY (workspace_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS task_collaborators (
      task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      added_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      PRIMARY KEY (task_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS project_collaborators (
      project_instance_id TEXT NOT NULL REFERENCES project_instances(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      added_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      PRIMARY KEY (project_instance_id, user_id)
    );
  `);

  await pool.query(`ALTER TABLE tasks ADD COLUMN IF NOT EXISTS workspace_id INTEGER REFERENCES workspaces(id)`);
  await pool.query(`ALTER TABLE messages ADD COLUMN IF NOT EXISTS sender_photo_url TEXT`);
  await pool.query(`ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS thread_type TEXT NOT NULL DEFAULT 'direct'`);
  await pool.query(`ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS task_id TEXT REFERENCES tasks(id) ON DELETE SET NULL`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_message_threads_task_id ON message_threads(task_id)`);

  // Phase 8: step assignees + rhythm collaborators
  await pool.query(`ALTER TABLE project_template_steps ADD COLUMN IF NOT EXISTS assignee_id INTEGER REFERENCES users(id) ON DELETE SET NULL`);
  await pool.query(`ALTER TABLE project_instance_steps ADD COLUMN IF NOT EXISTS assignee_id INTEGER REFERENCES users(id) ON DELETE SET NULL`);

  // scheduledDate on project_instance_steps (added with issue #519)
  await pool.query(`ALTER TABLE project_instance_steps ADD COLUMN IF NOT EXISTS scheduled_date TEXT`);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS rhythm_collaborators (
      rhythm_id TEXT NOT NULL REFERENCES recurring_task_rules(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      added_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      PRIMARY KEY (rhythm_id, user_id)
    )
  `);

  // Notifications
  await pool.query(`
    CREATE TABLE IF NOT EXISTS notifications (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      recipient_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      type TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id TEXT NOT NULL,
      message TEXT NOT NULL,
      read_at TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_notifications_recipient
      ON notifications(recipient_user_id, read_at)
  `);

  // Claude collaborator trigger queue.
  // task_id is NULLABLE: human-collaborator triggers carry a task_id, but
  // scheduler / webhook / research triggers are taskless and insert task_id=NULL.
  // UNIQUE(task_id) still de-dups human triggers (Postgres UNIQUE permits multiple NULLs).
  await pool.query(`
    CREATE TABLE IF NOT EXISTS pending_claude_triggers (
      id SERIAL PRIMARY KEY,
      task_id TEXT REFERENCES tasks(id) ON DELETE CASCADE,
      triggered_by_user_id INTEGER REFERENCES users(id),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE(task_id)
    )
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_pending_claude_triggers_created_at ON pending_claude_triggers(created_at)`);

  // tasks.preferred_agent — dual-DB additive column (agent_sessions tables are SQLite-only)
  await pool.query(`ALTER TABLE tasks ADD COLUMN IF NOT EXISTS preferred_agent TEXT`);

  // ── Agent Subsystem: Scheduler, Memory, Webhooks, Research ──────────────

  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_scheduled_tasks (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      schedule_type TEXT NOT NULL DEFAULT 'daily',
      scheduled_time TEXT,
      scheduled_day INTEGER,
      cron_expression TEXT,
      run_at TEXT,
      timezone TEXT NOT NULL DEFAULT 'America/Los_Angeles',
      next_run_at TIMESTAMPTZ,
      prompt TEXT NOT NULL,
      agent_kind TEXT NOT NULL DEFAULT 'opencode',
      allowed_mcps_json TEXT,
      allowed_skills_json TEXT,
      enabled BOOLEAN NOT NULL DEFAULT TRUE,
      last_run_at TIMESTAMPTZ,
      last_run_status TEXT,
      last_error TEXT,
      created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_agent_scheduled_tasks_next_run
      ON agent_scheduled_tasks(next_run_at)
      WHERE enabled = TRUE AND next_run_at IS NOT NULL
  `);

  // Extend pending_claude_triggers with scheduler context columns (additive,
  // all nullable). PROD-OWNED: the cloud role enqueues scheduled triggers into
  // this queue, so these columns and the agent_scheduled_tasks table above must
  // exist in every postgres deployment regardless of RHYTHM_ROLE. Moved here
  // (ahead of the role gate) so they are never skipped in the cloud role.
  await pool.query(`
    ALTER TABLE pending_claude_triggers ADD COLUMN IF NOT EXISTS scheduled_task_id TEXT REFERENCES agent_scheduled_tasks(id) ON DELETE CASCADE;
    ALTER TABLE pending_claude_triggers ADD COLUMN IF NOT EXISTS prompt TEXT;
    ALTER TABLE pending_claude_triggers ADD COLUMN IF NOT EXISTS allowed_mcps_json TEXT;
    ALTER TABLE pending_claude_triggers ADD COLUMN IF NOT EXISTS allowed_skills_json TEXT;
    ALTER TABLE pending_claude_triggers ADD COLUMN IF NOT EXISTS model_provider TEXT;
    ALTER TABLE pending_claude_triggers ADD COLUMN IF NOT EXISTS model_id TEXT;
    ALTER TABLE pending_claude_triggers ADD COLUMN IF NOT EXISTS webhook_endpoint_id TEXT;
    -- Drop the legacy NOT NULL on task_id for EXISTING deployments so taskless
    -- (scheduler/webhook/research) triggers can insert task_id=NULL. Idempotent:
    -- DROP NOT NULL is a no-op when the column is already nullable.
    ALTER TABLE pending_claude_triggers ALTER COLUMN task_id DROP NOT NULL;
  `);

  // Rhythm Agent iOS Task 4 — schema parity for verifier-only pairing data.
  // Pairing remains a local-agent feature, but these additive definitions keep
  // shared repository schema from drifting on Postgres deployments.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS mobile_pairing_codes (
      id TEXT PRIMARY KEY,
      host_id TEXT NOT NULL,
      user_id INTEGER NOT NULL,
      code_verifier TEXT NOT NULL,
      expires_at TEXT NOT NULL,
      consumed_at TEXT,
      created_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS mobile_devices (
      id TEXT PRIMARY KEY,
      host_id TEXT NOT NULL,
      user_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      token_verifier TEXT NOT NULL,
      revoked_at TEXT,
      created_at TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS mobile_opencode_resource_owners (
      resource_kind TEXT NOT NULL
        CHECK (resource_kind IN ('session', 'pty')),
      resource_id TEXT NOT NULL,
      owner_user_id INTEGER NOT NULL
        REFERENCES users(id) ON DELETE CASCADE,
      project_id TEXT NOT NULL,
      created_at TEXT NOT NULL,
      PRIMARY KEY (resource_kind, resource_id)
    );

    CREATE INDEX IF NOT EXISTS idx_mobile_opencode_resource_owner
      ON mobile_opencode_resource_owners(
        owner_user_id,
        project_id,
        resource_kind
      );
  `);

  // #1178 — production-owned transcript sharing is mounted in the cloud role,
  // so its schema must be installed before the agent-execution early return.
  // source_session_id remains provenance rather than an FK. The audit table
  // likewise deliberately has no share FK so history survives share deletion.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS shared_transcripts (
      id TEXT PRIMARY KEY,
      snapshot_json JSONB NOT NULL,
      owner_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      recipient_user_ids_json JSONB NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      expires_at TIMESTAMPTZ NOT NULL,
      revoked_at TIMESTAMPTZ,
      source_session_id TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_shared_transcripts_owner_created
      ON shared_transcripts(owner_user_id, created_at);

    CREATE TABLE IF NOT EXISTS share_audit_log (
      id TEXT PRIMARY KEY,
      share_id TEXT NOT NULL,
      actor_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      action TEXT NOT NULL CHECK (action IN ('share', 'view', 'revoke', 'delete')),
      timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS idx_share_audit_log_share_timestamp
      ON share_audit_log(share_id, timestamp);
    ALTER TABLE share_audit_log
      DROP CONSTRAINT IF EXISTS share_audit_log_share_id_fkey;

    CREATE OR REPLACE FUNCTION reject_shared_transcript_snapshot_update()
    RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION 'shared transcript snapshots are immutable';
    END;
    $$;
    DROP TRIGGER IF EXISTS shared_transcripts_snapshot_immutable
      ON shared_transcripts;
    CREATE TRIGGER shared_transcripts_snapshot_immutable
      BEFORE UPDATE OF snapshot_json ON shared_transcripts
      FOR EACH ROW EXECUTE FUNCTION reject_shared_transcript_snapshot_update();

    CREATE OR REPLACE FUNCTION reject_share_audit_delete()
    RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION 'share audit history is append-only';
    END;
    $$;
    DROP TRIGGER IF EXISTS share_audit_log_no_delete ON share_audit_log;
    CREATE TRIGGER share_audit_log_no_delete
      BEFORE DELETE ON share_audit_log
      FOR EACH ROW EXECUTE FUNCTION reject_share_audit_delete();
  `);

  // ── Agent-EXECUTION tables (#755) ──────────────────────────────────────────
  // Created ONLY when the deployment role runs the agent runtime
  // (RHYTHM_ROLE=all|local; the DEFAULT preserves today's behavior). The
  // 'cloud' (hosted production) role omits these — it never stands up agent
  // session/config/memory/skill/webhook/research/cookbook/design tables it
  // never uses. NOTE: the agent_configs / agent_sessions BASE tables are
  // SQLite-only (migrations.ts), so the ALTERs below were already
  // erroring/dead on postgres; gating them also removes that latent bootstrap
  // failure from any future non-cloud postgres deploy.
  if (!env.agentExecutionEnabled) {
    return;
  }

  // #1219 — keep the agent-memory projection schema compatible anywhere the
  // agent-execution role is enabled. The vault remains canonical; these rows
  // are still a derived query index plus an append-only lifecycle ledger.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_memory (
      id TEXT PRIMARY KEY,
      kind TEXT NOT NULL DEFAULT 'fact',
      content TEXT NOT NULL,
      source TEXT,
      source_id TEXT,
      tags_json TEXT NOT NULL DEFAULT '[]',
      status TEXT NOT NULL DEFAULT 'stable',
      stale_after TEXT,
      verified_json TEXT NOT NULL DEFAULT '[]',
      sources_json TEXT NOT NULL DEFAULT '[]',
      generated_by TEXT,
      generated_at TIMESTAMPTZ,
      trust_tier TEXT NOT NULL DEFAULT 'unverified',
      auto_injectable BOOLEAN NOT NULL DEFAULT FALSE,
      search_vector TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('english', content)
      ) STORED,
      owner_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`ALTER TABLE agent_memory ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'stable'`);
  await pool.query(`ALTER TABLE agent_memory ADD COLUMN IF NOT EXISTS stale_after TEXT`);
  await pool.query(`ALTER TABLE agent_memory ADD COLUMN IF NOT EXISTS verified_json TEXT NOT NULL DEFAULT '[]'`);
  await pool.query(`ALTER TABLE agent_memory ADD COLUMN IF NOT EXISTS sources_json TEXT NOT NULL DEFAULT '[]'`);
  await pool.query(`ALTER TABLE agent_memory ADD COLUMN IF NOT EXISTS generated_by TEXT`);
  await pool.query(`ALTER TABLE agent_memory ADD COLUMN IF NOT EXISTS generated_at TIMESTAMPTZ`);
  await pool.query(`ALTER TABLE agent_memory ADD COLUMN IF NOT EXISTS trust_tier TEXT NOT NULL DEFAULT 'unverified'`);
  await pool.query(`ALTER TABLE agent_memory ADD COLUMN IF NOT EXISTS auto_injectable BOOLEAN NOT NULL DEFAULT FALSE`);
  await pool.query(`ALTER TABLE agent_memory ADD COLUMN IF NOT EXISTS search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', content)) STORED`);
  await pool.query(`UPDATE agent_memory SET verified_json = '[]' WHERE verified_json IS NULL`);
  await pool.query(`UPDATE agent_memory SET sources_json = '[]' WHERE sources_json IS NULL`);
  await pool.query(`UPDATE agent_memory SET trust_tier = 'unverified' WHERE trust_tier IS NULL`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_agent_memory_owner ON agent_memory(owner_user_id)`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_agent_memory_kind ON agent_memory(kind)`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_agent_memory_active ON agent_memory(status, stale_after)`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_agent_memory_search ON agent_memory USING GIN(search_vector)`);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_memory_changes (
      id TEXT PRIMARY KEY,
      memory_id TEXT NOT NULL,
      memory_source_id TEXT NOT NULL,
      action TEXT NOT NULL,
      actor TEXT NOT NULL,
      changed_at TIMESTAMPTZ NOT NULL,
      prior_state_json TEXT NOT NULL,
      rollback_target TEXT,
      source_context_json TEXT NOT NULL DEFAULT '{}'
    )
  `);
  await pool.query(`ALTER TABLE agent_memory_changes ADD COLUMN IF NOT EXISTS memory_source_id TEXT`);
  await pool.query(`
    UPDATE agent_memory_changes changes
       SET memory_source_id = memory.source_id
      FROM agent_memory memory
     WHERE changes.memory_source_id IS NULL
       AND memory.id = changes.memory_id
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_agent_memory_changes_memory ON agent_memory_changes(memory_id, changed_at)`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_agent_memory_changes_source ON agent_memory_changes(memory_source_id, changed_at)`);
  await pool.query(`
    CREATE OR REPLACE FUNCTION guard_agent_memory_changes()
    RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'agent_memory_changes is append-only';
      END IF;
      IF NEW.rollback_target IS NOT NULL AND NOT EXISTS (
        SELECT 1
          FROM agent_memory_changes target
         WHERE target.id = NEW.rollback_target
           AND target.memory_source_id = NEW.memory_source_id
      ) THEN
        RAISE EXCEPTION
          'rollback_target must reference the same memory_source_id';
      END IF;
      RETURN NEW;
    END;
    $$;
    DROP TRIGGER IF EXISTS agent_memory_changes_append_only
      ON agent_memory_changes;
    CREATE TRIGGER agent_memory_changes_append_only
      BEFORE INSERT OR UPDATE OR DELETE ON agent_memory_changes
      FOR EACH ROW EXECUTE FUNCTION guard_agent_memory_changes();
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_webhook_endpoints (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      event_types_json TEXT NOT NULL DEFAULT '["*"]',
      secret TEXT NOT NULL,
      target_scheduled_task_id TEXT REFERENCES agent_scheduled_tasks(id) ON DELETE SET NULL,
      target_prompt TEXT,
      enabled BOOLEAN NOT NULL DEFAULT TRUE,
      last_triggered_at TIMESTAMPTZ,
      trigger_count INTEGER NOT NULL DEFAULT 0,
      created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_research_jobs (
      id TEXT PRIMARY KEY,
      query TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      sources_json TEXT NOT NULL DEFAULT '[]',
      report TEXT,
      error TEXT,
      agent_session_id TEXT,
      research_type TEXT NOT NULL DEFAULT 'generic',
      title TEXT,
      agent_profile_id TEXT,
      origin TEXT NOT NULL DEFAULT 'page',
      vault_path TEXT,
      requested_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`ALTER TABLE agent_research_jobs ADD COLUMN IF NOT EXISTS agent_session_id TEXT`);
  await pool.query(`ALTER TABLE agent_research_jobs ADD COLUMN IF NOT EXISTS research_type TEXT NOT NULL DEFAULT 'generic'`);
  await pool.query(`ALTER TABLE agent_research_jobs ADD COLUMN IF NOT EXISTS title TEXT`);
  await pool.query(`ALTER TABLE agent_research_jobs ADD COLUMN IF NOT EXISTS agent_profile_id TEXT`);
  await pool.query(`ALTER TABLE agent_research_jobs ADD COLUMN IF NOT EXISTS origin TEXT NOT NULL DEFAULT 'page'`);
  await pool.query(`ALTER TABLE agent_research_jobs ADD COLUMN IF NOT EXISTS vault_path TEXT`);
  await pool.query(`UPDATE agent_research_jobs SET research_type = 'generic', title = query, agent_profile_id = 'research', origin = 'page' WHERE research_type IS NULL OR title IS NULL OR agent_profile_id IS NULL OR origin IS NULL`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_agent_research_jobs_status ON agent_research_jobs(status)`);
  await pool.query(`CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_research_jobs_agent_session_id ON agent_research_jobs(agent_session_id) WHERE agent_session_id IS NOT NULL`);

  // B1 — agent_cookbook: reusable recipe/skill library for the agent scheduler.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_cookbook (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      description TEXT,
      steps_json TEXT NOT NULL DEFAULT '[]',
      bound_config_id TEXT,
      owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_agent_cookbook_created_at ON agent_cookbook(created_at)`,
  );

  // D1 — agent_designs: provider-neutral finished creative-media artifacts.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_designs (
      id TEXT PRIMARY KEY,
      title TEXT,
      provider TEXT,
      artifact_url TEXT,
      project_url TEXT,
      canva_url TEXT,
      artifact_type TEXT,
      file_path TEXT,
      thumbnail_url TEXT,
      session_id TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`ALTER TABLE agent_designs ADD COLUMN IF NOT EXISTS artifact_type TEXT`);
  await pool.query(`ALTER TABLE agent_designs ADD COLUMN IF NOT EXISTS file_path TEXT`);
  await pool.query(`ALTER TABLE agent_designs ADD COLUMN IF NOT EXISTS provider TEXT`);
  await pool.query(`ALTER TABLE agent_designs ADD COLUMN IF NOT EXISTS artifact_url TEXT`);
  await pool.query(`ALTER TABLE agent_designs ADD COLUMN IF NOT EXISTS project_url TEXT`);
  await pool.query(`UPDATE agent_designs SET project_url = canva_url, provider = COALESCE(provider, 'canva') WHERE canva_url IS NOT NULL AND project_url IS NULL`);
  await pool.query(`UPDATE agent_designs SET provider = 'local' WHERE file_path IS NOT NULL AND provider IS NULL`);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_agent_designs_created_at ON agent_designs(created_at)`,
  );

  // P1-1 — agent_skills: shared, instance-wide self-improving skill library.
  // Skills are SHARED across all agents — there is intentionally NO owner_user_id.
  // steps_json / tags_json hold JSON string arrays.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_skills (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      when_to_use TEXT,
      description TEXT,
      steps_json TEXT,
      tags_json TEXT,
      confidence REAL DEFAULT 0,
      status TEXT DEFAULT 'draft',
      source TEXT,
      uses INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_agent_skills_title ON agent_skills(title)`,
  );
  // body TEXT (additive) — full markdown procedure body for prose/seed skills.
  // Nullable; extracted skills using steps_json leave it null.
  await pool.query(`ALTER TABLE agent_skills ADD COLUMN IF NOT EXISTS body TEXT`);
  // P5-1 — version INTEGER (additive). Current version of the live row; bumped
  // by reviseInPlace/rollback. Default 1 so existing rows start versioned.
  await pool.query(
    `ALTER TABLE agent_skills ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1`,
  );

  // #792 (skill-unify2) — repurpose agent_skills as a name-keyed metadata
  // SIDECAR + measurement LEDGER over the engine's filesystem skills, for the
  // auto-apply → measure → auto-revert self-improvement model. NO human gate:
  // `status` carries the data-only lifecycle 'active' / 'measuring' / 'reverted'
  // (no proposed/approved/rejected). All columns additive + nullable. These MUST
  // stay column-for-column identical to the SQLite migration (skill_schema_parity
  // test enforces). See migrations.ts for per-column semantics.
  await pool.query(`
    ALTER TABLE agent_skills ADD COLUMN IF NOT EXISTS applied_for_name TEXT;
    ALTER TABLE agent_skills ADD COLUMN IF NOT EXISTS base_version INTEGER;
    ALTER TABLE agent_skills ADD COLUMN IF NOT EXISTS origin_location TEXT;
    ALTER TABLE agent_skills ADD COLUMN IF NOT EXISTS is_external INTEGER DEFAULT 0;
    ALTER TABLE agent_skills ADD COLUMN IF NOT EXISTS baseline_score INTEGER;
    ALTER TABLE agent_skills ADD COLUMN IF NOT EXISTS post_score INTEGER;
    ALTER TABLE agent_skills ADD COLUMN IF NOT EXISTS measure_reason TEXT;
  `);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_agent_skills_applied_for_name ON agent_skills(applied_for_name)`,
  );

  // P5-1 — agent_skill_versions: append-only version history for self-refinement.
  // Each row snapshots a prior (or restored) state of an agent_skills row so the
  // auto-apply refinement loop is non-destructive with one-click rollback.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_skill_versions (
      id TEXT PRIMARY KEY,
      skill_id TEXT NOT NULL REFERENCES agent_skills(id) ON DELETE CASCADE,
      version_no INTEGER NOT NULL,
      title TEXT NOT NULL,
      when_to_use TEXT,
      description TEXT,
      steps_json TEXT,
      tags_json TEXT,
      body TEXT,
      confidence REAL DEFAULT 0,
      source TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_agent_skill_versions_skill_id ON agent_skill_versions(skill_id)`,
  );

  // #1113 (Discovery-005) — agent_capability_gaps: this table was previously
  // missing from the Postgres path entirely (same missing-CREATE drift class
  // as agent_configs/agent_sessions below); AgentCapabilityGapsRepository
  // silently fell back to a throwaway in-memory SQLite DB under Postgres, so
  // every gap vanished per-instance. Column set MUST stay identical to the
  // SQLite migration (migrations.ts) — enforced by skill_schema_parity.test.ts.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_capability_gaps (
      id                TEXT PRIMARY KEY,
      dedup_key         TEXT NOT NULL UNIQUE,
      intent_title      TEXT NOT NULL,
      intent_problem    TEXT,
      intent_tags_json  TEXT,
      sample_session_id TEXT,
      agent_config_id   TEXT,
      status            TEXT NOT NULL DEFAULT 'open',
      created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_agent_capability_gaps_status ON agent_capability_gaps(status)`,
  );

  // proposals-parity fix (#1113 sibling) — agent_org_proposals: the org
  // self-optimizer's proposal store + lifecycle state machine. Previously
  // missing from the Postgres path entirely per a now-reversed decision
  // (docs/ai/decisions/2026-06-29-org-self-optimizer-cron.md §5 — "proposals
  // are local-only, never synced to production"); that assumption predates
  // #1111/#1113 making the optimizer's own seed run on a Postgres-backed
  // deployment (role-gated, not engine-gated — see org_optimizer_seed.ts), so
  // the optimizer now genuinely writes proposals against Postgres-backed
  // prod. Without this table AgentOrgProposalsRepository fell back to the
  // same throwaway in-memory SQLite DB #1113 fixed for agent_capability_gaps
  // — every proposal vanished per-instance. Column set MUST stay identical to
  // the SQLite migration (migrations.ts) — enforced by skill_schema_parity.test.ts.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_org_proposals (
      id            TEXT PRIMARY KEY,
      audit_run_id  TEXT,
      kind          TEXT NOT NULL,
      risk          TEXT NOT NULL,
      external      INTEGER DEFAULT 0,
      status        TEXT NOT NULL DEFAULT 'proposed',
      title         TEXT NOT NULL,
      rationale     TEXT,
      signal_ref    TEXT,
      target_ref    TEXT,
      change_json   TEXT,
      before_snapshot_json TEXT,
      provenance_json TEXT,
      dedup_key     TEXT,
      baseline_score INTEGER,
      post_score     INTEGER,
      measure_reason TEXT,
      decided_by_user_id INTEGER,
      owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_org_proposals_status ON agent_org_proposals(status)`,
  );
  await pool.query(
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_org_proposals_dedup ON agent_org_proposals(dedup_key)`,
  );

  // #1053 (OCU-12) — org_skills: matching table for the production org skill
  // library (see migrations.ts for the full rationale — public reads, authed
  // writes, single-file SKILL.md-only model for now). Column set MUST stay
  // identical to the SQLite migration — enforced by skill_schema_parity.test.ts.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS org_skills (
      name        TEXT PRIMARY KEY,
      description TEXT,
      content     TEXT NOT NULL,
      published   BOOLEAN NOT NULL DEFAULT TRUE,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_org_skills_published ON org_skills(published)`,
  );

  // #1072 (OCU-31) — org_settings: a single org-wide instructions markdown
  // (see migrations.ts for the full rationale — public read, authed write,
  // singleton row keyed by a fixed id). MANUAL-REVIEW FLAG (AGENTS.md
  // production posture): this is the ONLY prod-schema change in the
  // #1042-1108 mega-PR — purely additive (a brand-new table, no ALTER on an
  // existing one, no data migration), zero destructive-migration risk.
  // Column set MUST stay identical to the SQLite migration.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS org_settings (
      id         TEXT PRIMARY KEY,
      content    TEXT NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  // agent_configs — user-configurable list of CLI agents (issue #481 / #466).
  // NOTE: this CREATE was previously missing from the Postgres path; only the SQLite
  // migrations.ts created it, while the ALTERs below assumed it existed. On a Postgres
  // deploy that never had the table, `ALTER TABLE agent_configs ...` threw 42P01 and
  // crash-looped boot (ADD COLUMN IF NOT EXISTS does not guard a missing *table*).
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_configs (
      id TEXT PRIMARY KEY,
      label TEXT NOT NULL,
      icon TEXT NOT NULL,
      command TEXT NOT NULL,
      enabled INTEGER NOT NULL DEFAULT 1,
      is_agent INTEGER NOT NULL DEFAULT 1,
      can_resume INTEGER NOT NULL DEFAULT 0,
      resume_command TEXT,
      session_id_pattern TEXT,
      output_marker TEXT,
      preset_id TEXT,
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_agent_configs_enabled ON agent_configs(enabled)`,
  );

  // Seed built-in preset rows (ON CONFLICT keeps bootstrap idempotent).
  await pool.query(`
    INSERT INTO agent_configs
      (id, label, icon, command, is_agent, can_resume, resume_command, session_id_pattern, output_marker, preset_id, sort_order)
    VALUES
      ('claude-code', 'Claude Code', 'assets/agents/claude-code.png', 'claude', 1, 1, 'claude --resume {{sessionId}}', 'Session ID:\\s+([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})', '⏺', 'claude-code', 0),
      ('codex', 'Codex', 'assets/agents/codex.png', 'codex', 1, 0, NULL, NULL, '•', 'codex', 1),
      ('gemini-cli', 'Gemini CLI', 'assets/agents/gemini-cli.png', 'gemini', 1, 0, NULL, NULL, '✦', 'gemini-cli', 2),
      ('opencode', 'OpenCode', 'assets/agents/opencode.png', 'opencode', 1, 0, NULL, NULL, '│', 'opencode', 3)
    ON CONFLICT (id) DO NOTHING;
  `);

  // agent_sessions — agent run records. Same missing-CREATE bug as agent_configs above:
  // only migrations.ts (SQLite) created it, while the ALTERs further down assumed it existed.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_sessions (
      id TEXT PRIMARY KEY,
      task_id TEXT REFERENCES tasks(id) ON DELETE SET NULL,
      agent_kind TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'starting',
      session_token TEXT,
      cwd TEXT NOT NULL,
      name TEXT NOT NULL,
      last_preview TEXT,
      last_activity_at TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  // Agent-runner model selection: store preferred provider/model on agent_configs.
  await pool.query(`
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS model_provider TEXT;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS model_id TEXT;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS oc_agent TEXT;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS session_selectable BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS is_manager INTEGER NOT NULL DEFAULT 0;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS system_prompt TEXT;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS allowed_mcps_json TEXT;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS allowed_skills_json TEXT;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS core_permissions_json TEXT;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS allowed_delegates_json TEXT;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS locked INTEGER NOT NULL DEFAULT 0;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS disabled_reason TEXT;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS locked_at TIMESTAMPTZ;
    ALTER TABLE agent_configs ADD COLUMN IF NOT EXISTS locked_by TEXT;
  `);
  // #1135 — append-only application audit log for security lock/reviewed
  // re-enable transitions. Deliberately no cascading FK: deleting a profile
  // must not erase its security evidence.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_config_security_events (
      id              TEXT PRIMARY KEY,
      agent_config_id TEXT NOT NULL,
      event_type      TEXT NOT NULL CHECK (event_type IN ('locked', 'reviewed_reenabled')),
      actor           TEXT NOT NULL,
      reason          TEXT NOT NULL,
      review_note     TEXT,
      lock_version    TIMESTAMPTZ NOT NULL,
      created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_agent_config_security_events_profile
      ON agent_config_security_events(agent_config_id, created_at)
  `);

  // agent_config_id: logical FK from scheduled tasks to agent_configs.id.
  await pool.query(`
    ALTER TABLE agent_scheduled_tasks ADD COLUMN IF NOT EXISTS agent_config_id TEXT;
  `);

  // Per-task model override (the model-override change): nullable provider/model that, when
  // both set, override the bound profile's model for that scheduled run.
  await pool.query(`
    ALTER TABLE agent_scheduled_tasks ADD COLUMN IF NOT EXISTS model_provider TEXT;
    ALTER TABLE agent_scheduled_tasks ADD COLUMN IF NOT EXISTS model_id TEXT;
  `);

  // #738-fix — agent_sessions.scheduled_task_id: FK to agent_scheduled_tasks.id.
  await pool.query(`
    ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS scheduled_task_id TEXT REFERENCES agent_scheduled_tasks(id) ON DELETE SET NULL;
  `);

  // #743 — agent_sessions.parent_session_id: delegated subagent (child) sessions.
  await pool.query(`
    ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS parent_session_id TEXT REFERENCES agent_sessions(id) ON DELETE SET NULL;
  `);

  // #747 — agent_sessions.is_system: background/system sessions excluded from normal session list.
  await pool.query(`
    ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS is_system INTEGER NOT NULL DEFAULT 0;
    ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
    ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS delegation_depth INTEGER NOT NULL DEFAULT 0;
    ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS status_message TEXT;
    -- projects is intentionally SQLite/local-only; Postgres stores its id as a logical reference.
    ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS project_id TEXT;
    ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS mcp_role TEXT;
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_agent_sessions_is_system ON agent_sessions(is_system);
  `);

  // #1175 — Activity schema + owner-index parity. All changes are additive and
  // idempotent for active Postgres deployments. NULL recipe/proposal owners are
  // organization/system-global and excluded from authenticated mobile feeds;
  // only the trusted local desktop global view may include them.
  await pool.query(`
    ALTER TABLE agent_cookbook
      ADD COLUMN IF NOT EXISTS owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
    ALTER TABLE agent_org_proposals
      ADD COLUMN IF NOT EXISTS owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_agent_sessions_owner_activity
      ON agent_sessions(owner_user_id, last_activity_at, updated_at);
    CREATE INDEX IF NOT EXISTS idx_agent_scheduled_tasks_owner_activity
      ON agent_scheduled_tasks(created_by_user_id, last_run_at);
    CREATE INDEX IF NOT EXISTS idx_agent_webhook_endpoints_owner_activity
      ON agent_webhook_endpoints(created_by_user_id, last_triggered_at);
    CREATE INDEX IF NOT EXISTS idx_agent_research_jobs_owner_activity
      ON agent_research_jobs(requested_by_user_id, updated_at);
    CREATE INDEX IF NOT EXISTS idx_agent_cookbook_owner_activity
      ON agent_cookbook(owner_user_id, updated_at);
    CREATE INDEX IF NOT EXISTS idx_agent_org_proposals_owner_activity
      ON agent_org_proposals(owner_user_id, updated_at);
  `);

  // #1028 (USO B1) — agent_sessions.category: session classification driving the
  // USO scope filters (chat / scheduled / self_improvement). New rows are stamped
  // at insert; legacy rows are backfilled (scheduled_task_id NOT NULL → 'scheduled').
  // The backfill is guarded on category = 'chat' so it converges and re-running
  // the bootstrap is a no-op.
  await pool.query(`
    ALTER TABLE agent_sessions ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'chat';
  `);
  await pool.query(`
    UPDATE agent_sessions SET category = 'scheduled' WHERE scheduled_task_id IS NOT NULL AND category = 'chat';
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_agent_sessions_category ON agent_sessions(category);
  `);

  // #1123 — durable completion/outbox state for interactive async delegation.
  // Additive only; no existing rows need backfill because pre-#1123 child
  // sessions all belong to the native blocking `task` path.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS agent_async_delegations (
      id TEXT PRIMARY KEY,
      parent_session_id TEXT NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
      child_session_id TEXT NOT NULL UNIQUE REFERENCES agent_sessions(id) ON DELETE CASCADE,
      target_agent_config_id TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'dispatched'
        CHECK (status IN ('dispatched', 'completed', 'waking', 'notified', 'failed')),
      completion_text TEXT,
      error_text TEXT,
      completed_at TEXT,
      notified_at TEXT,
      created_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW}),
      updated_at TEXT NOT NULL DEFAULT (${UTC_TEXT_NOW})
    );
    CREATE INDEX IF NOT EXISTS idx_agent_async_delegations_parent_status
      ON agent_async_delegations(parent_session_id, status, created_at);
  `);

  // One-time repair, marker-guarded (schema_meta) — same contract as the
  // SQLite twin in migrations.ts ('nonmanager_delegates_wipe_v1'): this
  // bootstrap runs on EVERY boot, so an unguarded content UPDATE here
  // re-stomps user edits on every restart. Content repairs must be
  // one-time; only structural statements may run unguarded.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS schema_meta (
      key TEXT PRIMARY KEY,
      value TEXT
    );
  `);
  const wipeMarker = await pool.query(
    `SELECT key FROM schema_meta WHERE key = 'nonmanager_delegates_wipe_v1'`,
  );
  if ((wipeMarker.rowCount ?? 0) === 0) {
    await pool.query(`
      UPDATE agent_configs
         SET allowed_delegates_json = NULL
       WHERE id IN ('worship-planning', 'theologian')
         AND COALESCE(is_manager, 0) = 0
         AND allowed_delegates_json IS NOT NULL;
    `);
    await pool.query(
      `INSERT INTO schema_meta (key, value) VALUES ('nonmanager_delegates_wipe_v1', $1)
       ON CONFLICT (key) DO NOTHING`,
      [new Date().toISOString()],
    );
  }

  // #1138 follow-up — one-time repair of legacy numbered-key
  // core_permissions_json rows, marker-guarded (schema_meta) with the SAME
  // key as the SQLite twin in migrations.ts
  // ('numbered_core_permissions_repair_v1') per the postgres/sqlite schema
  // drift pattern. Data repair only — flat/hand-repaired/garbage rows are
  // left untouched by the shared converter (returns undefined).
  const numberedPermsMarker = await pool.query(
    `SELECT key FROM schema_meta WHERE key = 'numbered_core_permissions_repair_v1'`,
  );
  if ((numberedPermsMarker.rowCount ?? 0) === 0) {
    const permRows = await pool.query(
      `SELECT id, core_permissions_json FROM agent_configs WHERE core_permissions_json IS NOT NULL`,
    );
    for (const row of permRows.rows as { id: string; core_permissions_json: string }[]) {
      const repaired = convertLegacyNumberedCorePermissions(row.core_permissions_json);
      if (repaired === undefined) continue;
      await pool.query(
        `UPDATE agent_configs
            SET core_permissions_json = $1
          WHERE id = $2
            AND core_permissions_json = $3`,
        [repaired, row.id, row.core_permissions_json],
      );
    }
    await pool.query(
      `INSERT INTO schema_meta (key, value) VALUES ('numbered_core_permissions_repair_v1', $1)
       ON CONFLICT (key) DO NOTHING`,
      [new Date().toISOString()],
    );
  }
}
