import { randomUUID } from 'node:crypto';
import { env } from '../config/env';
import { getDb, getPostgresPool } from '../database/db';
import type { LiveArtifact, LiveArtifactVisibility } from '../models/live_artifact';

type Row = { id: string; type: 'html'; title: string; owner_user_id: number; workspace_id: number; visibility: LiveArtifactVisibility; current_bundle_revision: number; current_bundle_hash: string; current_state_revision: number; current_state_hash: string; declared_capabilities_json: string | string[]; created_at: string | Date; updated_at: string | Date; updated_by_user_id: number; updated_by_display_name?: string | null; deleted_at: string | Date | null };
const iso = (value: string | Date) => value instanceof Date ? value.toISOString() : value;
const map = (row: Row): LiveArtifact => ({ id: row.id, type: row.type, title: row.title, ownerUserId: row.owner_user_id, workspaceId: row.workspace_id, visibility: row.visibility, currentBundleRevision: row.current_bundle_revision, currentBundleHash: row.current_bundle_hash, currentStateRevision: row.current_state_revision, currentStateHash: row.current_state_hash, declaredCapabilities: typeof row.declared_capabilities_json === 'string' ? JSON.parse(row.declared_capabilities_json) : row.declared_capabilities_json, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at), updatedByUserId: row.updated_by_user_id, updatedByDisplayName: row.updated_by_display_name ?? null, deletedAt: row.deleted_at ? iso(row.deleted_at) : null });
const selectArtifact = 'SELECT live_artifacts.*, users.name AS updated_by_display_name FROM live_artifacts LEFT JOIN users ON users.id = live_artifacts.updated_by_user_id';

export class LiveArtifactsRepository {
  async isWorkspaceMember(workspaceId: number, userId: number): Promise<boolean> {
    const row = env.dbClient === 'postgres' ? (await getPostgresPool().query('SELECT 1 FROM workspace_members WHERE workspace_id = $1 AND user_id = $2', [workspaceId, userId])).rows[0] : getDb().prepare('SELECT 1 FROM workspace_members WHERE workspace_id = ? AND user_id = ?').get(workspaceId, userId);
    return !!row;
  }
  async find(id: string): Promise<LiveArtifact | null> { const row = env.dbClient === 'postgres' ? (await getPostgresPool().query<Row>(`${selectArtifact} WHERE live_artifacts.id = $1`, [id])).rows[0] : getDb().prepare(`${selectArtifact} WHERE live_artifacts.id = ?`).get(id) as Row | undefined; return row ? map(row) : null; }
  async canRead(artifact: LiveArtifact, userId: number): Promise<boolean> {
    if (artifact.ownerUserId === userId) return true;
    if (artifact.visibility === 'organization') return this.isWorkspaceMember(artifact.workspaceId, userId);
    if (artifact.visibility !== 'shared') return false;
    // ponytail: two queries per artifact in list(); fold into one JOIN if list latency matters.
    if (!await this.isWorkspaceMember(artifact.workspaceId, userId)) return false;
    const row = env.dbClient === 'postgres' ? (await getPostgresPool().query('SELECT 1 FROM live_artifact_collaborators WHERE artifact_id = $1 AND user_id = $2', [artifact.id, userId])).rows[0] : getDb().prepare('SELECT 1 FROM live_artifact_collaborators WHERE artifact_id = ? AND user_id = ?').get(artifact.id, userId);
    return !!row;
  }
  async list(userId: number, search?: string): Promise<LiveArtifact[]> {
    const all = env.dbClient === 'postgres' ? (await getPostgresPool().query<Row>(`${selectArtifact} WHERE live_artifacts.deleted_at IS NULL ORDER BY live_artifacts.updated_at DESC`)).rows.map(map) : (getDb().prepare(`${selectArtifact} WHERE live_artifacts.deleted_at IS NULL ORDER BY live_artifacts.updated_at DESC`).all() as Row[]).map(map);
    const visible = await Promise.all(all.map(async (artifact) => (await this.canRead(artifact, userId)) ? artifact : null));
    return visible.filter((artifact): artifact is LiveArtifact => !!artifact && (!search || artifact.title.toLowerCase().includes(search.toLowerCase())));
  }
  async create(input: Omit<LiveArtifact, 'createdAt' | 'updatedAt' | 'deletedAt'>, collaboratorIds: number[] = []): Promise<LiveArtifact> {
    const now = new Date().toISOString(); const capabilities = JSON.stringify(input.declaredCapabilities);
    if (env.dbClient === 'postgres') { const client = await getPostgresPool().connect(); try { await client.query('BEGIN'); const result = await client.query<Row>('INSERT INTO live_artifacts (id,type,title,owner_user_id,workspace_id,visibility,current_bundle_revision,current_bundle_hash,current_state_revision,current_state_hash,declared_capabilities_json,created_at,updated_at,updated_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$12,$4) RETURNING *', [input.id, input.type, input.title, input.ownerUserId, input.workspaceId, input.visibility, input.currentBundleRevision, input.currentBundleHash, input.currentStateRevision, input.currentStateHash, capabilities, now]); await client.query('INSERT INTO live_artifact_bundle_revisions (artifact_id,revision,hash,actor_user_id,created_at) VALUES ($1,$2,$3,$4,$5)', [input.id,1,input.currentBundleHash,input.ownerUserId,now]); await client.query('INSERT INTO live_artifact_state_revisions (artifact_id,revision,hash,actor_user_id,created_at) VALUES ($1,$2,$3,$4,$5)', [input.id,1,input.currentStateHash,input.ownerUserId,now]); for (const userId of collaboratorIds) await client.query('INSERT INTO live_artifact_collaborators (artifact_id,user_id,added_at,added_by_user_id) VALUES ($1,$2,$3,$4)', [input.id,userId,now,input.ownerUserId]); await client.query('COMMIT'); return map(result.rows[0]); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
    const db = getDb(); db.transaction(() => { db.prepare('INSERT INTO live_artifacts (id,type,title,owner_user_id,workspace_id,visibility,current_bundle_revision,current_bundle_hash,current_state_revision,current_state_hash,declared_capabilities_json,created_at,updated_at,updated_by_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(input.id,input.type,input.title,input.ownerUserId,input.workspaceId,input.visibility,1,input.currentBundleHash,1,input.currentStateHash,capabilities,now,now,input.ownerUserId); db.prepare('INSERT INTO live_artifact_bundle_revisions (artifact_id,revision,hash,actor_user_id,created_at) VALUES (?,?,?,?,?)').run(input.id,1,input.currentBundleHash,input.ownerUserId,now); db.prepare('INSERT INTO live_artifact_state_revisions (artifact_id,revision,hash,actor_user_id,created_at) VALUES (?,?,?,?,?)').run(input.id,1,input.currentStateHash,input.ownerUserId,now); for (const userId of collaboratorIds) db.prepare('INSERT INTO live_artifact_collaborators (artifact_id,user_id,added_at,added_by_user_id) VALUES (?,?,?,?)').run(input.id,userId,now,input.ownerUserId); })(); return (await this.find(input.id))!;
  }
  async updateContent(id: string, kind: 'bundle' | 'state', expected: number, contentHash: string, actor: number): Promise<LiveArtifact | null> {
    const current = `current_${kind}_revision`; const now = new Date().toISOString();
    if (env.dbClient === 'postgres') { const pool = getPostgresPool(); const client = await pool.connect(); try { await client.query('BEGIN'); const result = await client.query<Row>(`UPDATE live_artifacts SET ${current} = ${current} + 1, current_${kind}_hash = $1, updated_at = $2, updated_by_user_id = $3 WHERE id = $4 AND deleted_at IS NULL AND ${current} = $5 RETURNING *`, [contentHash,now,actor,id,expected]); if (!result.rows[0]) { await client.query('ROLLBACK'); return null; } const artifact = map(result.rows[0]); await client.query(`INSERT INTO live_artifact_${kind}_revisions (artifact_id,revision,hash,actor_user_id,created_at) VALUES ($1,$2,$3,$4,$5)`,[id, artifact[kind === 'bundle' ? 'currentBundleRevision' : 'currentStateRevision'],contentHash,actor,now]); await client.query('COMMIT'); return artifact; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
    const db = getDb(); return db.transaction(() => { const result = db.prepare(`UPDATE live_artifacts SET ${current} = ${current} + 1, current_${kind}_hash = ?, updated_at = ?, updated_by_user_id = ? WHERE id = ? AND deleted_at IS NULL AND ${current} = ?`).run(contentHash,now,actor,id,expected); if (!result.changes) return null; const artifact = map(db.prepare('SELECT * FROM live_artifacts WHERE id = ?').get(id) as Row); db.prepare(`INSERT INTO live_artifact_${kind}_revisions (artifact_id,revision,hash,actor_user_id,created_at) VALUES (?,?,?,?,?)`).run(id,kind === 'bundle' ? artifact.currentBundleRevision : artifact.currentStateRevision,contentHash,actor,now); return artifact; })();
  }
  async metadata(id: string, title: string | undefined, visibility: LiveArtifactVisibility | undefined, capabilities: string[] | undefined, actor: number): Promise<LiveArtifact> { const now = new Date().toISOString(); const current = await this.find(id); if (!current) throw new Error('missing'); const next = { title: title ?? current.title, visibility: visibility ?? current.visibility, capabilities: capabilities ?? current.declaredCapabilities }; if (env.dbClient === 'postgres') { const r = await getPostgresPool().query<Row>('UPDATE live_artifacts SET title=$1,visibility=$2,declared_capabilities_json=$3::jsonb,updated_at=$4,updated_by_user_id=$5 WHERE id=$6 RETURNING *',[next.title,next.visibility,JSON.stringify(next.capabilities),now,actor,id]); return map(r.rows[0]); } getDb().prepare('UPDATE live_artifacts SET title=?,visibility=?,declared_capabilities_json=?,updated_at=?,updated_by_user_id=? WHERE id=?').run(next.title,next.visibility,JSON.stringify(next.capabilities),now,actor,id); return (await this.find(id))!; }
  async collaborators(id: string): Promise<number[]> { const rows = env.dbClient === 'postgres' ? (await getPostgresPool().query<{user_id:number}>('SELECT user_id FROM live_artifact_collaborators WHERE artifact_id=$1',[id])).rows : getDb().prepare('SELECT user_id FROM live_artifact_collaborators WHERE artifact_id=?').all(id) as {user_id:number}[]; return rows.map((r) => r.user_id); }
  async addCollaborator(id: string, userId: number, actor: number): Promise<void> { const now = new Date().toISOString(); if (env.dbClient === 'postgres') { await getPostgresPool().query('INSERT INTO live_artifact_collaborators (artifact_id,user_id,added_at,added_by_user_id) VALUES ($1,$2,$3,$4) ON CONFLICT DO NOTHING',[id,userId,now,actor]); } else getDb().prepare('INSERT OR IGNORE INTO live_artifact_collaborators (artifact_id,user_id,added_at,added_by_user_id) VALUES (?,?,?,?)').run(id,userId,now,actor); }
  async removeCollaborator(id: string, userId: number): Promise<void> { if (env.dbClient === 'postgres') await getPostgresPool().query('DELETE FROM live_artifact_collaborators WHERE artifact_id=$1 AND user_id=$2',[id,userId]); else getDb().prepare('DELETE FROM live_artifact_collaborators WHERE artifact_id=? AND user_id=?').run(id,userId); }
  async softDelete(id: string, actor: number): Promise<void> { const now = new Date().toISOString(); if (env.dbClient === 'postgres') await getPostgresPool().query('UPDATE live_artifacts SET deleted_at=$1,deleted_by_user_id=$2 WHERE id=$3 AND deleted_at IS NULL',[now,actor,id]); else getDb().prepare('UPDATE live_artifacts SET deleted_at=?,deleted_by_user_id=? WHERE id=? AND deleted_at IS NULL').run(now,actor,id); }
  newId() { return randomUUID(); }
}
