import { execFile } from 'node:child_process';
import { cp, mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const run = promisify(execFile);
const electronRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceApp = resolve(electronRoot, 'node_modules/electron/dist/Electron.app');
const distRoot = resolve(electronRoot, 'dist');
const artifact = resolve(distRoot, 'Rhythm.app');
const stagingArtifact = resolve(distRoot, '.Rhythm.app.tmp');
const resources = resolve(stagingArtifact, 'Contents/Resources');
const packagedApp = resolve(resources, 'app');
const infoPlist = resolve(stagingArtifact, 'Contents/Info.plist');
const rendererBuildEnvironment = { ...process.env };
// TEST-ONLY: Vite gateway values remain supported by `npm run dev` and Playwright. A shipping
// renderer must start from a neutral environment, then receive only the non-secret live-mode
// invariant; caller-supplied bases and tokens must never become artifact bytes.
for (const key of [
  'VITE_RHYTHM_GATEWAY_MODE',
  'VITE_RHYTHM_API_BASE',
  'VITE_RHYTHM_ENGINE_BASE',
  'VITE_RHYTHM_LIVE_TOKEN',
]) delete rendererBuildEnvironment[key];
rendererBuildEnvironment.VITE_RHYTHM_GATEWAY_MODE = 'live';

await run('npm', ['--prefix', '../web', 'run', 'build'], {
  cwd: electronRoot,
  env: rendererBuildEnvironment,
});
await mkdir(distRoot, { recursive: true });
await Promise.all([
  rm(artifact, { recursive: true, force: true }),
  rm(stagingArtifact, { recursive: true, force: true }),
]);
await cp(sourceApp, stagingArtifact, { recursive: true, verbatimSymlinks: true });
await mkdir(resolve(packagedApp, 'src'), { recursive: true });
await Promise.all([
  cp(resolve(electronRoot, 'src/main.mjs'), resolve(packagedApp, 'src/main.mjs')),
  cp(resolve(electronRoot, 'src/policy.mjs'), resolve(packagedApp, 'src/policy.mjs')),
  cp(resolve(electronRoot, 'src/production-api-config.mjs'), resolve(packagedApp, 'src/production-api-config.mjs')),
  cp(resolve(electronRoot, 'src/preload.cjs'), resolve(packagedApp, 'src/preload.cjs')),
  cp(resolve(electronRoot, 'src/google-oauth-core.mjs'), resolve(packagedApp, 'src/google-oauth-core.mjs')),
  cp(resolve(electronRoot, 'src/desktop-google-oauth.mjs'), resolve(packagedApp, 'src/desktop-google-oauth.mjs')),
  cp(resolve(electronRoot, 'src/agent-server.mjs'), resolve(packagedApp, 'src/agent-server.mjs')),
  cp(resolve(electronRoot, 'src/human-approval-main-signer.mjs'), resolve(packagedApp, 'src/human-approval-main-signer.mjs')),
  cp(resolve(electronRoot, 'package.json'), resolve(packagedApp, 'package.json')),
  cp(resolve(electronRoot, '../web/dist'), resolve(packagedApp, 'web/dist'), { recursive: true }),
  writeFile(resolve(packagedApp, 'src/build-config.mjs'), [
    '// Generated by package-mac.mjs. The OAuth client ID is public; no client secret is embedded.',
    `export const GOOGLE_DESKTOP_CLIENT_ID = ${JSON.stringify(process.env.GOOGLE_DESKTOP_CLIENT_ID?.trim() ?? '')};`,
    "export const RHYTHM_AUTH_API_BASE = 'https://api.vcrcapps.com';",
    '',
  ].join('\n')),
]);

await rename(
  resolve(stagingArtifact, 'Contents/MacOS/Electron'),
  resolve(stagingArtifact, 'Contents/MacOS/Rhythm'),
);
for (const [key, value] of [
  ['CFBundleExecutable', 'Rhythm'],
  ['CFBundleIdentifier', 'com.rhythm.desktop'],
  ['CFBundleName', 'Rhythm'],
  ['CFBundleDisplayName', 'Rhythm'],
  ['CFBundleShortVersionString', '0.1.0'],
  ['CFBundleVersion', '0.1.0'],
]) {
  await run('plutil', ['-replace', key, '-string', value, infoPlist]);
}

await run('codesign', ['--force', '--deep', '--sign', '-', stagingArtifact]);
await rename(stagingArtifact, artifact);
process.stdout.write(`Packaged ${artifact} with an ad-hoc signature.\n`);
