import { execFile } from 'node:child_process';
import { chmod, cp, mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const run = promisify(execFile);
const electronRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceApp = resolve(electronRoot, 'node_modules/electron/dist/Electron.app');
const distRoot = resolve(electronRoot, 'dist');
const artifact = resolve(distRoot, 'Rhythm.app');
const stagingArtifact = resolve(distRoot, '.Rhythm.app.tmp');
const resources = resolve(stagingArtifact, 'Contents/Resources');
const packagedApp = resolve(resources, 'app');
const apiServerSource = resolve(electronRoot, '../api_server');
const packagedApiServer = resolve(resources, 'api_server');
const packagedNode = resolve(resources, 'node/bin/node');
const infoPlist = resolve(stagingArtifact, 'Contents/Info.plist');
const releaseVersion = process.env.RELEASE_VERSION?.trim() || '0.1.0';
if (!/^\d+(?:\.\d+){0,2}$/.test(releaseVersion)) {
  throw new Error(`RELEASE_VERSION must contain one to three numeric components: ${releaseVersion}`);
}
const rendererBuildEnvironment = { ...process.env };
// TEST-ONLY: Vite gateway values remain supported by `npm run dev` and Playwright. A shipping
// renderer must start from a neutral environment, then receive only the non-secret live-mode
// invariant; caller-supplied bases and tokens must never become artifact bytes.
for (const key of [
  'VITE_RHYTHM_GATEWAY_MODE',
  'VITE_RHYTHM_API_BASE',
  'VITE_RHYTHM_ENGINE_BASE',
  'VITE_RHYTHM_LIVE_TOKEN',
]) delete rendererBuildEnvironment[key];
rendererBuildEnvironment.VITE_RHYTHM_GATEWAY_MODE = 'live';

await run('npm', ['--prefix', '../web', 'run', 'build'], {
  cwd: electronRoot,
  env: rendererBuildEnvironment,
});
await run('npm', ['--prefix', '../api_server', 'run', 'build'], { cwd: electronRoot });
await mkdir(distRoot, { recursive: true });
await Promise.all([
  rm(artifact, { recursive: true, force: true }),
  rm(stagingArtifact, { recursive: true, force: true }),
]);
await cp(sourceApp, stagingArtifact, { recursive: true, verbatimSymlinks: true });
await mkdir(resolve(packagedApp, 'src'), { recursive: true });
await mkdir(packagedApiServer, { recursive: true });
await Promise.all([
  cp(resolve(electronRoot, 'src/main.mjs'), resolve(packagedApp, 'src/main.mjs')),
  cp(resolve(electronRoot, 'src/policy.mjs'), resolve(packagedApp, 'src/policy.mjs')),
  cp(resolve(electronRoot, 'src/production-api-config.mjs'), resolve(packagedApp, 'src/production-api-config.mjs')),
  cp(resolve(electronRoot, 'src/runtime-config.mjs'), resolve(packagedApp, 'src/runtime-config.mjs')),
  cp(resolve(electronRoot, 'src/preload.cjs'), resolve(packagedApp, 'src/preload.cjs')),
  cp(resolve(electronRoot, 'src/google-oauth-core.mjs'), resolve(packagedApp, 'src/google-oauth-core.mjs')),
  cp(resolve(electronRoot, 'src/desktop-google-oauth.mjs'), resolve(packagedApp, 'src/desktop-google-oauth.mjs')),
  cp(resolve(electronRoot, 'src/agent-server.mjs'), resolve(packagedApp, 'src/agent-server.mjs')),
  cp(resolve(electronRoot, 'src/human-approval-main-signer.mjs'), resolve(packagedApp, 'src/human-approval-main-signer.mjs')),
  cp(resolve(electronRoot, 'package.json'), resolve(packagedApp, 'package.json')),
  cp(resolve(electronRoot, '../web/dist'), resolve(packagedApp, 'web/dist'), { recursive: true }),
  ...['dist', 'scripts', 'opencode_plugins', 'config_seeds', 'vendor', 'resources'].map((entry) =>
    cp(resolve(apiServerSource, entry), resolve(packagedApiServer, entry), { recursive: true })),
  cp(resolve(apiServerSource, 'package.json'), resolve(packagedApiServer, 'package.json')),
  cp(resolve(apiServerSource, 'package-lock.json'), resolve(packagedApiServer, 'package-lock.json')),
  cp(resolve(electronRoot, '../../.mcp-roles'), resolve(packagedApiServer, '.mcp-roles'), { recursive: true }),
  writeFile(resolve(packagedApp, 'src/build-config.mjs'), [
    '// Generated by package-mac.mjs. The OAuth client ID is public; no client secret is embedded.',
    `export const GOOGLE_DESKTOP_CLIENT_ID = ${JSON.stringify(process.env.GOOGLE_DESKTOP_CLIENT_ID?.trim() ?? '')};`,
    "export const RHYTHM_AUTH_API_BASE = 'https://api.vcrcapps.com';",
    '',
  ].join('\n')),
]);

// Match the shipping Flutter bundle: install production dependencies in the detached payload,
// letting api_server's postinstall rebuild better-sqlite3 against this exact Node runtime.
await run('npm', ['install', '--omit=dev'], { cwd: packagedApiServer });
await run('npm', ['install', '--omit=dev'], { cwd: resolve(packagedApiServer, 'config_seeds/tools') });
await rm(resolve(packagedApiServer, '.node-runtime.json'), { force: true });

await mkdir(dirname(packagedNode), { recursive: true });
await cp(process.execPath, packagedNode);
await chmod(packagedNode, 0o755);
// Probe native addons in separate processes. Loading node-pty after creating a better-sqlite3
// Statement can force that Statement's GC during Node 24 addon teardown and abort inside
// RemoveEnvironmentCleanupHook even though each addon is ABI-correct.
await run(packagedNode, ['-e', [
  `const root=${JSON.stringify(packagedApiServer)};`,
  "const Database=require(root+'/node_modules/better-sqlite3');",
  "const db=new Database(':memory:');",
  "if(db.prepare('select 1 as x').get().x!==1)process.exit(1);",
].join('')]);
await run(packagedNode, ['-e', [
  `const root=${JSON.stringify(packagedApiServer)};`,
  "require(root+'/node_modules/node-pty');",
].join('')]);

await rename(
  resolve(stagingArtifact, 'Contents/MacOS/Electron'),
  resolve(stagingArtifact, 'Contents/MacOS/Rhythm'),
);
for (const [key, value] of [
  ['CFBundleExecutable', 'Rhythm'],
  ['CFBundleIdentifier', 'com.rhythm.desktop'],
  ['CFBundleName', 'Rhythm'],
  ['CFBundleDisplayName', 'Rhythm'],
  ['CFBundleShortVersionString', releaseVersion],
  ['CFBundleVersion', releaseVersion],
]) {
  await run('plutil', ['-replace', key, '-string', value, infoPlist]);
}

await run('codesign', ['--force', '--deep', '--sign', '-', stagingArtifact]);
await rename(stagingArtifact, artifact);
process.stdout.write(`Packaged ${artifact} with an ad-hoc signature.\n`);
