import { createHash } from 'crypto';
import { adaptRouterFreeConfig } from './router_free_config';
import { publicContextPreflight, type ExtractionTask } from './router_free_extraction';
import { selectFreeRoute, type FreeClassification, type FreeRouteDecision } from './router_free_policy';
import type { RouterFreeStateStore } from './router_free_state';
import type { RouterGridConfig } from './router_grid_config';

export interface PublicCodingTask { id: string; kind: 'coding'; label: string; prompt: string; classification: { tier: 1|2|3|4; category:'coding'; canQueue:boolean }; exportName: string; tests: Array<{args:unknown[];expected:unknown}> }
export interface PublicImageAsset { id:string; label:string; mime:'image/png'|'image/jpeg'; base64:string; sha256:string }
export interface PublicImageDesignTask { id:string; kind:'image_design'; label:string; prompt:string; imageId:string; classification:{tier:1|2|3|4;category:'design';canQueue:boolean}; helperRequiredTerms:string[]; expected:Record<string,string|number|boolean> }
export type PublicFreeTask=PublicCodingTask|PublicImageDesignTask;
export type PublicTaskResult={kind:'held';reason:string}|{kind:'released';model:string;effort:string|null;degraded:boolean;values:unknown;checks:string[];helper?:{model:string;verified:true}}|{kind:'rejected';model:string;effort:string|null;checks:string[]};
export interface PublicTaskDeps { config:RouterGridConfig;store:RouterFreeStateStore;verifiedFreeModels:ReadonlySet<string>;baseUrl:string;apiKey:string;fetchImpl?:typeof fetch;timeoutMs?:number }
const ID=/^[a-z0-9][a-z0-9_-]{0,63}$/, NAME=/^[A-Za-z_$][A-Za-z0-9_$]{0,39}$/;
const publicShape=(sourceText:string,taskId:string):ExtractionTask=>({kind:'structured_extraction',taskId,sourceText,fields:[{name:'payload',type:'string',required:true}],publicSource:{trusted:true,label:taskId},ownerOptIn:true,attachments:[],context:{memory:false,dayflow:false,history:false,profilePrompt:false}});
const publicText=(id:string,surfaces:string[])=>publicContextPreflight(publicShape(surfaces.join('\n'),id)).privacy===false;
export function validatePublicCodingTask(t:PublicCodingTask):boolean{return !!t&&ID.test(t.id)&&t.kind==='coding'&&!!t.label&&t.label.length<=200&&!!t.prompt&&t.prompt.length<=10000&&NAME.test(t.exportName)&&[1,2,3,4].includes(t.classification?.tier)&&t.classification?.category==='coding'&&typeof t.classification?.canQueue==='boolean'&&Array.isArray(t.tests)&&t.tests.length>0&&t.tests.length<=20&&t.tests.every(x=>Array.isArray(x.args)&&x.args.length<=10&&JSON.stringify(x).length<=5000)&&publicText(t.id,[t.label,t.prompt,t.exportName,JSON.stringify(t.tests)])}
export function validatePublicImageTask(t:PublicImageDesignTask,a:PublicImageAsset|undefined):boolean{if(!t||!a||!ID.test(t.id)||!ID.test(a.id)||t.kind!=='image_design'||t.imageId!==a.id||!t.label||t.label.length>200||!t.prompt||t.prompt.length>10000||t.classification?.category!=='design'||![1,2,3,4].includes(t.classification?.tier)||typeof t.classification?.canQueue!=='boolean'||!Array.isArray(t.helperRequiredTerms)||t.helperRequiredTerms.length<2||t.helperRequiredTerms.length>20||t.helperRequiredTerms.some(x=>!x||x.length>100)||!a.label||a.label.length>200||!['image/png','image/jpeg'].includes(a.mime)||!/^[a-f0-9]{64}$/.test(a.sha256)||typeof a.base64!=='string'||a.base64.length>1500000)return false;let b:Buffer;try{b=Buffer.from(a.base64,'base64')}catch{return false}if(!b.length||createHash('sha256').update(b).digest('hex')!==a.sha256)return false;const magic=a.mime==='image/png'?b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):b[0]===255&&b[1]===216&&b.at(-2)===255&&b.at(-1)===217;return !!magic&&!!t.expected&&!Array.isArray(t.expected)&&Object.keys(t.expected).length>0&&JSON.stringify(t.expected).length<=5000&&publicText(t.id,[t.label,t.prompt,...t.helperRequiredTerms,JSON.stringify(t.expected),a.label])}
/** Provider-generated JavaScript is not executed in-process. A cross-platform OS-isolated executor with
 * a read-only root, no network/credentials, descendant containment and resource limits does not exist in Rhythm yet. */
export function verifyPublicCode(_t:PublicCodingTask,_out:string):{pass:boolean;checks:string[];code?:string}{return{pass:false,checks:['untrusted_code_execution_unsupported']}}
export function verifyPublicImageOutput(t:PublicImageDesignTask,out:string):{pass:boolean;checks:string[];values?:Record<string,unknown>}{let v:unknown;try{v=JSON.parse(out)}catch{return{pass:false,checks:['output_not_json']}}if(!v||typeof v!=='object'||Array.isArray(v))return{pass:false,checks:['output_not_object']};if(JSON.stringify(v)!==JSON.stringify(t.expected))return{pass:false,checks:['oracle_mismatch']};return{pass:true,checks:['oracle_match'],values:v as Record<string,unknown>}}
async function provider(d:PublicTaskDeps,r:Extract<FreeRouteDecision,{kind:'route'}>,messages:unknown[],model=r.model,effort=r.effort):Promise<{ok:true;text:string}|{ok:false;code:'429'|'5xx'|'error_body'|'empty'}>{const lease=d.store.tryReserve(1);if(lease.kind!=='lease'||!d.store.commitAttempt(lease.lease.id))return{ok:false,code:'error_body'};try{const res=await(d.fetchImpl??fetch)(`${d.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',redirect:'error',signal:AbortSignal.timeout(d.timeoutMs??30000),headers:{'content-type':'application/json',authorization:`Bearer ${d.apiKey}`},body:JSON.stringify({model:model.replace(/^openrouter\//,''),stream:false,...(effort?{reasoning:{effort}}:{}),messages})});if(res.status===429)return{ok:false,code:'429'};if(res.status>=500)return{ok:false,code:'5xx'};if(!res.ok)return{ok:false,code:'error_body'};const body=await res.json().catch(()=>null) as {error?:unknown;choices?:Array<{message?:{content?:unknown}}>}|null;if(!body||body.error)return{ok:false,code:'error_body'};const text=body.choices?.[0]?.message?.content;return typeof text==='string'&&text.trim()?{ok:true,text}:{ok:false,code:'empty'}}catch{return{ok:false,code:'error_body'}}finally{d.store.release(lease.lease.id)}}
function route(d:PublicTaskDeps,c:FreeClassification,images:boolean,blocked:ReadonlySet<string>):FreeRouteDecision{return selectFreeRoute({config:adaptRouterFreeConfig(d.config).policy,classification:c,privacyPreflight:false,realUser:true,hasImages:images,canVerify:true,availableVerifiedFreeModels:d.verifiedFreeModels,openCircuitModels:new Set([...d.store.openCircuits(),...blocked]),dailyRemaining:d.store.usage().dailyRemaining,dailyCount:d.store.usage().dailyCount,rpmCount:Math.max(0,d.config.free_mode.rpm_limit-Math.floor(d.store.usage().availableTokens))})}
const cls=(v:PublicFreeTask['classification']):FreeClassification=>({...v,containsPrivateData:false});
export async function executePublicCoding(t:PublicCodingTask,d:PublicTaskDeps):Promise<PublicTaskResult>{return{kind:'held',reason:'untrusted_code_execution_unsupported'}}
export async function executePublicImageDesign(t:PublicImageDesignTask,a:PublicImageAsset,d:PublicTaskDeps):Promise<PublicTaskResult>{if(d.config.free_mode.enabled!==true||!validatePublicImageTask(t,a))return{kind:'held',reason:'privacy'};const r=route(d,cls(t.classification),true,new Set());if(r.kind==='queue')return{kind:'held',reason:r.reason};if(!r.helper)return{kind:'held',reason:'helper_not_required'};const h=await provider(d,r,[{role:'system',content:r.helper.prompt},{role:'user',content:[{type:'text',text:`SDMRX:${t.id} Public image ${a.id}: describe this registered image only.`},{type:'image_url',image_url:{url:`data:${a.mime};base64,${a.base64}`}}]}],r.helper.model,r.helper.effort);if(!h.ok){d.store.recordFailure(r.helper.model,h.code);return{kind:'held',reason:'helper_failed'}}const lower=h.text.toLowerCase();if(!t.helperRequiredTerms.every(x=>lower.includes(x.toLowerCase())))return{kind:'rejected',model:r.helper.model,effort:r.helper.effort??null,checks:['helper_oracle_mismatch']};const ans=await provider(d,r,[{role:'system',content:'Use only the verified public image description. Return JSON only, with exactly the requested design fields.'},{role:'user',content:`SDMRX:${t.id} Task ${t.id}: ${t.prompt}\nVerified image description:\n${h.text}\nRequired keys: ${Object.keys(t.expected).join(', ')}`}]);if(!ans.ok){d.store.recordFailure(r.model,ans.code);return{kind:'held',reason:'answer_failed'}}const v=verifyPublicImageOutput(t,ans.text);if(!v.pass)return{kind:'rejected',model:r.model,effort:r.effort??null,checks:v.checks};d.store.reportSuccess(r.model);d.store.reportSuccess(r.helper.model);return{kind:'released',model:r.model,effort:r.effort??null,degraded:r.degraded,values:v.values!,checks:[...t.helperRequiredTerms.map(x=>`helper:${x}`),...v.checks],helper:{model:r.helper.model,verified:true}}}
