import Database from 'better-sqlite3';
import { mkdtempSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { expect, it, vi } from 'vitest';
import { env } from '../../config/env';
import * as database from '../../database/db';
import { runPostgresBootstrap } from '../../database/postgres_bootstrap';
import { RouterGridAttemptsRepository } from './router_grid_attempts_repository';
import { recordDecision } from './decision_log';
import { runMigrations } from '../../database/migrations';
import { setDb } from '../../database/db';
const c = { tier: 4, category: 'knowledge', canQueue: false, securitySensitive: false, estInputTokens: 12, source: 'rules', reason: 'ok' };
const r = { model: 'openai/fake', provider: 'openai', effortRequested: 'high', effortApplied: 'high', accountId: 'a', accountSource: 'router', tierUsed: 4, kind: 'route', reason: 'ok', degraded: false, applied: true, trace: [] };
it('repair-c3: PG bootstrap schema and actual parameterized pool query boundary preserve restart state', async () => {
  const rows: any[] = [];
  const pool = { query: vi.fn(async (sql: string, values?: any[]) => {
    if (sql.startsWith('INSERT INTO agent_router_grid_attempts')) {
      expect(sql).toContain('VALUES ($1,$2,$3,$4)');
      rows.push({ classification_json: values![2], result_json: values![3] });
    }
    return { rows: sql.startsWith('SELECT classification_json') ? rows : [], rowCount: 0 };
  }) };
  const connectedPool = { ...pool, connect: async () => ({ query: pool.query, release: () => undefined }) };
  await runPostgresBootstrap(connectedPool as any);
  const schema = pool.query.mock.calls[0][0];
  expect(schema).toContain('CREATE TABLE IF NOT EXISTS agent_router_grid_attempts');
  expect(schema).toContain('GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  expect(schema).toContain('ON agent_router_grid_attempts(session_id,id)');
  expect(schema).not.toMatch(/DROP|DELETE|query_preview/);
  const previous = env.dbClient; env.dbClient = 'postgres';
  const spy = vi.spyOn(database, 'getPostgresPool').mockReturnValue(pool as any);
  try {
    recordDecision({ feature: 'model_routing', mode: 'on', sessionId: 'pg-session', status: 'ok', applied: true });
    await new RouterGridAttemptsRepository().append('pg-session', c, r);
    await new RouterGridAttemptsRepository().append('pg-session', { ...c, tier: 1 }, { ...r, model: 'openai/next' });
    expect(await new RouterGridAttemptsRepository().readState('pg-session')).toEqual({ classification: c, model: 'openai/next', provider: 'openai', accountId: 'a', accountSource: 'router' });
    expect(pool.query.mock.calls.at(-1)).toEqual(['SELECT classification_json,result_json FROM agent_router_grid_attempts WHERE session_id=$1 ORDER BY id', ['pg-session']]);
  } finally { spy.mockRestore(); env.dbClient = previous; }
});
it('repair-c3: closed validation rejects prompt/error/secret fields and malformed values without mutation', async () => {
  const db = new Database(':memory:'); runMigrations(db); const previous = setDb(db);
  try {
    const repo = new RouterGridAttemptsRepository();
    for (const invalid of [{ ...c, query: 'private prompt' }, { ...c, tier: 9 }, { ...c, reason: 'provider body secret' }, { ...c, securitySensitive: null }]) {
      await expect(repo.append('s', invalid, r)).rejects.toThrow('invalid_grid_attempt');
    }
    for (const invalid of [{ ...r, error: 'secret' }, { ...r, effortApplied: 'unknown' }, { ...r, provider: 'other' },
      { ...r, trace: [{ action: 'route', tier: 4, excerpt: 'private' }] }]) await expect(repo.append('s', c, invalid)).rejects.toThrow('invalid_grid_attempt');
    expect(db.prepare('SELECT COUNT(*) AS n FROM agent_router_grid_attempts').get()).toEqual({ n: 0 });
  } finally { setDb(previous); db.close(); }
});
it('repair-c3: additive durable attempt schema survives migration rerun', () => {
  const db = new Database(':memory:'); runMigrations(db); runMigrations(db);
  expect(db.prepare("SELECT name FROM sqlite_master WHERE name='agent_router_grid_attempts'").get()).toEqual({ name: 'agent_router_grid_attempts' });
  db.close();
});
it('repair-c3: SQLite restart keeps first classification and latest applied model without diagnostic log', async () => {
  const path = join(mkdtempSync(join(tmpdir(), 'grid-attempts-')), 'ledger.db');
  let db = new Database(path); db.pragma('journal_mode = MEMORY'); runMigrations(db); const prev = setDb(db);
  try {
    const modulePath = './router_grid_attempts_repository';
    const mod = await import(modulePath).catch(() => null);
    expect(mod, 'durable repository must exist').not.toBeNull();
    const repo = new mod.RouterGridAttemptsRepository();
    const classification = { tier: 4, category: 'knowledge', canQueue: false, securitySensitive: false, estInputTokens: 12, source: 'rules', reason: 'ok' };
    const result = { model: 'openai/fake', provider: 'openai', effortRequested: 'high', effortApplied: 'high', accountId: 'a', accountSource: 'router', tierUsed: 4, kind: 'route', reason: 'ok', degraded: false, applied: true, trace: [] };
    await repo.append('fake-session', classification, result);
    await repo.append('fake-session', { ...classification, tier: 1 }, { ...result, model: 'anthropic/fake', provider: 'anthropic' });
    await repo.append('fake-session', classification, { ...result, kind: 'shadow', model: 'openai/shadow' });
    await repo.append('fake-session', classification, { ...result, kind: 'none', model: null, provider: null, tierUsed: null, reason: 'no_usable_route' });
    db.close(); db = new Database(path); setDb(db);
    expect(await new mod.RouterGridAttemptsRepository().readState('fake-session')).toEqual({ classification, model: 'anthropic/fake', provider: 'anthropic', accountId: 'a', accountSource: 'router' });
    const stored = db.prepare('SELECT classification_json,result_json FROM agent_router_grid_attempts ORDER BY id').all();
    expect(stored).toHaveLength(4);
    expect(Object.keys(JSON.parse((stored[0] as any).classification_json)).sort()).toEqual(['canQueue', 'category', 'estInputTokens', 'reason', 'securitySensitive', 'source', 'tier']);
    expect(Object.keys(JSON.parse((stored[0] as any).result_json)).sort()).toEqual(['accountId', 'accountSource', 'applied', 'degraded', 'effortApplied', 'effortRequested', 'kind', 'model', 'provider', 'reason', 'tierUsed', 'trace']);
    expect(db.prepare('SELECT COUNT(*) AS n FROM agent_decision_log').get()).toEqual({ n: 0 });
  } finally { setDb(prev); db.close(); } // Fixtures intentionally preserved.
});
it('pending failed route cannot supersede a prior explicit-pin applied receipt', async () => {
  const db = new Database(':memory:'); runMigrations(db); const previous = setDb(db);
  try {
    const repo = new RouterGridAttemptsRepository();
    await repo.append('pin-session', c, { ...r, accountSource: 'pinned', applied: true });
    await repo.append('pin-session', c, { ...r, accountSource: 'router', accountId: 'other', applied: false });
    expect(await repo.readState('pin-session')).toMatchObject({ accountSource: 'pinned', accountId: 'a' });
    expect(await repo.isRouterOwnedAccount('pin-session', 'openai', 'other')).toBe(false);
  } finally { setDb(previous); db.close(); }
});

it('legacy route without applied is ambiguous and never authorizes restart auto ownership', async () => {
  const db = new Database(':memory:'); runMigrations(db); const previous = setDb(db);
  try {
    db.prepare('INSERT INTO agent_router_grid_attempts(session_id,created_at,classification_json,result_json) VALUES (?,?,?,?)')
      .run('legacy-session', new Date().toISOString(), JSON.stringify(c), JSON.stringify((({ applied: _applied, ...legacy }) => legacy)(r)));
    const repo = new RouterGridAttemptsRepository();
    expect(await repo.readState('legacy-session')).toBeNull();
    expect(await repo.isRouterOwnedAccount('legacy-session', 'openai', 'a')).toBe(false);
  } finally { setDb(previous); db.close(); }
});
