import { Platform, StyleSheet } from 'react-native';

import { Fonts, MinimumTouchTarget, Radii, Spacing, TypeScale } from '@/constants/theme';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  // Restored from the merge base: integration replaced the generic loading row
  // with AgentTypingBubble, but mega's completion-sync row still renders with it.
  loadingRow: { flexDirection: 'row', gap: 10, alignItems: 'center', paddingHorizontal: 8, paddingBottom: 8 },
  keyboardArea: { flex: 1 },
  header: { alignItems: 'center', flexDirection: 'row', height: 52, minHeight: 52 },
  headerBackButton: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 },
  headerBackGlyph: { fontFamily: Fonts.sans, fontSize: 22, lineHeight: 24 },
  headerMain: { flex: 1, minWidth: 0, alignSelf: 'stretch', justifyContent: 'center' },
  headerActions: { flexDirection: 'row', alignItems: 'center', flexShrink: 0 },
  headerAction: { minWidth: 44, minHeight: 44, margin: 0, alignItems: 'center', justifyContent: 'center' },
  headerActionPressed: { opacity: 0.72 },
  headerFilesButton: { minHeight: 44, margin: 0 },
  headerTitle: { fontFamily: Fonts.display, fontSize: TypeScale.body, fontWeight: '700', flexShrink: 1 },
  headerSessionAnchor: { flex: 1, alignSelf: 'stretch', justifyContent: 'center', borderRadius: 14, marginRight: 8 },
  headerSessionAnchorPressed: { opacity: 0.82 },
  headerSessionContent: { flexDirection: 'row', alignItems: 'center', gap: 8, minWidth: 0, minHeight: 44, paddingRight: 4 },
  headerSessionTextWrap: { flex: 1, minWidth: 0 },
  headerUsage: { fontFamily: Fonts.sans, fontSize: TypeScale.caption2, marginTop: 1, flexShrink: 1 },
  chatSegmentedControl: { flexDirection: 'row', height: 44, marginHorizontal: 16, marginBottom: Spacing.x2, position: 'relative' },
  chatSegmentedVisual: { borderRadius: Radii.control, bottom: 6, left: 0, position: 'absolute', right: 0, top: 6 },
  topTabVisual: { height: 32 },
  sessionPickerOverlay: { ...StyleSheet.absoluteFillObject },
  sessionPickerBackdrop: { ...StyleSheet.absoluteFillObject },
  sessionPickerBackdropFill: { flex: 1, backgroundColor: 'rgba(0,0,0,0.28)' },
  sessionPickerSheet: { position: 'absolute', left: 0, right: 0, bottom: 0, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, overflow: 'hidden' },
  sessionPickerHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1 },
  sessionPickerCloseButton: { minHeight: MinimumTouchTarget, justifyContent: 'center', paddingHorizontal: 10, borderRadius: 999 },
  sessionPickerCloseButtonPressed: { opacity: 0.82 },
  sessionPickerCloseLabel: { fontFamily: Fonts.sans, fontSize: 15, fontWeight: '600' },
  sessionPickerList: { padding: 12, gap: 8, paddingBottom: 24 },
  sessionPickerItem: { borderRadius: 16, borderWidth: 1 },
  sessionPickerItemRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 56, paddingHorizontal: 14, paddingVertical: 12 },
  sessionPickerItemIcon: { width: 32, height: 32, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  sessionPickerItemTextWrap: { flex: 1, gap: 2 },
  sessionPickerItemTitle: { fontFamily: Fonts.sans, fontSize: 16 },
  sessionPickerItemSubtitle: { fontFamily: Fonts.sans, fontSize: 13 },
  usageProvider: { borderWidth: 1, borderRadius: 14, gap: 8, padding: 12 },
  usageModel: { gap: 4, paddingLeft: 8 },
  usageRow: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  contextProgress: { borderRadius: 999, height: 8 },
  tabsRow: { flexDirection: 'row', borderBottomWidth: 1 },
  chatArea: { flex: 1, position: 'relative' },
  scroll: { flex: 1 },
  content: { alignSelf: 'center', gap: 0, maxWidth: 422, paddingHorizontal: 16, paddingBottom: 24, width: '100%' },
  transcriptItem: { marginBottom: 20 },
  transcriptHeader: { gap: 8 },
  transcriptFooter: { gap: 12 },
  noticeCard: { borderRadius: 20 },
  waitingNoticeContent: { gap: 8 },
  waitingNoticeHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  emptyContent: { gap: Spacing.x3, paddingBottom: Spacing.x6, paddingTop: Spacing.x6 },
  emptyTitle: { fontFamily: Fonts.display, fontSize: TypeScale.title2, lineHeight: 28, fontWeight: '700' },
  emptyDescription: { fontFamily: Fonts.sans, fontSize: TypeScale.subheadline, lineHeight: 22, maxWidth: 440 },
  promptStack: { gap: Spacing.x2, marginTop: Spacing.x1 },
  promptCard: { borderWidth: 1, borderRadius: Radii.grouped },
  promptCardInner: { flexDirection: 'row', gap: Spacing.x3, alignItems: 'center', minHeight: 60, paddingHorizontal: Spacing.x4, paddingVertical: Spacing.x3 },
  promptCardText: { flex: 1, fontFamily: Fonts.sans, fontSize: TypeScale.subheadline, lineHeight: 21 },
  sectionStack: { gap: 12 },
  sectionCard: { borderRadius: 18 },
  sectionHeaderCard: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, alignItems: 'center' },
  diffGroup: { borderWidth: 1, borderRadius: Radii.grouped, gap: 12, padding: 14 },
  paginationRow: { alignItems: 'center', flexDirection: 'row', gap: 6, height: 44, justifyContent: 'center', marginBottom: 8 },
  paginationLabel: { fontFamily: Fonts.sans, fontSize: 13 },
  composer: {
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: Platform.select({ ios: 4, default: 4 }),
    gap: 0,
    borderTopWidth: 1,
  },
  composerDockRow: { flexDirection: 'row', alignItems: 'center' },
  inputShell: { borderWidth: 1, borderRadius: 22, maxHeight: 92, paddingHorizontal: Spacing.x1, paddingVertical: 4, minHeight: 48, justifyContent: 'center' },
  inputShellFlex: { flex: 1 },
  // Keep actions anchored while multiline text grows upward.
  composerRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.x1 },
  // The native input takes over scrolling after reaching the explicit cap.
  input: { flex: 1, minHeight: 24, maxHeight: 84, fontSize: 17, lineHeight: 22, marginHorizontal: -4, paddingVertical: 0, textAlignVertical: 'top' },
  inputContentCompact: { paddingHorizontal: 0, paddingTop: 0, paddingBottom: 0, fontFamily: Fonts.sans },
  controlsRow: { flexDirection: 'row', flexWrap: 'nowrap', gap: 6, paddingHorizontal: 0, alignItems: 'center', width: '100%' },
  attachmentStrip: { flexGrow: 0, maxHeight: 48 },
  attachmentRow: { flexDirection: 'row', gap: 8, paddingVertical: 2 },
  attachmentChip: { width: 168, height: 44, flexDirection: 'row', alignItems: 'center', borderRadius: 16 },
  attachmentTypeIcon: { height: 32, width: 32, margin: 0 },
  attachmentLabel: { flex: 1, minWidth: 0 },
  attachmentRemoveButton: { width: MinimumTouchTarget, height: MinimumTouchTarget, margin: 0 },
  conversationBanner: { borderWidth: 1, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 12, gap: 8 },
  conversationBannerHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, alignItems: 'center' },
  voiceStatusRow: { paddingHorizontal: 2 },
  voiceStatusChip: { alignSelf: 'flex-start' },
  composerMetadataRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: MinimumTouchTarget },
  composerMetadataActions: { alignItems: 'center', flexDirection: 'row' },
  composerStateLabel: { flex: 1, minWidth: 0, paddingLeft: 4 },
  composerDismissButton: { margin: 0, height: MinimumTouchTarget, width: MinimumTouchTarget },
  composerVoiceButton: { margin: 0, height: MinimumTouchTarget, width: MinimumTouchTarget },
  composerInlineButton: { margin: 0, width: MinimumTouchTarget, height: MinimumTouchTarget, alignSelf: 'center' },
  composerPrimaryButton: { margin: 0, width: MinimumTouchTarget, height: MinimumTouchTarget, borderRadius: Radii.pill, alignSelf: 'center' },
  composerActionButton: { margin: 0 },
  sendErrorCard: { marginHorizontal: 12, marginBottom: 12, borderRadius: 16 },
  sendErrorContent: { gap: 8 },
  sendErrorActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 4 },
  diffListCardContent: { paddingHorizontal: 0, paddingVertical: 0 },
  todoInline: { borderTopWidth: 1 },
  todoHeader: { minHeight: MinimumTouchTarget, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 4 },
  todoSummary: { flex: 1 },
  todoToggleButton: { width: MinimumTouchTarget, height: MinimumTouchTarget, margin: 0 },
  todoList: { gap: 4, paddingBottom: 8 },
  todoItemRow: { flexDirection: 'row', alignItems: 'center', gap: 4, minHeight: MinimumTouchTarget },
  todoStatusIcon: { margin: 0 },
  todoTextWrap: { flex: 1 },
});
