import { useEffect, useRef, useState } from 'react';
import { DayflowGatewayError, type DayflowCommit, type DayflowConfig, type DayflowGateway, type DayflowPreview, type DayflowStatus, type OwnedNotesPage } from '../../gateway/dayflow';

const today = () => new Date().toLocaleDateString('en-CA');
const message = (error: unknown) => error instanceof DayflowGatewayError ? error.message : 'Dayflow is unavailable.';
const configSignature = (config: DayflowConfig) => JSON.stringify({ timezone: config.timezone, exclusions: config.exclusions, maxRecordsPerRun: config.maxRecordsPerRun });
const receiptSummary = (items: DayflowCommit['items']) => items.map((item) => `${item.candidateId}: ${item.state}${item.code ? ` (${item.code})` : ''}`).join(' · ');

export function DayflowSettingsSection({ dayflow }: { dayflow?: DayflowGateway }) {
  const [status, setStatus] = useState<DayflowStatus | null>(null); const [config, setConfig] = useState<DayflowConfig | null>(null); const [owned, setOwned] = useState<OwnedNotesPage | null>(null);
  const [bundlePath, setBundlePath] = useState(''); const [selectionToken, setSelectionToken] = useState(''); const [date, setDate] = useState(today); const [preview, setPreview] = useState<DayflowPreview | null>(null); const [selected, setSelected] = useState<Set<string>>(new Set()); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [disabling, setDisabling] = useState(false); const [loadFailed, setLoadFailed] = useState(false); const [savedConfig, setSavedConfig] = useState('');
  const operationGeneration = useRef(0); const draftRevision = useRef(0); const saveRevision = useRef(0); const disableRevision = useRef(0); const mounted = useRef(false); const bundlePathRef = useRef(bundlePath);
  const current = (generation: number) => mounted.current && generation === operationGeneration.current;
  // Editing timezone/exclusions invalidates a preview, but does not alter a source selection that
  // was already checked for the same bundle path. Path changes and Disable still revoke consent.
  const invalidate = (clearSelection = true) => { operationGeneration.current += 1; if (clearSelection) setSelectionToken(''); setPreview(null); setSelected(new Set()); };
  const refresh = async (generation = operationGeneration.current, submittedRevision?: number) => {
    if (!dayflow) return false;
    const [nextStatus, nextConfig, nextOwned] = await Promise.all([dayflow.getStatus(), dayflow.getConfig(), dayflow.listOwned()]);
    if (!current(generation)) return false;
    setStatus(nextStatus); setSavedConfig(configSignature(nextConfig)); setOwned(nextOwned);
    if (submittedRevision === undefined || draftRevision.current === submittedRevision) setConfig(nextConfig);
    return true;
  };
  useEffect(() => { mounted.current = true; const generation = operationGeneration.current; void refresh(generation).catch(() => { if (current(generation)) setLoadFailed(true); }); return () => { mounted.current = false; operationGeneration.current += 1; }; // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dayflow]);
  useEffect(() => { bundlePathRef.current = bundlePath; }, [bundlePath]);
  const run = async (work: (generation: number) => Promise<void>) => { if (busy || disabling) return; const generation = operationGeneration.current; setBusy(true); setNotice(''); try { await work(generation); } catch (error) { if (current(generation)) setNotice(message(error)); } finally { if (mounted.current) setBusy(false); } };
  if (!dayflow || loadFailed) return <p className="settings-empty" role="status">Dayflow metadata is unavailable. No source access or import is active.</p>;
  if (!status || !config) return <p className="settings-feedback" role="status">Checking local Dayflow metadata…</p>;
  const configDirty = configSignature(config) !== savedConfig;
  const appendOwned = async (generation: number) => {
    if (!owned?.nextCursor || !dayflow) return;
    try {
      const next = await dayflow.listOwned(25, owned.nextCursor);
      if (!current(generation)) return;
      setOwned((current) => current ? { ...next, items: [...current.items, ...next.items.filter((item) => !current.items.some((existing) => existing.memoryId === item.memoryId))], total: next.total } : next);
    } catch (error) {
      if (error instanceof DayflowGatewayError && error.code === 'CURSOR_STALE') { const reloaded = await dayflow.listOwned(); if (!current(generation)) return; setOwned(reloaded); setNotice('The owned observations list changed and was reloaded.'); return; }
      throw error;
    }
  };
  return <section data-testid="dayflow-settings">
    <p className="settings-section-intro">Local manual activity import. Observations are unverified; this screen never captures automatically.</p>
    <dl className="settings-properties" data-testid="dayflow-status"><div><dt>State</dt><dd>{status.enabled ? 'Enabled' : 'Off'}</dd></div><div><dt>Readiness</dt><dd>{status.readiness.state}</dd></div><div><dt>Automatic import</dt><dd>Off</dd></div><div><dt>Stored observations</dt><dd>{status.importedCount}</dd></div></dl>
    {notice && <p role="alert" className="form-error">{notice}</p>}
    <div className="form-grid"><label className="field">Dayflow bundle path<input value={bundlePath} onChange={(event) => { setBundlePath(event.target.value); invalidate(); }} placeholder="/Applications/Dayflow.app" data-testid="dayflow-bundle-path" /></label><button type="button" className="secondary-button" disabled={!bundlePath || busy || disabling} onClick={() => void run(async (generation) => { const path = bundlePathRef.current; setSelectionToken(''); const result = await dayflow.checkReadiness(path); if (!current(generation) || bundlePathRef.current !== path) return; setSelectionToken(result.selectionToken ?? ''); setNotice(result.state === 'ready' ? 'Source verified. Save configuration before enabling.' : `Source is ${result.state}.`); })} data-testid="dayflow-check-source">Check source</button><label className="field">Timezone<input value={config.timezone ?? ''} onChange={(event) => { draftRevision.current += 1; setConfig({ ...config, timezone: event.target.value || null }); invalidate(false); }} placeholder="America/Los_Angeles" data-testid="dayflow-timezone" /></label><label className="field">Exclusions<input value={config.exclusions.join(', ')} onChange={(event) => { draftRevision.current += 1; setConfig({ ...config, exclusions: event.target.value.split(',').map((value) => value.trim()).filter(Boolean) }); invalidate(false); }} placeholder="Category names, separated by commas" data-testid="dayflow-exclusions" /></label><button type="button" className="secondary-button" disabled={busy || disabling || !config.timezone || !configDirty && !selectionToken} onClick={() => void run(async (generation) => { const submitted = config; const submittedToken = selectionToken || undefined; const submittedRevision = draftRevision.current; const request = ++saveRevision.current; const saved = await dayflow.updateConfig({ timezone: submitted.timezone ?? undefined, exclusions: submitted.exclusions, sourceSelectionToken: submittedToken }); if (!mounted.current || request !== saveRevision.current) return; setSavedConfig(configSignature(saved)); setSelectionToken((currentToken) => currentToken === submittedToken ? '' : currentToken); if (!current(generation)) return; invalidate(); const refreshed = await refresh(operationGeneration.current, submittedRevision); if (!refreshed) return; setNotice(draftRevision.current === submittedRevision ? 'Dayflow configuration saved and source status refreshed.' : 'Configuration saved; newer changes remain unsaved.'); })} data-testid="dayflow-save">Save configuration</button></div>
    {configDirty && <p className="settings-feedback" role="status">Configuration changes are not saved.</p>}
    <div className="dialog-actions"><button type="button" className="primary-button" disabled={busy || disabling || status.readiness.state !== 'ready' || !config.timezone || configDirty} onClick={() => void run(async (generation) => { const next = await dayflow.updateConfig({ enabled: true }); if (!current(generation)) return; setConfig(next); await refresh(generation); if (current(generation)) setNotice('Manual Dayflow integration enabled.'); })} data-testid="dayflow-enable">Enable manual integration</button><button type="button" className="secondary-button" disabled={disabling} onClick={() => { if (disabling) return; invalidate(); const request = ++disableRevision.current; setDisabling(true); setNotice(''); void dayflow.disable().then((next) => { if (mounted.current && request === disableRevision.current) { setStatus(next); setNotice('Dayflow disabled. Existing observations remain available to forget.'); } }).catch((error) => { if (mounted.current && request === disableRevision.current) setNotice(message(error)); }).finally(() => { if (mounted.current && request === disableRevision.current) setDisabling(false); }); }} data-testid="dayflow-disable">{disabling ? 'Disabling…' : 'Disable'}</button></div>
    <hr /><label className="field">Date<input type="date" value={date} onChange={(event) => { setDate(event.target.value); invalidate(); }} data-testid="dayflow-date" /></label><button type="button" className="primary-button" disabled={busy || disabling || configDirty || !status.canPreview || !date} onClick={() => void run(async (generation) => { const next = await dayflow.preview(date); if (!current(generation)) return; setPreview(next); setSelected(new Set()); })} data-testid="dayflow-preview">Preview observed activity</button>
    {preview && <section aria-label="Dayflow preview" data-testid="dayflow-preview-results"><p>Observed activity is unverified · {preview.date} · {preview.timeZone}</p>{preview.candidates.map((candidate) => <label className="check-row" key={candidate.candidateId}><input type="checkbox" checked={selected.has(candidate.candidateId)} onChange={() => setSelected((current) => { const next = new Set(current); next.has(candidate.candidateId) ? next.delete(candidate.candidateId) : next.add(candidate.candidateId); return next; })} data-testid={`dayflow-candidate-${candidate.candidateId}`} /><span><strong>{candidate.summary}</strong><small>{candidate.observedStart}{candidate.category ? ` · ${candidate.category}` : ''}</small></span></label>)}<button type="button" className="primary-button" disabled={busy || disabling || selected.size === 0} onClick={() => void run(async (generation) => { const receipt = await dayflow.commit(preview.token, [...selected]); if (!current(generation)) return; setNotice(receiptSummary(receipt.items)); invalidate(); await refresh(operationGeneration.current); })} data-testid="dayflow-import">Import {selected.size} selected</button></section>}
    <hr /><h3>Owned observations</h3>{owned?.items.map((note) => <div className="settings-row" key={note.memoryId}><span>{note.memoryId} · {note.state}</span><button type="button" className="text-danger-button" disabled={busy || disabling || note.state !== 'imported'} onClick={() => { if (window.confirm(`Forget owned observation ${note.memoryId}?`)) void run(async (generation) => { await dayflow.forget(note.memoryId); if (current(generation)) await refresh(generation); }); }} data-testid={`dayflow-forget-${note.memoryId}`}>Forget</button></div>)}{owned?.nextCursor && <button type="button" className="secondary-button" disabled={busy || disabling} onClick={() => void run(appendOwned)}>Load more</button>}
  </section>;
}
