import { useEffect, useState } from 'react';
import { navigate } from '../../components/Shell';
import { useAuthUser } from '../../gateway/auth';
import { useGateway } from '../../gateway/context';
import type { WorkspaceMember } from '../../gateway/workspace-members';
import { useFixtures } from '../../store';

export function SettingsPage() {
  const gateway = useGateway(); const settings = gateway.domains.settings; const auth = useAuthUser(); const { theme, setTheme } = useFixtures();
  const [workspace, setWorkspace] = useState<{ id: number; name: string; role: 'admin' | 'staff'; joinCode?: string } | null>(null); const [members, setMembers] = useState<WorkspaceMember[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [emailEnabled, setEmailEnabled] = useState(true);
  const [runtime, setRuntime] = useState({ api: 'checking', engine: 'checking' });
  const localKey = `rhythm.settings.${auth?.user.id ?? 'fixture'}`; const saved = JSON.parse(localStorage.getItem(localKey) ?? '{}');
  const shell = (window as Window & { rhythmShell?: { appVersion?: string; updates?: { openDownloadPage(): Promise<void> } } }).rhythmShell;
  const [dangerousConfirm, setDangerousConfirm] = useState(saved.dangerousConfirm ?? true); const [sendKey, setSendKey] = useState(saved.sendKey ?? 'Enter');
  const load = async () => { if (!settings) return; try { const [next, people] = await Promise.all([settings.workspace(), settings.members()]); setWorkspace(next); setMembers(people); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Settings could not be loaded.'); } };
  useEffect(() => { void load(); }, [settings]);
  useEffect(() => { void Promise.all([gateway.health.api(), gateway.health.engine()]).then(([api, engine]) => setRuntime({ api: api.state, engine: engine.state })).catch(() => setRuntime({ api: 'unavailable', engine: 'unavailable' })); }, [gateway]);
  const mutate = async (operation: () => Promise<unknown>) => { setBusy(true); try { await operation(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Setting could not be saved.'); } finally { setBusy(false); } };
  const saveLocal = (patch: Record<string, unknown>) => localStorage.setItem(localKey, JSON.stringify({ dangerousConfirm, sendKey, ...patch })); const admin = workspace?.role === 'admin';
  return <section className="page-shell settings-page" aria-labelledby="settings-title" data-testid="page-settings"><header><span className="eyebrow">Rhythm</span><h1 id="settings-title">Settings</h1><p>Workspace, account, access, and desktop preferences.</p></header>{error && <p role="alert">{error}</p>}
    <section><h2>Appearance and keyboard</h2><label>Theme<select value={theme} onChange={(event) => setTheme(event.target.value as typeof theme)}><option value="dark">Dark</option><option value="light">Light</option></select></label><label>Send message key<input value={sendKey} onChange={(event) => { setSendKey(event.target.value); saveLocal({ sendKey: event.target.value }); }} /></label><label><input type="checkbox" checked={dangerousConfirm} onChange={(event) => { setDangerousConfirm(event.target.checked); saveLocal({ dangerousConfirm: event.target.checked }); }} />Require confirmation for destructive tools</label><button type="button" onClick={() => { setSendKey('Enter'); setDangerousConfirm(true); localStorage.removeItem(localKey); }}>Reset keyboard and safety preferences</button></section>
    <section><h2>Workspace</h2><strong>{workspace?.name ?? 'No workspace'}</strong>{workspace?.joinCode && <p>Join code: <code>{workspace.joinCode}</code></p>}{admin && <button type="button" disabled={busy} onClick={() => void mutate(async () => { const result = await settings!.regenerateJoinCode(); setWorkspace((current) => current ? { ...current, joinCode: result.joinCode } : current); })}>Regenerate join code</button>}<ul>{members.map((member) => <li key={member.userId}><span>{member.name} · {member.email}</span><select aria-label={`Role for ${member.name}`} value={member.role} disabled={!admin || busy || member.userId === auth?.user.id} onChange={(event) => void mutate(() => settings!.updateRole(member.userId, event.target.value as 'admin' | 'staff'))}><option value="admin">Admin</option><option value="staff">Staff</option></select><label><input type="checkbox" checked={Boolean((member as WorkspaceMember & { isFacilitiesManager?: boolean }).isFacilitiesManager)} disabled={!admin || busy} onChange={(event) => void mutate(() => settings!.updateUser(member.userId, { isFacilitiesManager: event.target.checked }))} />Facilities manager</label>{admin && member.userId !== auth?.user.id && <button type="button" disabled={busy} onClick={() => void mutate(() => settings!.removeMember(member.userId))}>Remove</button>}</li>)}</ul></section>
    <section><h2>Notifications</h2><label><input type="checkbox" checked={emailEnabled} onChange={(event) => { const checked = event.target.checked; setEmailEnabled(checked); void mutate(() => settings!.updatePreferences({ emailNotificationsEnabled: checked })); }} />Email notifications</label></section>
    <section><h2>Accounts and access</h2><button type="button" onClick={() => navigate('/tools/agent-settings')}>AI accounts and agent settings</button><button type="button" onClick={() => navigate('/integrations')}>Google, Gmail, and Planning Center</button><button type="button" onClick={() => navigate('/mobile-access')}>Mobile access</button><button type="button" onClick={() => navigate('/tools/brain')}>Semantic memory and memory vault</button>{auth?.auth?.logout && <button type="button" onClick={() => void auth.auth!.logout!()}>Sign out</button>}</section>
    <section><h2>Runtime and updates</h2><p>Version: {shell?.appVersion ?? 'development'}. API: {runtime.api}. Engine: {runtime.engine}.</p><p>Restart Rhythm to restart the owned local runtime.</p>{shell?.updates && <button type="button" onClick={() => void shell.updates!.openDownloadPage()}>Check Rhythm releases</button>}</section>
  </section>;
}
