/**
 * Research → Vault entry defaults (Issue #847, life-02).
 *
 * MAINTAINER FORMAT (2026-07-02, supersedes the earlier provisional
 * `research/` default): completed research lands as Research Database
 * ENTRIES in the maintainer's existing theological-study vault structure,
 * per the vault's own intake workflow
 * (`Resources/theological-study/Research Entry Intake.md`) and template
 * (`Templates/Theology - Research Entry.md`):
 *
 *   - Folder: `Resources/theological-study/Research Database/Entries/<topical-subfolder>/`
 *   - Filename: `<slugged-title>.md` (NOT date-prefixed)
 *   - Frontmatter: `type: "entry"` is CRITICAL — the Research Entries base
 *     only picks up notes with that exact field.
 *
 * This module exists so a later change to the entries root, the subfolder
 * taxonomy, or the frontmatter schema is a change HERE, not a hunt through
 * `researchVaultWriteService.ts`. Nothing outside this file should hard-code
 * the folder names, filename shape, or frontmatter key names.
 */

/** Vault-root-relative root that research entries are written under. */
export const RESEARCH_ENTRIES_ROOT =
  'Resources/theological-study/Research Database/Entries';

/** Subfolder used when no topical subfolder matches the material. */
export const RESEARCH_ENTRY_FALLBACK_SUBFOLDER = '13-miscellaneous';

/**
 * Topical subfolders (mirrors the vault's existing Entries/ structure) with
 * the keyword lists the best-match heuristic scores against. Keys are the
 * exact on-disk folder names. Keywords are matched case-insensitively as
 * whole words against the entry's topic + title text; the subfolder with the
 * most hits wins, ties broken by list order, zero hits → the fallback.
 */
export const RESEARCH_ENTRY_SUBFOLDER_KEYWORDS: ReadonlyArray<
  readonly [subfolder: string, keywords: readonly string[]]
> = [
  ['01-worship-theology-foundations', ['worship', 'theology', 'foundations', 'doxology', 'glory', 'presence']],
  ['02-sacraments-baptism-eucharist', ['sacrament', 'sacraments', 'baptism', 'eucharist', 'communion', "lord's supper", 'table']],
  ['03-liturgy-liturgical-history', ['liturgy', 'liturgical', 'rite', 'ritual', 'ordo', 'lectionary', 'calendar', 'history']],
  ['04-old-testament-worship', ['old testament', 'temple', 'tabernacle', 'psalms', 'levites', 'sacrifice', 'torah', 'israel']],
  ['05-new-testament-worship', ['new testament', 'early church', 'apostolic', 'synagogue', 'pauline', 'gospels']],
  ['06-daily-office-prayer', ['daily office', 'prayer', 'hours', 'matins', 'vespers', 'compline', 'devotion']],
  ['07-worship-culture-inculturation', ['culture', 'inculturation', 'contextualization', 'global', 'indigenous', 'multicultural']],
  ['08-music-arts-in-worship', ['music', 'song', 'hymn', 'hymnody', 'arts', 'aesthetics', 'singing', 'instruments', 'psalmody']],
  ['09-christian-initiation-confirmation', ['initiation', 'confirmation', 'catechesis', 'catechumenate', 'profession of faith']],
  ['10-sending-mission-benediction', ['sending', 'mission', 'missional', 'benediction', 'blessing', 'commissioning']],
  ['11-reformed-crc-worship', ['reformed', 'crc', 'calvin', 'calvinist', 'presbyterian', 'covenant', 'confessions']],
  ['12-sources-reading-notes', ['reading notes', 'bibliography', 'sources', 'book review', 'literature']],
  ['13-miscellaneous', []],
  ['14-technology-ai-imago', ['technology', 'ai', 'artificial intelligence', 'digital', 'imago', 'imago dei', 'media', 'livestream']],
] as const;

/** Informational provenance value for entries generated by the research pipeline. */
export const RESEARCH_NOTE_SOURCE = 'research-job' as const;

/**
 * Ordered frontmatter keys for a research entry (documents the locked
 * schema). `type: "entry"` MUST be present and exact — it drives the vault's
 * Research Entries base. `job_id` is Rhythm's extra provenance key.
 */
export const RESEARCH_ENTRY_FRONTMATTER_KEYS = [
  'type',
  'topic',
  'parent',
  'page',
  'source',
  'author',
  'citation',
  'scripture_references',
  'themes',
  'doctrine_tags',
  'status',
  'tags',
  'job_id',
] as const;

/** The `type` value the Research Entries base filters on. */
export const RESEARCH_ENTRY_TYPE = 'entry' as const;

/** Fixed tags every generated research entry carries (template parity). */
export const RESEARCH_ENTRY_TAGS = ['theology', 'worship', 'research-entry'] as const;

/** Initial workflow status for a freshly generated entry. */
export const RESEARCH_ENTRY_STATUS = 'inbox' as const;

/**
 * Build the research entry filename: `<slugged-title>.md`. `titleSlug` must
 * already be a filesystem-safe slug (see {@link slugForNote} in
 * memoryVaultWriteService, reused as-is by the write service — no second
 * slugger is introduced here). NOT date-prefixed, per the maintainer format.
 */
export function researchEntryFilename(titleSlug: string): string {
  return `${titleSlug}.md`;
}

/**
 * Best-match topical subfolder for an entry: case-insensitive whole-word
 * keyword scoring over the provided text (topic + title). Most hits wins,
 * ties broken by taxonomy order, zero hits → {@link
 * RESEARCH_ENTRY_FALLBACK_SUBFOLDER}.
 */
export function matchEntrySubfolder(text: string): string {
  const haystack = ` ${text.toLowerCase().replace(/[^a-z0-9']+/g, ' ')} `;
  let best = RESEARCH_ENTRY_FALLBACK_SUBFOLDER;
  let bestScore = 0;
  for (const [subfolder, keywords] of RESEARCH_ENTRY_SUBFOLDER_KEYWORDS) {
    let score = 0;
    for (const kw of keywords) {
      if (haystack.includes(` ${kw} `)) score += 1;
    }
    if (score > bestScore) {
      bestScore = score;
      best = subfolder;
    }
  }
  return best;
}
